"""giteaapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from giteaapi.api_helper import APIHelper


class AccessTokenRepresentsAnApiAccessToken(object):
    """Implementation of the 'AccessToken represents an API access token.' model.

    Attributes:
        created_at (datetime): The timestamp when the token was created
        id (int): The unique identifier of the access token
        last_used_at (datetime): The timestamp when the token was last used
        name (str): The name of the access token
        scopes (List[str]): The scopes granted to this access token
        sha_1 (str): The SHA1 hash of the access token
        token_last_eight (str): The last eight characters of the token
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "created_at": "created_at",
        "id": "id",
        "last_used_at": "last_used_at",
        "name": "name",
        "scopes": "scopes",
        "sha_1": "sha1",
        "token_last_eight": "token_last_eight",
    }

    _optionals = [
        "created_at",
        "id",
        "last_used_at",
        "name",
        "scopes",
        "sha_1",
        "token_last_eight",
    ]

    def __init__(
        self,
        created_at=APIHelper.SKIP,
        id=APIHelper.SKIP,
        last_used_at=APIHelper.SKIP,
        name=APIHelper.SKIP,
        scopes=APIHelper.SKIP,
        sha_1=APIHelper.SKIP,
        token_last_eight=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a AccessTokenRepresentsAnApiAccessToken instance."""
        # Initialize members of the class
        if created_at is not APIHelper.SKIP:
            self.created_at =\
                 APIHelper.apply_datetime_converter(
                created_at, APIHelper.RFC3339DateTime)\
                 if created_at else None
        if id is not APIHelper.SKIP:
            self.id = id
        if last_used_at is not APIHelper.SKIP:
            self.last_used_at =\
                 APIHelper.apply_datetime_converter(
                last_used_at, APIHelper.RFC3339DateTime)\
                 if last_used_at else None
        if name is not APIHelper.SKIP:
            self.name = name
        if scopes is not APIHelper.SKIP:
            self.scopes = scopes
        if sha_1 is not APIHelper.SKIP:
            self.sha_1 = sha_1
        if token_last_eight is not APIHelper.SKIP:
            self.token_last_eight = token_last_eight

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        created_at = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("created_at")).datetime\
            if dictionary.get("created_at") else APIHelper.SKIP
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else APIHelper.SKIP
        last_used_at = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("last_used_at")).datetime\
            if dictionary.get("last_used_at") else APIHelper.SKIP
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else APIHelper.SKIP
        scopes =\
            dictionary.get("scopes")\
            if dictionary.get("scopes")\
                else APIHelper.SKIP
        sha_1 =\
            dictionary.get("sha1")\
            if dictionary.get("sha1")\
                else APIHelper.SKIP
        token_last_eight =\
            dictionary.get("token_last_eight")\
            if dictionary.get("token_last_eight")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(created_at,
                   id,
                   last_used_at,
                   name,
                   scopes,
                   sha_1,
                   token_last_eight,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _created_at=(
            self.created_at
            if hasattr(self, "created_at")
            else None
        )
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _last_used_at=(
            self.last_used_at
            if hasattr(self, "last_used_at")
            else None
        )
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _scopes=(
            self.scopes
            if hasattr(self, "scopes")
            else None
        )
        _sha_1=(
            self.sha_1
            if hasattr(self, "sha_1")
            else None
        )
        _token_last_eight=(
            self.token_last_eight
            if hasattr(self, "token_last_eight")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"created_at={_created_at!r}, "
            f"id={_id!r}, "
            f"last_used_at={_last_used_at!r}, "
            f"name={_name!r}, "
            f"scopes={_scopes!r}, "
            f"sha_1={_sha_1!r}, "
            f"token_last_eight={_token_last_eight!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _created_at=(
            self.created_at
            if hasattr(self, "created_at")
            else None
        )
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _last_used_at=(
            self.last_used_at
            if hasattr(self, "last_used_at")
            else None
        )
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _scopes=(
            self.scopes
            if hasattr(self, "scopes")
            else None
        )
        _sha_1=(
            self.sha_1
            if hasattr(self, "sha_1")
            else None
        )
        _token_last_eight=(
            self.token_last_eight
            if hasattr(self, "token_last_eight")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"created_at={_created_at!s}, "
            f"id={_id!s}, "
            f"last_used_at={_last_used_at!s}, "
            f"name={_name!s}, "
            f"scopes={_scopes!s}, "
            f"sha_1={_sha_1!s}, "
            f"token_last_eight={_token_last_eight!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
