"""giteaapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from giteaapi.api_helper import APIHelper


class ActionWorkflowStep(object):
    """Implementation of the 'ActionWorkflowStep' model.

    ActionWorkflowStep represents a step of a WorkflowJob

    Attributes:
        completed_at (datetime): The model property of type datetime.
        conclusion (str): The model property of type str.
        name (str): The model property of type str.
        number (int): The model property of type int.
        started_at (datetime): The model property of type datetime.
        status (str): The model property of type str.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "completed_at": "completed_at",
        "conclusion": "conclusion",
        "name": "name",
        "number": "number",
        "started_at": "started_at",
        "status": "status",
    }

    _optionals = [
        "completed_at",
        "conclusion",
        "name",
        "number",
        "started_at",
        "status",
    ]

    def __init__(
        self,
        completed_at=APIHelper.SKIP,
        conclusion=APIHelper.SKIP,
        name=APIHelper.SKIP,
        number=APIHelper.SKIP,
        started_at=APIHelper.SKIP,
        status=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ActionWorkflowStep instance."""
        # Initialize members of the class
        if completed_at is not APIHelper.SKIP:
            self.completed_at =\
                 APIHelper.apply_datetime_converter(
                completed_at, APIHelper.RFC3339DateTime)\
                 if completed_at else None
        if conclusion is not APIHelper.SKIP:
            self.conclusion = conclusion
        if name is not APIHelper.SKIP:
            self.name = name
        if number is not APIHelper.SKIP:
            self.number = number
        if started_at is not APIHelper.SKIP:
            self.started_at =\
                 APIHelper.apply_datetime_converter(
                started_at, APIHelper.RFC3339DateTime)\
                 if started_at else None
        if status is not APIHelper.SKIP:
            self.status = status

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        completed_at = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("completed_at")).datetime\
            if dictionary.get("completed_at") else APIHelper.SKIP
        conclusion =\
            dictionary.get("conclusion")\
            if dictionary.get("conclusion")\
                else APIHelper.SKIP
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else APIHelper.SKIP
        number =\
            dictionary.get("number")\
            if dictionary.get("number")\
                else APIHelper.SKIP
        started_at = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("started_at")).datetime\
            if dictionary.get("started_at") else APIHelper.SKIP
        status =\
            dictionary.get("status")\
            if dictionary.get("status")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(completed_at,
                   conclusion,
                   name,
                   number,
                   started_at,
                   status,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _completed_at=(
            self.completed_at
            if hasattr(self, "completed_at")
            else None
        )
        _conclusion=(
            self.conclusion
            if hasattr(self, "conclusion")
            else None
        )
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _number=(
            self.number
            if hasattr(self, "number")
            else None
        )
        _started_at=(
            self.started_at
            if hasattr(self, "started_at")
            else None
        )
        _status=(
            self.status
            if hasattr(self, "status")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"completed_at={_completed_at!r}, "
            f"conclusion={_conclusion!r}, "
            f"name={_name!r}, "
            f"number={_number!r}, "
            f"started_at={_started_at!r}, "
            f"status={_status!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _completed_at=(
            self.completed_at
            if hasattr(self, "completed_at")
            else None
        )
        _conclusion=(
            self.conclusion
            if hasattr(self, "conclusion")
            else None
        )
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _number=(
            self.number
            if hasattr(self, "number")
            else None
        )
        _started_at=(
            self.started_at
            if hasattr(self, "started_at")
            else None
        )
        _status=(
            self.status
            if hasattr(self, "status")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"completed_at={_completed_at!s}, "
            f"conclusion={_conclusion!s}, "
            f"name={_name!s}, "
            f"number={_number!s}, "
            f"started_at={_started_at!s}, "
            f"status={_status!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
