"""giteaapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from giteaapi.api_helper import APIHelper
from giteaapi.models.action_workflow_run import (
    ActionWorkflowRun,
)


class ActionArtifact(object):
    """Implementation of the 'ActionArtifact' model.

    ActionArtifact represents a ActionArtifact

    Attributes:
        archive_download_url (str): The model property of type str.
        created_at (datetime): The model property of type datetime.
        expired (bool): The model property of type bool.
        expires_at (datetime): The model property of type datetime.
        id (int): The model property of type int.
        name (str): The model property of type str.
        size_in_bytes (int): The model property of type int.
        updated_at (datetime): The model property of type datetime.
        url (str): The model property of type str.
        workflow_run (ActionWorkflowRun): ActionWorkflowRun represents a WorkflowRun
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "archive_download_url": "archive_download_url",
        "created_at": "created_at",
        "expired": "expired",
        "expires_at": "expires_at",
        "id": "id",
        "name": "name",
        "size_in_bytes": "size_in_bytes",
        "updated_at": "updated_at",
        "url": "url",
        "workflow_run": "workflow_run",
    }

    _optionals = [
        "archive_download_url",
        "created_at",
        "expired",
        "expires_at",
        "id",
        "name",
        "size_in_bytes",
        "updated_at",
        "url",
        "workflow_run",
    ]

    def __init__(
        self,
        archive_download_url=APIHelper.SKIP,
        created_at=APIHelper.SKIP,
        expired=APIHelper.SKIP,
        expires_at=APIHelper.SKIP,
        id=APIHelper.SKIP,
        name=APIHelper.SKIP,
        size_in_bytes=APIHelper.SKIP,
        updated_at=APIHelper.SKIP,
        url=APIHelper.SKIP,
        workflow_run=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ActionArtifact instance."""
        # Initialize members of the class
        if archive_download_url is not APIHelper.SKIP:
            self.archive_download_url = archive_download_url
        if created_at is not APIHelper.SKIP:
            self.created_at =\
                 APIHelper.apply_datetime_converter(
                created_at, APIHelper.RFC3339DateTime)\
                 if created_at else None
        if expired is not APIHelper.SKIP:
            self.expired = expired
        if expires_at is not APIHelper.SKIP:
            self.expires_at =\
                 APIHelper.apply_datetime_converter(
                expires_at, APIHelper.RFC3339DateTime)\
                 if expires_at else None
        if id is not APIHelper.SKIP:
            self.id = id
        if name is not APIHelper.SKIP:
            self.name = name
        if size_in_bytes is not APIHelper.SKIP:
            self.size_in_bytes = size_in_bytes
        if updated_at is not APIHelper.SKIP:
            self.updated_at =\
                 APIHelper.apply_datetime_converter(
                updated_at, APIHelper.RFC3339DateTime)\
                 if updated_at else None
        if url is not APIHelper.SKIP:
            self.url = url
        if workflow_run is not APIHelper.SKIP:
            self.workflow_run = workflow_run

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        archive_download_url =\
            dictionary.get("archive_download_url")\
            if dictionary.get("archive_download_url")\
                else APIHelper.SKIP
        created_at = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("created_at")).datetime\
            if dictionary.get("created_at") else APIHelper.SKIP
        expired =\
            dictionary.get("expired")\
            if "expired" in dictionary.keys()\
                else APIHelper.SKIP
        expires_at = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("expires_at")).datetime\
            if dictionary.get("expires_at") else APIHelper.SKIP
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else APIHelper.SKIP
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else APIHelper.SKIP
        size_in_bytes =\
            dictionary.get("size_in_bytes")\
            if dictionary.get("size_in_bytes")\
                else APIHelper.SKIP
        updated_at = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("updated_at")).datetime\
            if dictionary.get("updated_at") else APIHelper.SKIP
        url =\
            dictionary.get("url")\
            if dictionary.get("url")\
                else APIHelper.SKIP
        workflow_run =\
            ActionWorkflowRun.from_dictionary(
                dictionary.get("workflow_run"))\
                if "workflow_run" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(archive_download_url,
                   created_at,
                   expired,
                   expires_at,
                   id,
                   name,
                   size_in_bytes,
                   updated_at,
                   url,
                   workflow_run,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _archive_download_url=(
            self.archive_download_url
            if hasattr(self, "archive_download_url")
            else None
        )
        _created_at=(
            self.created_at
            if hasattr(self, "created_at")
            else None
        )
        _expired=(
            self.expired
            if hasattr(self, "expired")
            else None
        )
        _expires_at=(
            self.expires_at
            if hasattr(self, "expires_at")
            else None
        )
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _size_in_bytes=(
            self.size_in_bytes
            if hasattr(self, "size_in_bytes")
            else None
        )
        _updated_at=(
            self.updated_at
            if hasattr(self, "updated_at")
            else None
        )
        _url=(
            self.url
            if hasattr(self, "url")
            else None
        )
        _workflow_run=(
            self.workflow_run
            if hasattr(self, "workflow_run")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"archive_download_url={_archive_download_url!r}, "
            f"created_at={_created_at!r}, "
            f"expired={_expired!r}, "
            f"expires_at={_expires_at!r}, "
            f"id={_id!r}, "
            f"name={_name!r}, "
            f"size_in_bytes={_size_in_bytes!r}, "
            f"updated_at={_updated_at!r}, "
            f"url={_url!r}, "
            f"workflow_run={_workflow_run!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _archive_download_url=(
            self.archive_download_url
            if hasattr(self, "archive_download_url")
            else None
        )
        _created_at=(
            self.created_at
            if hasattr(self, "created_at")
            else None
        )
        _expired=(
            self.expired
            if hasattr(self, "expired")
            else None
        )
        _expires_at=(
            self.expires_at
            if hasattr(self, "expires_at")
            else None
        )
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _size_in_bytes=(
            self.size_in_bytes
            if hasattr(self, "size_in_bytes")
            else None
        )
        _updated_at=(
            self.updated_at
            if hasattr(self, "updated_at")
            else None
        )
        _url=(
            self.url
            if hasattr(self, "url")
            else None
        )
        _workflow_run=(
            self.workflow_run
            if hasattr(self, "workflow_run")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"archive_download_url={_archive_download_url!s}, "
            f"created_at={_created_at!s}, "
            f"expired={_expired!s}, "
            f"expires_at={_expires_at!s}, "
            f"id={_id!s}, "
            f"name={_name!s}, "
            f"size_in_bytes={_size_in_bytes!s}, "
            f"updated_at={_updated_at!s}, "
            f"url={_url!s}, "
            f"workflow_run={_workflow_run!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
