"""giteaapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from giteaapi.api_helper import APIHelper


class CommitUserContainsInformationOfAUserInTheContextOfACommit(object):
    """Implementation of the
    'CommitUser contains information of a user in the context of a commit.' model.

    Attributes:
        date (str): Date is the commit date in string format
        email (str): The model property of type str.
        name (str): Name is the person's name
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "date": "date",
        "email": "email",
        "name": "name",
    }

    _optionals = [
        "date",
        "email",
        "name",
    ]

    def __init__(
        self,
        date=APIHelper.SKIP,
        email=APIHelper.SKIP,
        name=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a
        CommitUserContainsInformationOfAUserInTheContextOfACommit instance.
        """
        # Initialize members of the class
        if date is not APIHelper.SKIP:
            self.date = date
        if email is not APIHelper.SKIP:
            self.email = email
        if name is not APIHelper.SKIP:
            self.name = name

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        date =\
            dictionary.get("date")\
            if dictionary.get("date")\
                else APIHelper.SKIP
        email =\
            dictionary.get("email")\
            if dictionary.get("email")\
                else APIHelper.SKIP
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(date,
                   email,
                   name,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _date=(
            self.date
            if hasattr(self, "date")
            else None
        )
        _email=(
            self.email
            if hasattr(self, "email")
            else None
        )
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"date={_date!r}, "
            f"email={_email!r}, "
            f"name={_name!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _date=(
            self.date
            if hasattr(self, "date")
            else None
        )
        _email=(
            self.email
            if hasattr(self, "email")
            else None
        )
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"date={_date!s}, "
            f"email={_email!s}, "
            f"name={_name!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
