"""giteaapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from giteaapi.api_helper import APIHelper
from giteaapi.models.attachment import Attachment
from giteaapi.models.user import User


class Comment(object):
    """Implementation of the 'Comment' model.

    Comment represents a comment on a commit or issue

    Attributes:
        assets (List[Attachment]): Attachments contains files attached to the comment
        body (str): Body contains the comment text content
        created_at (datetime): The model property of type datetime.
        html_url (str): HTMLURL is the web URL for viewing the comment
        id (int): ID is the unique identifier for the comment
        issue_url (str): IssueURL is the API URL for the issue
        original_author (str): OriginalAuthor is the original author name (for
            imported comments)
        original_author_id (int): OriginalAuthorID is the original author ID (for
            imported comments)
        pull_request_url (str): PRURL is the API URL for the pull request (if
            applicable)
        updated_at (datetime): The model property of type datetime.
        user (User): User represents a user
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "assets": "assets",
        "body": "body",
        "created_at": "created_at",
        "html_url": "html_url",
        "id": "id",
        "issue_url": "issue_url",
        "original_author": "original_author",
        "original_author_id": "original_author_id",
        "pull_request_url": "pull_request_url",
        "updated_at": "updated_at",
        "user": "user",
    }

    _optionals = [
        "assets",
        "body",
        "created_at",
        "html_url",
        "id",
        "issue_url",
        "original_author",
        "original_author_id",
        "pull_request_url",
        "updated_at",
        "user",
    ]

    def __init__(
        self,
        assets=APIHelper.SKIP,
        body=APIHelper.SKIP,
        created_at=APIHelper.SKIP,
        html_url=APIHelper.SKIP,
        id=APIHelper.SKIP,
        issue_url=APIHelper.SKIP,
        original_author=APIHelper.SKIP,
        original_author_id=APIHelper.SKIP,
        pull_request_url=APIHelper.SKIP,
        updated_at=APIHelper.SKIP,
        user=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Comment instance."""
        # Initialize members of the class
        if assets is not APIHelper.SKIP:
            self.assets = assets
        if body is not APIHelper.SKIP:
            self.body = body
        if created_at is not APIHelper.SKIP:
            self.created_at =\
                 APIHelper.apply_datetime_converter(
                created_at, APIHelper.RFC3339DateTime)\
                 if created_at else None
        if html_url is not APIHelper.SKIP:
            self.html_url = html_url
        if id is not APIHelper.SKIP:
            self.id = id
        if issue_url is not APIHelper.SKIP:
            self.issue_url = issue_url
        if original_author is not APIHelper.SKIP:
            self.original_author = original_author
        if original_author_id is not APIHelper.SKIP:
            self.original_author_id = original_author_id
        if pull_request_url is not APIHelper.SKIP:
            self.pull_request_url = pull_request_url
        if updated_at is not APIHelper.SKIP:
            self.updated_at =\
                 APIHelper.apply_datetime_converter(
                updated_at, APIHelper.RFC3339DateTime)\
                 if updated_at else None
        if user is not APIHelper.SKIP:
            self.user = user

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        assets = None
        if dictionary.get("assets") is not None:
            assets = [
                Attachment.from_dictionary(x)
                    for x in dictionary.get("assets")
            ]
        else:
            assets = APIHelper.SKIP
        body =\
            dictionary.get("body")\
            if dictionary.get("body")\
                else APIHelper.SKIP
        created_at = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("created_at")).datetime\
            if dictionary.get("created_at") else APIHelper.SKIP
        html_url =\
            dictionary.get("html_url")\
            if dictionary.get("html_url")\
                else APIHelper.SKIP
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else APIHelper.SKIP
        issue_url =\
            dictionary.get("issue_url")\
            if dictionary.get("issue_url")\
                else APIHelper.SKIP
        original_author =\
            dictionary.get("original_author")\
            if dictionary.get("original_author")\
                else APIHelper.SKIP
        original_author_id =\
            dictionary.get("original_author_id")\
            if dictionary.get("original_author_id")\
                else APIHelper.SKIP
        pull_request_url =\
            dictionary.get("pull_request_url")\
            if dictionary.get("pull_request_url")\
                else APIHelper.SKIP
        updated_at = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("updated_at")).datetime\
            if dictionary.get("updated_at") else APIHelper.SKIP
        user =\
            User.from_dictionary(
                dictionary.get("user"))\
                if "user" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(assets,
                   body,
                   created_at,
                   html_url,
                   id,
                   issue_url,
                   original_author,
                   original_author_id,
                   pull_request_url,
                   updated_at,
                   user,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _assets=(
            self.assets
            if hasattr(self, "assets")
            else None
        )
        _body=(
            self.body
            if hasattr(self, "body")
            else None
        )
        _created_at=(
            self.created_at
            if hasattr(self, "created_at")
            else None
        )
        _html_url=(
            self.html_url
            if hasattr(self, "html_url")
            else None
        )
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _issue_url=(
            self.issue_url
            if hasattr(self, "issue_url")
            else None
        )
        _original_author=(
            self.original_author
            if hasattr(self, "original_author")
            else None
        )
        _original_author_id=(
            self.original_author_id
            if hasattr(self, "original_author_id")
            else None
        )
        _pull_request_url=(
            self.pull_request_url
            if hasattr(self, "pull_request_url")
            else None
        )
        _updated_at=(
            self.updated_at
            if hasattr(self, "updated_at")
            else None
        )
        _user=(
            self.user
            if hasattr(self, "user")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"assets={_assets!r}, "
            f"body={_body!r}, "
            f"created_at={_created_at!r}, "
            f"html_url={_html_url!r}, "
            f"id={_id!r}, "
            f"issue_url={_issue_url!r}, "
            f"original_author={_original_author!r}, "
            f"original_author_id={_original_author_id!r}, "
            f"pull_request_url={_pull_request_url!r}, "
            f"updated_at={_updated_at!r}, "
            f"user={_user!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _assets=(
            self.assets
            if hasattr(self, "assets")
            else None
        )
        _body=(
            self.body
            if hasattr(self, "body")
            else None
        )
        _created_at=(
            self.created_at
            if hasattr(self, "created_at")
            else None
        )
        _html_url=(
            self.html_url
            if hasattr(self, "html_url")
            else None
        )
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _issue_url=(
            self.issue_url
            if hasattr(self, "issue_url")
            else None
        )
        _original_author=(
            self.original_author
            if hasattr(self, "original_author")
            else None
        )
        _original_author_id=(
            self.original_author_id
            if hasattr(self, "original_author_id")
            else None
        )
        _pull_request_url=(
            self.pull_request_url
            if hasattr(self, "pull_request_url")
            else None
        )
        _updated_at=(
            self.updated_at
            if hasattr(self, "updated_at")
            else None
        )
        _user=(
            self.user
            if hasattr(self, "user")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"assets={_assets!s}, "
            f"body={_body!s}, "
            f"created_at={_created_at!s}, "
            f"html_url={_html_url!s}, "
            f"id={_id!s}, "
            f"issue_url={_issue_url!s}, "
            f"original_author={_original_author!s}, "
            f"original_author_id={_original_author_id!s}, "
            f"pull_request_url={_pull_request_url!s}, "
            f"updated_at={_updated_at!s}, "
            f"user={_user!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
