"""giteaapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from giteaapi.api_helper import APIHelper


class CreateTagOption(object):
    """Implementation of the 'CreateTagOption' model.

    CreateTagOption options when creating a tag

    Attributes:
        message (str): The message to associate with the tag
        tag_name (str): The model property of type str.
        target (str): The target commit SHA or branch name for the tag
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "tag_name": "tag_name",
        "message": "message",
        "target": "target",
    }

    _optionals = [
        "message",
        "target",
    ]

    def __init__(
        self,
        tag_name=None,
        message=APIHelper.SKIP,
        target=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a CreateTagOption instance."""
        # Initialize members of the class
        if message is not APIHelper.SKIP:
            self.message = message
        self.tag_name = tag_name
        if target is not APIHelper.SKIP:
            self.target = target

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        tag_name =\
            dictionary.get("tag_name")\
            if dictionary.get("tag_name")\
                else None
        message =\
            dictionary.get("message")\
            if dictionary.get("message")\
                else APIHelper.SKIP
        target =\
            dictionary.get("target")\
            if dictionary.get("target")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(tag_name,
                   message,
                   target,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _message=(
            self.message
            if hasattr(self, "message")
            else None
        )
        _tag_name=self.tag_name
        _target=(
            self.target
            if hasattr(self, "target")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"message={_message!r}, "
            f"tag_name={_tag_name!r}, "
            f"target={_target!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _message=(
            self.message
            if hasattr(self, "message")
            else None
        )
        _tag_name=self.tag_name
        _target=(
            self.target
            if hasattr(self, "target")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"message={_message!s}, "
            f"tag_name={_tag_name!s}, "
            f"target={_target!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
