"""giteaapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from giteaapi.api_helper import APIHelper


class CreateHookOption(object):
    """Implementation of the 'CreateHookOption' model.

    CreateHookOption options when create a hook

    Attributes:
        active (bool): The model property of type bool.
        authorization_header (str): Authorization header to include in webhook
            requests
        branch_filter (str): Branch filter pattern to determine which branches
            trigger the webhook
        config (Dict[str, str]): CreateHookOptionConfig has all config options in it
            required are "content_type" and "url" Required
        events (List[str]): List of events that will trigger this webhook
        name (str): Optional human-readable name for the webhook
        mtype (Type): The model property of type Type.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "config": "config",
        "mtype": "type",
        "active": "active",
        "authorization_header": "authorization_header",
        "branch_filter": "branch_filter",
        "events": "events",
        "name": "name",
    }

    _optionals = [
        "active",
        "authorization_header",
        "branch_filter",
        "events",
        "name",
    ]

    def __init__(
        self,
        config=None,
        mtype=None,
        active=False,
        authorization_header=APIHelper.SKIP,
        branch_filter=APIHelper.SKIP,
        events=APIHelper.SKIP,
        name=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a CreateHookOption instance."""
        # Initialize members of the class
        self.active = active
        if authorization_header is not APIHelper.SKIP:
            self.authorization_header = authorization_header
        if branch_filter is not APIHelper.SKIP:
            self.branch_filter = branch_filter
        self.config = config
        if events is not APIHelper.SKIP:
            self.events = events
        if name is not APIHelper.SKIP:
            self.name = name
        self.mtype = mtype

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        config =\
            dictionary.get("config")\
            if dictionary.get("config")\
                else None
        mtype =\
            dictionary.get("type")\
            if dictionary.get("type")\
                else None
        active =\
            dictionary.get("active")\
            if dictionary.get("active")\
                else False
        authorization_header =\
            dictionary.get("authorization_header")\
            if dictionary.get("authorization_header")\
                else APIHelper.SKIP
        branch_filter =\
            dictionary.get("branch_filter")\
            if dictionary.get("branch_filter")\
                else APIHelper.SKIP
        events =\
            dictionary.get("events")\
            if dictionary.get("events")\
                else APIHelper.SKIP
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(config,
                   mtype,
                   active,
                   authorization_header,
                   branch_filter,
                   events,
                   name,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _active=(
            self.active
            if hasattr(self, "active")
            else None
        )
        _authorization_header=(
            self.authorization_header
            if hasattr(self, "authorization_header")
            else None
        )
        _branch_filter=(
            self.branch_filter
            if hasattr(self, "branch_filter")
            else None
        )
        _config=self.config
        _events=(
            self.events
            if hasattr(self, "events")
            else None
        )
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _mtype=self.mtype
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"active={_active!r}, "
            f"authorization_header={_authorization_header!r}, "
            f"branch_filter={_branch_filter!r}, "
            f"config={_config!r}, "
            f"events={_events!r}, "
            f"name={_name!r}, "
            f"mtype={_mtype!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _active=(
            self.active
            if hasattr(self, "active")
            else None
        )
        _authorization_header=(
            self.authorization_header
            if hasattr(self, "authorization_header")
            else None
        )
        _branch_filter=(
            self.branch_filter
            if hasattr(self, "branch_filter")
            else None
        )
        _config=self.config
        _events=(
            self.events
            if hasattr(self, "events")
            else None
        )
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _mtype=self.mtype
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"active={_active!s}, "
            f"authorization_header={_authorization_header!s}, "
            f"branch_filter={_branch_filter!s}, "
            f"config={_config!s}, "
            f"events={_events!s}, "
            f"name={_name!s}, "
            f"mtype={_mtype!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
