"""giteaapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from giteaapi.api_helper import APIHelper


class CreateOrgOption(object):
    """Implementation of the 'CreateOrgOption' model.

    CreateOrgOption options for creating an organization

    Attributes:
        description (str): The description of the organization
        email (str): The email address of the organization
        full_name (str): The full display name of the organization
        location (str): The location of the organization
        repo_admin_change_team_access (bool): Whether repository administrators can
            change team access
        username (str): username of the organization
        visibility (Visibility3): possible values are `public` (default), `limited`
            or `private` public UserVisibilityPublic limited UserVisibilityLimited
            private UserVisibilityPrivate
        website (str): The website URL of the organization
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "username": "username",
        "description": "description",
        "email": "email",
        "full_name": "full_name",
        "location": "location",
        "repo_admin_change_team_access": "repo_admin_change_team_access",
        "visibility": "visibility",
        "website": "website",
    }

    _optionals = [
        "description",
        "email",
        "full_name",
        "location",
        "repo_admin_change_team_access",
        "visibility",
        "website",
    ]

    def __init__(
        self,
        username=None,
        description=APIHelper.SKIP,
        email=APIHelper.SKIP,
        full_name=APIHelper.SKIP,
        location=APIHelper.SKIP,
        repo_admin_change_team_access=APIHelper.SKIP,
        visibility=APIHelper.SKIP,
        website=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a CreateOrgOption instance."""
        # Initialize members of the class
        if description is not APIHelper.SKIP:
            self.description = description
        if email is not APIHelper.SKIP:
            self.email = email
        if full_name is not APIHelper.SKIP:
            self.full_name = full_name
        if location is not APIHelper.SKIP:
            self.location = location
        if repo_admin_change_team_access is not APIHelper.SKIP:
            self.repo_admin_change_team_access = repo_admin_change_team_access
        self.username = username
        if visibility is not APIHelper.SKIP:
            self.visibility = visibility
        if website is not APIHelper.SKIP:
            self.website = website

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        username =\
            dictionary.get("username")\
            if dictionary.get("username")\
                else None
        description =\
            dictionary.get("description")\
            if dictionary.get("description")\
                else APIHelper.SKIP
        email =\
            dictionary.get("email")\
            if dictionary.get("email")\
                else APIHelper.SKIP
        full_name =\
            dictionary.get("full_name")\
            if dictionary.get("full_name")\
                else APIHelper.SKIP
        location =\
            dictionary.get("location")\
            if dictionary.get("location")\
                else APIHelper.SKIP
        repo_admin_change_team_access =\
            dictionary.get("repo_admin_change_team_access")\
            if "repo_admin_change_team_access" in dictionary.keys()\
                else APIHelper.SKIP
        visibility =\
            dictionary.get("visibility")\
            if dictionary.get("visibility")\
                else APIHelper.SKIP
        website =\
            dictionary.get("website")\
            if dictionary.get("website")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(username,
                   description,
                   email,
                   full_name,
                   location,
                   repo_admin_change_team_access,
                   visibility,
                   website,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _email=(
            self.email
            if hasattr(self, "email")
            else None
        )
        _full_name=(
            self.full_name
            if hasattr(self, "full_name")
            else None
        )
        _location=(
            self.location
            if hasattr(self, "location")
            else None
        )
        _repo_admin_change_team_access=(
            self.repo_admin_change_team_access
            if hasattr(self, "repo_admin_change_team_access")
            else None
        )
        _username=self.username
        _visibility=(
            self.visibility
            if hasattr(self, "visibility")
            else None
        )
        _website=(
            self.website
            if hasattr(self, "website")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"description={_description!r}, "
            f"email={_email!r}, "
            f"full_name={_full_name!r}, "
            f"location={_location!r}, "
            f"repo_admin_change_team_access={_repo_admin_change_team_access!r}, "
            f"username={_username!r}, "
            f"visibility={_visibility!r}, "
            f"website={_website!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _email=(
            self.email
            if hasattr(self, "email")
            else None
        )
        _full_name=(
            self.full_name
            if hasattr(self, "full_name")
            else None
        )
        _location=(
            self.location
            if hasattr(self, "location")
            else None
        )
        _repo_admin_change_team_access=(
            self.repo_admin_change_team_access
            if hasattr(self, "repo_admin_change_team_access")
            else None
        )
        _username=self.username
        _visibility=(
            self.visibility
            if hasattr(self, "visibility")
            else None
        )
        _website=(
            self.website
            if hasattr(self, "website")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"description={_description!s}, "
            f"email={_email!s}, "
            f"full_name={_full_name!s}, "
            f"location={_location!s}, "
            f"repo_admin_change_team_access={_repo_admin_change_team_access!s}, "
            f"username={_username!s}, "
            f"visibility={_visibility!s}, "
            f"website={_website!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
