"""giteaapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from giteaapi.api_helper import APIHelper


class CreateRepoOption(object):
    """Implementation of the 'CreateRepoOption' model.

    CreateRepoOption options when creating repository

    Attributes:
        auto_init (bool): Whether the repository should be auto-initialized?
        default_branch (str): DefaultBranch of the repository (used when initializes
            and in template)
        description (str): Description of the repository to create
        gitignores (str): Gitignores to use
        issue_labels (str): Label-Set to use
        license (str): License to use
        name (str): Name of the repository to create
        object_format_name (ObjectFormatName1): ObjectFormatName of the underlying
            git repository, empty string for default (sha1) sha1 ObjectFormatSHA1
            sha256 ObjectFormatSHA256
        private (bool): Whether the repository is private
        readme (str): Readme of the repository to create
        template (bool): Whether the repository is template
        trust_model (TrustModel): TrustModel of the repository
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "name": "name",
        "auto_init": "auto_init",
        "default_branch": "default_branch",
        "description": "description",
        "gitignores": "gitignores",
        "issue_labels": "issue_labels",
        "license": "license",
        "object_format_name": "object_format_name",
        "private": "private",
        "readme": "readme",
        "template": "template",
        "trust_model": "trust_model",
    }

    _optionals = [
        "auto_init",
        "default_branch",
        "description",
        "gitignores",
        "issue_labels",
        "license",
        "object_format_name",
        "private",
        "readme",
        "template",
        "trust_model",
    ]

    def __init__(
        self,
        name=None,
        auto_init=APIHelper.SKIP,
        default_branch=APIHelper.SKIP,
        description=APIHelper.SKIP,
        gitignores=APIHelper.SKIP,
        issue_labels=APIHelper.SKIP,
        license=APIHelper.SKIP,
        object_format_name=APIHelper.SKIP,
        private=APIHelper.SKIP,
        readme=APIHelper.SKIP,
        template=APIHelper.SKIP,
        trust_model=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a CreateRepoOption instance."""
        # Initialize members of the class
        if auto_init is not APIHelper.SKIP:
            self.auto_init = auto_init
        if default_branch is not APIHelper.SKIP:
            self.default_branch = default_branch
        if description is not APIHelper.SKIP:
            self.description = description
        if gitignores is not APIHelper.SKIP:
            self.gitignores = gitignores
        if issue_labels is not APIHelper.SKIP:
            self.issue_labels = issue_labels
        if license is not APIHelper.SKIP:
            self.license = license
        self.name = name
        if object_format_name is not APIHelper.SKIP:
            self.object_format_name = object_format_name
        if private is not APIHelper.SKIP:
            self.private = private
        if readme is not APIHelper.SKIP:
            self.readme = readme
        if template is not APIHelper.SKIP:
            self.template = template
        if trust_model is not APIHelper.SKIP:
            self.trust_model = trust_model

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else None
        auto_init =\
            dictionary.get("auto_init")\
            if "auto_init" in dictionary.keys()\
                else APIHelper.SKIP
        default_branch =\
            dictionary.get("default_branch")\
            if dictionary.get("default_branch")\
                else APIHelper.SKIP
        description =\
            dictionary.get("description")\
            if dictionary.get("description")\
                else APIHelper.SKIP
        gitignores =\
            dictionary.get("gitignores")\
            if dictionary.get("gitignores")\
                else APIHelper.SKIP
        issue_labels =\
            dictionary.get("issue_labels")\
            if dictionary.get("issue_labels")\
                else APIHelper.SKIP
        license =\
            dictionary.get("license")\
            if dictionary.get("license")\
                else APIHelper.SKIP
        object_format_name =\
            dictionary.get("object_format_name")\
            if dictionary.get("object_format_name")\
                else APIHelper.SKIP
        private =\
            dictionary.get("private")\
            if "private" in dictionary.keys()\
                else APIHelper.SKIP
        readme =\
            dictionary.get("readme")\
            if dictionary.get("readme")\
                else APIHelper.SKIP
        template =\
            dictionary.get("template")\
            if "template" in dictionary.keys()\
                else APIHelper.SKIP
        trust_model =\
            dictionary.get("trust_model")\
            if dictionary.get("trust_model")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(name,
                   auto_init,
                   default_branch,
                   description,
                   gitignores,
                   issue_labels,
                   license,
                   object_format_name,
                   private,
                   readme,
                   template,
                   trust_model,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _auto_init=(
            self.auto_init
            if hasattr(self, "auto_init")
            else None
        )
        _default_branch=(
            self.default_branch
            if hasattr(self, "default_branch")
            else None
        )
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _gitignores=(
            self.gitignores
            if hasattr(self, "gitignores")
            else None
        )
        _issue_labels=(
            self.issue_labels
            if hasattr(self, "issue_labels")
            else None
        )
        _license=(
            self.license
            if hasattr(self, "license")
            else None
        )
        _name=self.name
        _object_format_name=(
            self.object_format_name
            if hasattr(self, "object_format_name")
            else None
        )
        _private=(
            self.private
            if hasattr(self, "private")
            else None
        )
        _readme=(
            self.readme
            if hasattr(self, "readme")
            else None
        )
        _template=(
            self.template
            if hasattr(self, "template")
            else None
        )
        _trust_model=(
            self.trust_model
            if hasattr(self, "trust_model")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"auto_init={_auto_init!r}, "
            f"default_branch={_default_branch!r}, "
            f"description={_description!r}, "
            f"gitignores={_gitignores!r}, "
            f"issue_labels={_issue_labels!r}, "
            f"license={_license!r}, "
            f"name={_name!r}, "
            f"object_format_name={_object_format_name!r}, "
            f"private={_private!r}, "
            f"readme={_readme!r}, "
            f"template={_template!r}, "
            f"trust_model={_trust_model!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _auto_init=(
            self.auto_init
            if hasattr(self, "auto_init")
            else None
        )
        _default_branch=(
            self.default_branch
            if hasattr(self, "default_branch")
            else None
        )
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _gitignores=(
            self.gitignores
            if hasattr(self, "gitignores")
            else None
        )
        _issue_labels=(
            self.issue_labels
            if hasattr(self, "issue_labels")
            else None
        )
        _license=(
            self.license
            if hasattr(self, "license")
            else None
        )
        _name=self.name
        _object_format_name=(
            self.object_format_name
            if hasattr(self, "object_format_name")
            else None
        )
        _private=(
            self.private
            if hasattr(self, "private")
            else None
        )
        _readme=(
            self.readme
            if hasattr(self, "readme")
            else None
        )
        _template=(
            self.template
            if hasattr(self, "template")
            else None
        )
        _trust_model=(
            self.trust_model
            if hasattr(self, "trust_model")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"auto_init={_auto_init!s}, "
            f"default_branch={_default_branch!s}, "
            f"description={_description!s}, "
            f"gitignores={_gitignores!s}, "
            f"issue_labels={_issue_labels!s}, "
            f"license={_license!s}, "
            f"name={_name!s}, "
            f"object_format_name={_object_format_name!s}, "
            f"private={_private!s}, "
            f"readme={_readme!s}, "
            f"template={_template!s}, "
            f"trust_model={_trust_model!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
