"""giteaapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from giteaapi.api_helper import APIHelper


class CreatePullReviewComment(object):
    """Implementation of the 'CreatePullReviewComment' model.

    CreatePullReviewComment represent a review comment for creation api

    Attributes:
        body (str): The model property of type str.
        new_position (int): if comment to new file line or 0
        old_position (int): if comment to old file line or 0
        path (str): the tree path
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "body": "body",
        "new_position": "new_position",
        "old_position": "old_position",
        "path": "path",
    }

    _optionals = [
        "body",
        "new_position",
        "old_position",
        "path",
    ]

    def __init__(
        self,
        body=APIHelper.SKIP,
        new_position=APIHelper.SKIP,
        old_position=APIHelper.SKIP,
        path=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a CreatePullReviewComment instance."""
        # Initialize members of the class
        if body is not APIHelper.SKIP:
            self.body = body
        if new_position is not APIHelper.SKIP:
            self.new_position = new_position
        if old_position is not APIHelper.SKIP:
            self.old_position = old_position
        if path is not APIHelper.SKIP:
            self.path = path

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        body =\
            dictionary.get("body")\
            if dictionary.get("body")\
                else APIHelper.SKIP
        new_position =\
            dictionary.get("new_position")\
            if dictionary.get("new_position")\
                else APIHelper.SKIP
        old_position =\
            dictionary.get("old_position")\
            if dictionary.get("old_position")\
                else APIHelper.SKIP
        path =\
            dictionary.get("path")\
            if dictionary.get("path")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(body,
                   new_position,
                   old_position,
                   path,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _body=(
            self.body
            if hasattr(self, "body")
            else None
        )
        _new_position=(
            self.new_position
            if hasattr(self, "new_position")
            else None
        )
        _old_position=(
            self.old_position
            if hasattr(self, "old_position")
            else None
        )
        _path=(
            self.path
            if hasattr(self, "path")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"body={_body!r}, "
            f"new_position={_new_position!r}, "
            f"old_position={_old_position!r}, "
            f"path={_path!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _body=(
            self.body
            if hasattr(self, "body")
            else None
        )
        _new_position=(
            self.new_position
            if hasattr(self, "new_position")
            else None
        )
        _old_position=(
            self.old_position
            if hasattr(self, "old_position")
            else None
        )
        _path=(
            self.path
            if hasattr(self, "path")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"body={_body!s}, "
            f"new_position={_new_position!s}, "
            f"old_position={_old_position!s}, "
            f"path={_path!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
