"""giteaapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from giteaapi.api_helper import APIHelper


class Email(object):
    """Implementation of the 'Email' model.

    Email an email address belonging to a user

    Attributes:
        email (str): The model property of type str.
        primary (bool): Whether this is the primary email address
        user_id (int): The unique identifier of the user who owns this email
        username (str): username of the user
        verified (bool): Whether the email address has been verified
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "email": "email",
        "primary": "primary",
        "user_id": "user_id",
        "username": "username",
        "verified": "verified",
    }

    _optionals = [
        "email",
        "primary",
        "user_id",
        "username",
        "verified",
    ]

    def __init__(
        self,
        email=APIHelper.SKIP,
        primary=APIHelper.SKIP,
        user_id=APIHelper.SKIP,
        username=APIHelper.SKIP,
        verified=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Email instance."""
        # Initialize members of the class
        if email is not APIHelper.SKIP:
            self.email = email
        if primary is not APIHelper.SKIP:
            self.primary = primary
        if user_id is not APIHelper.SKIP:
            self.user_id = user_id
        if username is not APIHelper.SKIP:
            self.username = username
        if verified is not APIHelper.SKIP:
            self.verified = verified

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        email =\
            dictionary.get("email")\
            if dictionary.get("email")\
                else APIHelper.SKIP
        primary =\
            dictionary.get("primary")\
            if "primary" in dictionary.keys()\
                else APIHelper.SKIP
        user_id =\
            dictionary.get("user_id")\
            if dictionary.get("user_id")\
                else APIHelper.SKIP
        username =\
            dictionary.get("username")\
            if dictionary.get("username")\
                else APIHelper.SKIP
        verified =\
            dictionary.get("verified")\
            if "verified" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(email,
                   primary,
                   user_id,
                   username,
                   verified,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _email=(
            self.email
            if hasattr(self, "email")
            else None
        )
        _primary=(
            self.primary
            if hasattr(self, "primary")
            else None
        )
        _user_id=(
            self.user_id
            if hasattr(self, "user_id")
            else None
        )
        _username=(
            self.username
            if hasattr(self, "username")
            else None
        )
        _verified=(
            self.verified
            if hasattr(self, "verified")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"email={_email!r}, "
            f"primary={_primary!r}, "
            f"user_id={_user_id!r}, "
            f"username={_username!r}, "
            f"verified={_verified!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _email=(
            self.email
            if hasattr(self, "email")
            else None
        )
        _primary=(
            self.primary
            if hasattr(self, "primary")
            else None
        )
        _user_id=(
            self.user_id
            if hasattr(self, "user_id")
            else None
        )
        _username=(
            self.username
            if hasattr(self, "username")
            else None
        )
        _verified=(
            self.verified
            if hasattr(self, "verified")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"email={_email!s}, "
            f"primary={_primary!s}, "
            f"user_id={_user_id!s}, "
            f"username={_username!s}, "
            f"verified={_verified!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
