"""giteaapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from giteaapi.api_helper import APIHelper


class GeneralUiSettings(object):
    """Implementation of the 'GeneralUISettings' model.

    GeneralUISettings contains global ui settings exposed by API

    Attributes:
        allowed_reactions (List[str]): AllowedReactions contains the list of allowed
            emoji reactions
        custom_emojis (List[str]): CustomEmojis contains the list of custom emojis
        default_theme (str): DefaultTheme is the default UI theme
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "allowed_reactions": "allowed_reactions",
        "custom_emojis": "custom_emojis",
        "default_theme": "default_theme",
    }

    _optionals = [
        "allowed_reactions",
        "custom_emojis",
        "default_theme",
    ]

    def __init__(
        self,
        allowed_reactions=APIHelper.SKIP,
        custom_emojis=APIHelper.SKIP,
        default_theme=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a GeneralUiSettings instance."""
        # Initialize members of the class
        if allowed_reactions is not APIHelper.SKIP:
            self.allowed_reactions = allowed_reactions
        if custom_emojis is not APIHelper.SKIP:
            self.custom_emojis = custom_emojis
        if default_theme is not APIHelper.SKIP:
            self.default_theme = default_theme

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        allowed_reactions =\
            dictionary.get("allowed_reactions")\
            if dictionary.get("allowed_reactions")\
                else APIHelper.SKIP
        custom_emojis =\
            dictionary.get("custom_emojis")\
            if dictionary.get("custom_emojis")\
                else APIHelper.SKIP
        default_theme =\
            dictionary.get("default_theme")\
            if dictionary.get("default_theme")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(allowed_reactions,
                   custom_emojis,
                   default_theme,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _allowed_reactions=(
            self.allowed_reactions
            if hasattr(self, "allowed_reactions")
            else None
        )
        _custom_emojis=(
            self.custom_emojis
            if hasattr(self, "custom_emojis")
            else None
        )
        _default_theme=(
            self.default_theme
            if hasattr(self, "default_theme")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"allowed_reactions={_allowed_reactions!r}, "
            f"custom_emojis={_custom_emojis!r}, "
            f"default_theme={_default_theme!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _allowed_reactions=(
            self.allowed_reactions
            if hasattr(self, "allowed_reactions")
            else None
        )
        _custom_emojis=(
            self.custom_emojis
            if hasattr(self, "custom_emojis")
            else None
        )
        _default_theme=(
            self.default_theme
            if hasattr(self, "default_theme")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"allowed_reactions={_allowed_reactions!s}, "
            f"custom_emojis={_custom_emojis!s}, "
            f"default_theme={_default_theme!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
