"""giteaapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from giteaapi.api_helper import APIHelper


class GetFilesOptions(object):
    """Implementation of the 'GetFilesOptions' model.

    GetFilesOptions options for retrieving metadate and content of multiple files

    Attributes:
        files (List[str]): Files is the list of file paths to retrieve
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "files": "files",
    }

    _optionals = [
        "files",
    ]

    def __init__(
        self,
        files=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a GetFilesOptions instance."""
        # Initialize members of the class
        if files is not APIHelper.SKIP:
            self.files = files

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        files =\
            dictionary.get("files")\
            if dictionary.get("files")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(files,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _files=(
            self.files
            if hasattr(self, "files")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"files={_files!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _files=(
            self.files
            if hasattr(self, "files")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"files={_files!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
