"""giteaapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from giteaapi.api_helper import APIHelper
from giteaapi.models.git_entry import GitEntry


class GitTreeResponse(object):
    """Implementation of the 'GitTreeResponse' model.

    GitTreeResponse returns a git tree

    Attributes:
        page (int): Page is the current page number for pagination
        sha (str): SHA is the tree object SHA
        total_count (int): TotalCount is the total number of entries in the tree
        tree (List[GitEntry]): Entries contains the tree entries (files and
            directories)
        truncated (bool): Truncated indicates if the response was truncated due to
            size
        url (str): URL is the API URL for this tree
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "page": "page",
        "sha": "sha",
        "total_count": "total_count",
        "tree": "tree",
        "truncated": "truncated",
        "url": "url",
    }

    _optionals = [
        "page",
        "sha",
        "total_count",
        "tree",
        "truncated",
        "url",
    ]

    def __init__(
        self,
        page=APIHelper.SKIP,
        sha=APIHelper.SKIP,
        total_count=APIHelper.SKIP,
        tree=APIHelper.SKIP,
        truncated=APIHelper.SKIP,
        url=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a GitTreeResponse instance."""
        # Initialize members of the class
        if page is not APIHelper.SKIP:
            self.page = page
        if sha is not APIHelper.SKIP:
            self.sha = sha
        if total_count is not APIHelper.SKIP:
            self.total_count = total_count
        if tree is not APIHelper.SKIP:
            self.tree = tree
        if truncated is not APIHelper.SKIP:
            self.truncated = truncated
        if url is not APIHelper.SKIP:
            self.url = url

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        page =\
            dictionary.get("page")\
            if dictionary.get("page")\
                else APIHelper.SKIP
        sha =\
            dictionary.get("sha")\
            if dictionary.get("sha")\
                else APIHelper.SKIP
        total_count =\
            dictionary.get("total_count")\
            if dictionary.get("total_count")\
                else APIHelper.SKIP
        tree = None
        if dictionary.get("tree") is not None:
            tree = [
                GitEntry.from_dictionary(x)
                    for x in dictionary.get("tree")
            ]
        else:
            tree = APIHelper.SKIP
        truncated =\
            dictionary.get("truncated")\
            if "truncated" in dictionary.keys()\
                else APIHelper.SKIP
        url =\
            dictionary.get("url")\
            if dictionary.get("url")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(page,
                   sha,
                   total_count,
                   tree,
                   truncated,
                   url,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _page=(
            self.page
            if hasattr(self, "page")
            else None
        )
        _sha=(
            self.sha
            if hasattr(self, "sha")
            else None
        )
        _total_count=(
            self.total_count
            if hasattr(self, "total_count")
            else None
        )
        _tree=(
            self.tree
            if hasattr(self, "tree")
            else None
        )
        _truncated=(
            self.truncated
            if hasattr(self, "truncated")
            else None
        )
        _url=(
            self.url
            if hasattr(self, "url")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"page={_page!r}, "
            f"sha={_sha!r}, "
            f"total_count={_total_count!r}, "
            f"tree={_tree!r}, "
            f"truncated={_truncated!r}, "
            f"url={_url!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _page=(
            self.page
            if hasattr(self, "page")
            else None
        )
        _sha=(
            self.sha
            if hasattr(self, "sha")
            else None
        )
        _total_count=(
            self.total_count
            if hasattr(self, "total_count")
            else None
        )
        _tree=(
            self.tree
            if hasattr(self, "tree")
            else None
        )
        _truncated=(
            self.truncated
            if hasattr(self, "truncated")
            else None
        )
        _url=(
            self.url
            if hasattr(self, "url")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"page={_page!s}, "
            f"sha={_sha!s}, "
            f"total_count={_total_count!s}, "
            f"tree={_tree!s}, "
            f"truncated={_truncated!s}, "
            f"url={_url!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
