"""giteaapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from giteaapi.api_helper import APIHelper


class InternalTracker(object):
    """Implementation of the 'InternalTracker' model.

    InternalTracker represents settings for internal tracker

    Attributes:
        allow_only_contributors_to_track_time (bool): Let only contributors track
            time (Built-in issue tracker)
        enable_issue_dependencies (bool): Enable dependencies for issues and pull
            requests (Built-in issue tracker)
        enable_time_tracker (bool): Enable time tracking (Built-in issue tracker)
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "allow_only_contributors_to_track_time":
            "allow_only_contributors_to_track_time",
        "enable_issue_dependencies": "enable_issue_dependencies",
        "enable_time_tracker": "enable_time_tracker",
    }

    _optionals = [
        "allow_only_contributors_to_track_time",
        "enable_issue_dependencies",
        "enable_time_tracker",
    ]

    def __init__(
        self,
        allow_only_contributors_to_track_time=APIHelper.SKIP,
        enable_issue_dependencies=APIHelper.SKIP,
        enable_time_tracker=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a InternalTracker instance."""
        # Initialize members of the class
        if allow_only_contributors_to_track_time is not APIHelper.SKIP:
            self.allow_only_contributors_to_track_time =\
                 allow_only_contributors_to_track_time
        if enable_issue_dependencies is not APIHelper.SKIP:
            self.enable_issue_dependencies = enable_issue_dependencies
        if enable_time_tracker is not APIHelper.SKIP:
            self.enable_time_tracker = enable_time_tracker

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        allow_only_contributors_to_track_time =\
            dictionary.get("allow_only_contributors_to_track_time")\
            if "allow_only_contributors_to_track_time" in dictionary.keys()\
                else APIHelper.SKIP
        enable_issue_dependencies =\
            dictionary.get("enable_issue_dependencies")\
            if "enable_issue_dependencies" in dictionary.keys()\
                else APIHelper.SKIP
        enable_time_tracker =\
            dictionary.get("enable_time_tracker")\
            if "enable_time_tracker" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(allow_only_contributors_to_track_time,
                   enable_issue_dependencies,
                   enable_time_tracker,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _allow_only_contributors_to_track_time=(
            self.allow_only_contributors_to_track_time
            if hasattr(self, "allow_only_contributors_to_track_time")
            else None
        )
        _enable_issue_dependencies=(
            self.enable_issue_dependencies
            if hasattr(self, "enable_issue_dependencies")
            else None
        )
        _enable_time_tracker=(
            self.enable_time_tracker
            if hasattr(self, "enable_time_tracker")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"allow_only_contributors_to_track_time={_allow_only_contributors_to_track_time!r}, "
            f"enable_issue_dependencies={_enable_issue_dependencies!r}, "
            f"enable_time_tracker={_enable_time_tracker!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _allow_only_contributors_to_track_time=(
            self.allow_only_contributors_to_track_time
            if hasattr(self, "allow_only_contributors_to_track_time")
            else None
        )
        _enable_issue_dependencies=(
            self.enable_issue_dependencies
            if hasattr(self, "enable_issue_dependencies")
            else None
        )
        _enable_time_tracker=(
            self.enable_time_tracker
            if hasattr(self, "enable_time_tracker")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"allow_only_contributors_to_track_time={_allow_only_contributors_to_track_time!s}, "
            f"enable_issue_dependencies={_enable_issue_dependencies!s}, "
            f"enable_time_tracker={_enable_time_tracker!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
