"""giteaapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from giteaapi.api_helper import APIHelper


class IssueFormField(object):
    """Implementation of the 'IssueFormField' model.

    IssueFormField represents a form field

    Attributes:
        attributes (Dict[str, Any]): The model property of type Dict[str, Any].
        id (str): The model property of type str.
        mtype (Type1): The model property of type Type1.
        validations (Dict[str, Any]): The model property of type Dict[str, Any].
        visible (List[Visible]): The model property of type List[Visible].
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "attributes": "attributes",
        "id": "id",
        "mtype": "type",
        "validations": "validations",
        "visible": "visible",
    }

    _optionals = [
        "attributes",
        "id",
        "mtype",
        "validations",
        "visible",
    ]

    def __init__(
        self,
        attributes=APIHelper.SKIP,
        id=APIHelper.SKIP,
        mtype=APIHelper.SKIP,
        validations=APIHelper.SKIP,
        visible=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a IssueFormField instance."""
        # Initialize members of the class
        if attributes is not APIHelper.SKIP:
            self.attributes = attributes
        if id is not APIHelper.SKIP:
            self.id = id
        if mtype is not APIHelper.SKIP:
            self.mtype = mtype
        if validations is not APIHelper.SKIP:
            self.validations = validations
        if visible is not APIHelper.SKIP:
            self.visible = visible

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        attributes =\
            dictionary.get("attributes")\
            if dictionary.get("attributes")\
                else APIHelper.SKIP
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else APIHelper.SKIP
        mtype =\
            dictionary.get("type")\
            if dictionary.get("type")\
                else APIHelper.SKIP
        validations =\
            dictionary.get("validations")\
            if dictionary.get("validations")\
                else APIHelper.SKIP
        visible =\
            dictionary.get("visible")\
            if dictionary.get("visible")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(attributes,
                   id,
                   mtype,
                   validations,
                   visible,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _attributes=(
            self.attributes
            if hasattr(self, "attributes")
            else None
        )
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _mtype=(
            self.mtype
            if hasattr(self, "mtype")
            else None
        )
        _validations=(
            self.validations
            if hasattr(self, "validations")
            else None
        )
        _visible=(
            self.visible
            if hasattr(self, "visible")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"attributes={_attributes!r}, "
            f"id={_id!r}, "
            f"mtype={_mtype!r}, "
            f"validations={_validations!r}, "
            f"visible={_visible!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _attributes=(
            self.attributes
            if hasattr(self, "attributes")
            else None
        )
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _mtype=(
            self.mtype
            if hasattr(self, "mtype")
            else None
        )
        _validations=(
            self.validations
            if hasattr(self, "validations")
            else None
        )
        _visible=(
            self.visible
            if hasattr(self, "visible")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"attributes={_attributes!s}, "
            f"id={_id!s}, "
            f"mtype={_mtype!s}, "
            f"validations={_validations!s}, "
            f"visible={_visible!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
