"""giteaapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from giteaapi.api_helper import APIHelper


class NewIssuePinsAllowed(object):
    """Implementation of the 'NewIssuePinsAllowed' model.

    NewIssuePinsAllowed represents an API response that says if new Issue Pins are
    allowed

    Attributes:
        issues (bool): The model property of type bool.
        pull_requests (bool): The model property of type bool.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "issues": "issues",
        "pull_requests": "pull_requests",
    }

    _optionals = [
        "issues",
        "pull_requests",
    ]

    def __init__(
        self,
        issues=APIHelper.SKIP,
        pull_requests=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a NewIssuePinsAllowed instance."""
        # Initialize members of the class
        if issues is not APIHelper.SKIP:
            self.issues = issues
        if pull_requests is not APIHelper.SKIP:
            self.pull_requests = pull_requests

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        issues =\
            dictionary.get("issues")\
            if "issues" in dictionary.keys()\
                else APIHelper.SKIP
        pull_requests =\
            dictionary.get("pull_requests")\
            if "pull_requests" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(issues,
                   pull_requests,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _issues=(
            self.issues
            if hasattr(self, "issues")
            else None
        )
        _pull_requests=(
            self.pull_requests
            if hasattr(self, "pull_requests")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"issues={_issues!r}, "
            f"pull_requests={_pull_requests!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _issues=(
            self.issues
            if hasattr(self, "issues")
            else None
        )
        _pull_requests=(
            self.pull_requests
            if hasattr(self, "pull_requests")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"issues={_issues!s}, "
            f"pull_requests={_pull_requests!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
