"""giteaapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class OpType(object):
    """Implementation of the 'OpType' enum.

    the type of action

    Attributes:
        CREATE_REPO: The enum member of type str.
        RENAME_REPO: The enum member of type str.
        STAR_REPO: The enum member of type str.
        WATCH_REPO: The enum member of type str.
        COMMIT_REPO: The enum member of type str.
        CREATE_ISSUE: The enum member of type str.
        CREATE_PULL_REQUEST: The enum member of type str.
        TRANSFER_REPO: The enum member of type str.
        PUSH_TAG: The enum member of type str.
        COMMENT_ISSUE: The enum member of type str.
        MERGE_PULL_REQUEST: The enum member of type str.
        CLOSE_ISSUE: The enum member of type str.
        REOPEN_ISSUE: The enum member of type str.
        CLOSE_PULL_REQUEST: The enum member of type str.
        REOPEN_PULL_REQUEST: The enum member of type str.
        DELETE_TAG: The enum member of type str.
        DELETE_BRANCH: The enum member of type str.
        MIRROR_SYNC_PUSH: The enum member of type str.
        MIRROR_SYNC_CREATE: The enum member of type str.
        MIRROR_SYNC_DELETE: The enum member of type str.
        APPROVE_PULL_REQUEST: The enum member of type str.
        REJECT_PULL_REQUEST: The enum member of type str.
        COMMENT_PULL: The enum member of type str.
        PUBLISH_RELEASE: The enum member of type str.
        PULL_REVIEW_DISMISSED: The enum member of type str.
        PULL_REQUEST_READY_FOR_REVIEW: The enum member of type str.
        AUTO_MERGE_PULL_REQUEST: The enum member of type str.

    """

    CREATE_REPO = "create_repo"

    RENAME_REPO = "rename_repo"

    STAR_REPO = "star_repo"

    WATCH_REPO = "watch_repo"

    COMMIT_REPO = "commit_repo"

    CREATE_ISSUE = "create_issue"

    CREATE_PULL_REQUEST = "create_pull_request"

    TRANSFER_REPO = "transfer_repo"

    PUSH_TAG = "push_tag"

    COMMENT_ISSUE = "comment_issue"

    MERGE_PULL_REQUEST = "merge_pull_request"

    CLOSE_ISSUE = "close_issue"

    REOPEN_ISSUE = "reopen_issue"

    CLOSE_PULL_REQUEST = "close_pull_request"

    REOPEN_PULL_REQUEST = "reopen_pull_request"

    DELETE_TAG = "delete_tag"

    DELETE_BRANCH = "delete_branch"

    MIRROR_SYNC_PUSH = "mirror_sync_push"

    MIRROR_SYNC_CREATE = "mirror_sync_create"

    MIRROR_SYNC_DELETE = "mirror_sync_delete"

    APPROVE_PULL_REQUEST = "approve_pull_request"

    REJECT_PULL_REQUEST = "reject_pull_request"

    COMMENT_PULL = "comment_pull"

    PUBLISH_RELEASE = "publish_release"

    PULL_REVIEW_DISMISSED = "pull_review_dismissed"

    PULL_REQUEST_READY_FOR_REVIEW = "pull_request_ready_for_review"

    AUTO_MERGE_PULL_REQUEST = "auto_merge_pull_request"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
