"""giteaapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from giteaapi.api_helper import APIHelper


class OrganizationPermissions(object):
    """Implementation of the 'OrganizationPermissions' model.

    OrganizationPermissions list different users permissions on an organization

    Attributes:
        can_create_repository (bool): Whether the user can create repositories in the
            organization
        can_read (bool): Whether the user can read the organization
        can_write (bool): Whether the user can write to the organization
        is_admin (bool): Whether the user is an admin of the organization
        is_owner (bool): Whether the user is an owner of the organization
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "can_create_repository": "can_create_repository",
        "can_read": "can_read",
        "can_write": "can_write",
        "is_admin": "is_admin",
        "is_owner": "is_owner",
    }

    _optionals = [
        "can_create_repository",
        "can_read",
        "can_write",
        "is_admin",
        "is_owner",
    ]

    def __init__(
        self,
        can_create_repository=APIHelper.SKIP,
        can_read=APIHelper.SKIP,
        can_write=APIHelper.SKIP,
        is_admin=APIHelper.SKIP,
        is_owner=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a OrganizationPermissions instance."""
        # Initialize members of the class
        if can_create_repository is not APIHelper.SKIP:
            self.can_create_repository = can_create_repository
        if can_read is not APIHelper.SKIP:
            self.can_read = can_read
        if can_write is not APIHelper.SKIP:
            self.can_write = can_write
        if is_admin is not APIHelper.SKIP:
            self.is_admin = is_admin
        if is_owner is not APIHelper.SKIP:
            self.is_owner = is_owner

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        can_create_repository =\
            dictionary.get("can_create_repository")\
            if "can_create_repository" in dictionary.keys()\
                else APIHelper.SKIP
        can_read =\
            dictionary.get("can_read")\
            if "can_read" in dictionary.keys()\
                else APIHelper.SKIP
        can_write =\
            dictionary.get("can_write")\
            if "can_write" in dictionary.keys()\
                else APIHelper.SKIP
        is_admin =\
            dictionary.get("is_admin")\
            if "is_admin" in dictionary.keys()\
                else APIHelper.SKIP
        is_owner =\
            dictionary.get("is_owner")\
            if "is_owner" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(can_create_repository,
                   can_read,
                   can_write,
                   is_admin,
                   is_owner,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _can_create_repository=(
            self.can_create_repository
            if hasattr(self, "can_create_repository")
            else None
        )
        _can_read=(
            self.can_read
            if hasattr(self, "can_read")
            else None
        )
        _can_write=(
            self.can_write
            if hasattr(self, "can_write")
            else None
        )
        _is_admin=(
            self.is_admin
            if hasattr(self, "is_admin")
            else None
        )
        _is_owner=(
            self.is_owner
            if hasattr(self, "is_owner")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"can_create_repository={_can_create_repository!r}, "
            f"can_read={_can_read!r}, "
            f"can_write={_can_write!r}, "
            f"is_admin={_is_admin!r}, "
            f"is_owner={_is_owner!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _can_create_repository=(
            self.can_create_repository
            if hasattr(self, "can_create_repository")
            else None
        )
        _can_read=(
            self.can_read
            if hasattr(self, "can_read")
            else None
        )
        _can_write=(
            self.can_write
            if hasattr(self, "can_write")
            else None
        )
        _is_admin=(
            self.is_admin
            if hasattr(self, "is_admin")
            else None
        )
        _is_owner=(
            self.is_owner
            if hasattr(self, "is_owner")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"can_create_repository={_can_create_repository!s}, "
            f"can_read={_can_read!s}, "
            f"can_write={_can_write!s}, "
            f"is_admin={_is_admin!s}, "
            f"is_owner={_is_owner!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
