"""giteaapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from giteaapi.api_helper import APIHelper
from giteaapi.models.repository import Repository
from giteaapi.models.user import User


class Package(object):
    """Implementation of the 'Package' model.

    Package represents a package

    Attributes:
        created_at (datetime): The model property of type datetime.
        creator (User): User represents a user
        html_url (str): The HTML URL to view the package
        id (int): The unique identifier of the package
        name (str): The name of the package
        owner (User): User represents a user
        repository (Repository): Repository represents a repository
        mtype (str): The type of the package (e.g., npm, maven, docker)
        version (str): The version of the package
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "created_at": "created_at",
        "creator": "creator",
        "html_url": "html_url",
        "id": "id",
        "name": "name",
        "owner": "owner",
        "repository": "repository",
        "mtype": "type",
        "version": "version",
    }

    _optionals = [
        "created_at",
        "creator",
        "html_url",
        "id",
        "name",
        "owner",
        "repository",
        "mtype",
        "version",
    ]

    def __init__(
        self,
        created_at=APIHelper.SKIP,
        creator=APIHelper.SKIP,
        html_url=APIHelper.SKIP,
        id=APIHelper.SKIP,
        name=APIHelper.SKIP,
        owner=APIHelper.SKIP,
        repository=APIHelper.SKIP,
        mtype=APIHelper.SKIP,
        version=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Package instance."""
        # Initialize members of the class
        if created_at is not APIHelper.SKIP:
            self.created_at =\
                 APIHelper.apply_datetime_converter(
                created_at, APIHelper.RFC3339DateTime)\
                 if created_at else None
        if creator is not APIHelper.SKIP:
            self.creator = creator
        if html_url is not APIHelper.SKIP:
            self.html_url = html_url
        if id is not APIHelper.SKIP:
            self.id = id
        if name is not APIHelper.SKIP:
            self.name = name
        if owner is not APIHelper.SKIP:
            self.owner = owner
        if repository is not APIHelper.SKIP:
            self.repository = repository
        if mtype is not APIHelper.SKIP:
            self.mtype = mtype
        if version is not APIHelper.SKIP:
            self.version = version

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        created_at = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("created_at")).datetime\
            if dictionary.get("created_at") else APIHelper.SKIP
        creator =\
            User.from_dictionary(
                dictionary.get("creator"))\
                if "creator" in dictionary.keys()\
                else APIHelper.SKIP
        html_url =\
            dictionary.get("html_url")\
            if dictionary.get("html_url")\
                else APIHelper.SKIP
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else APIHelper.SKIP
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else APIHelper.SKIP
        owner =\
            User.from_dictionary(
                dictionary.get("owner"))\
                if "owner" in dictionary.keys()\
                else APIHelper.SKIP
        repository =\
            Repository.from_dictionary(
                dictionary.get("repository"))\
                if "repository" in dictionary.keys()\
                else APIHelper.SKIP
        mtype =\
            dictionary.get("type")\
            if dictionary.get("type")\
                else APIHelper.SKIP
        version =\
            dictionary.get("version")\
            if dictionary.get("version")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(created_at,
                   creator,
                   html_url,
                   id,
                   name,
                   owner,
                   repository,
                   mtype,
                   version,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _created_at=(
            self.created_at
            if hasattr(self, "created_at")
            else None
        )
        _creator=(
            self.creator
            if hasattr(self, "creator")
            else None
        )
        _html_url=(
            self.html_url
            if hasattr(self, "html_url")
            else None
        )
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _owner=(
            self.owner
            if hasattr(self, "owner")
            else None
        )
        _repository=(
            self.repository
            if hasattr(self, "repository")
            else None
        )
        _mtype=(
            self.mtype
            if hasattr(self, "mtype")
            else None
        )
        _version=(
            self.version
            if hasattr(self, "version")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"created_at={_created_at!r}, "
            f"creator={_creator!r}, "
            f"html_url={_html_url!r}, "
            f"id={_id!r}, "
            f"name={_name!r}, "
            f"owner={_owner!r}, "
            f"repository={_repository!r}, "
            f"mtype={_mtype!r}, "
            f"version={_version!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _created_at=(
            self.created_at
            if hasattr(self, "created_at")
            else None
        )
        _creator=(
            self.creator
            if hasattr(self, "creator")
            else None
        )
        _html_url=(
            self.html_url
            if hasattr(self, "html_url")
            else None
        )
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _owner=(
            self.owner
            if hasattr(self, "owner")
            else None
        )
        _repository=(
            self.repository
            if hasattr(self, "repository")
            else None
        )
        _mtype=(
            self.mtype
            if hasattr(self, "mtype")
            else None
        )
        _version=(
            self.version
            if hasattr(self, "version")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"created_at={_created_at!s}, "
            f"creator={_creator!s}, "
            f"html_url={_html_url!s}, "
            f"id={_id!s}, "
            f"name={_name!s}, "
            f"owner={_owner!s}, "
            f"repository={_repository!s}, "
            f"mtype={_mtype!s}, "
            f"version={_version!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
