"""giteaapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from giteaapi.api_helper import APIHelper


class RepositoryMeta(object):
    """Implementation of the 'RepositoryMeta' model.

    RepositoryMeta basic repository information

    Attributes:
        full_name (str): The model property of type str.
        id (int): The model property of type int.
        name (str): The model property of type str.
        owner (str): The model property of type str.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "full_name": "full_name",
        "id": "id",
        "name": "name",
        "owner": "owner",
    }

    _optionals = [
        "full_name",
        "id",
        "name",
        "owner",
    ]

    def __init__(
        self,
        full_name=APIHelper.SKIP,
        id=APIHelper.SKIP,
        name=APIHelper.SKIP,
        owner=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a RepositoryMeta instance."""
        # Initialize members of the class
        if full_name is not APIHelper.SKIP:
            self.full_name = full_name
        if id is not APIHelper.SKIP:
            self.id = id
        if name is not APIHelper.SKIP:
            self.name = name
        if owner is not APIHelper.SKIP:
            self.owner = owner

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        full_name =\
            dictionary.get("full_name")\
            if dictionary.get("full_name")\
                else APIHelper.SKIP
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else APIHelper.SKIP
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else APIHelper.SKIP
        owner =\
            dictionary.get("owner")\
            if dictionary.get("owner")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(full_name,
                   id,
                   name,
                   owner,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _full_name=(
            self.full_name
            if hasattr(self, "full_name")
            else None
        )
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _owner=(
            self.owner
            if hasattr(self, "owner")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"full_name={_full_name!r}, "
            f"id={_id!r}, "
            f"name={_name!r}, "
            f"owner={_owner!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _full_name=(
            self.full_name
            if hasattr(self, "full_name")
            else None
        )
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _owner=(
            self.owner
            if hasattr(self, "owner")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"full_name={_full_name!s}, "
            f"id={_id!s}, "
            f"name={_name!s}, "
            f"owner={_owner!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
