"""giteaapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from giteaapi.api_helper import APIHelper


class RunDetails(object):
    """Implementation of the 'RunDetails' model.

    RunDetails returns workflow_dispatch runid and url

    Attributes:
        html_url (str): The model property of type str.
        run_url (str): The model property of type str.
        workflow_run_id (int): The model property of type int.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "html_url": "html_url",
        "run_url": "run_url",
        "workflow_run_id": "workflow_run_id",
    }

    _optionals = [
        "html_url",
        "run_url",
        "workflow_run_id",
    ]

    def __init__(
        self,
        html_url=APIHelper.SKIP,
        run_url=APIHelper.SKIP,
        workflow_run_id=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a RunDetails instance."""
        # Initialize members of the class
        if html_url is not APIHelper.SKIP:
            self.html_url = html_url
        if run_url is not APIHelper.SKIP:
            self.run_url = run_url
        if workflow_run_id is not APIHelper.SKIP:
            self.workflow_run_id = workflow_run_id

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        html_url =\
            dictionary.get("html_url")\
            if dictionary.get("html_url")\
                else APIHelper.SKIP
        run_url =\
            dictionary.get("run_url")\
            if dictionary.get("run_url")\
                else APIHelper.SKIP
        workflow_run_id =\
            dictionary.get("workflow_run_id")\
            if dictionary.get("workflow_run_id")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(html_url,
                   run_url,
                   workflow_run_id,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _html_url=(
            self.html_url
            if hasattr(self, "html_url")
            else None
        )
        _run_url=(
            self.run_url
            if hasattr(self, "run_url")
            else None
        )
        _workflow_run_id=(
            self.workflow_run_id
            if hasattr(self, "workflow_run_id")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"html_url={_html_url!r}, "
            f"run_url={_run_url!r}, "
            f"workflow_run_id={_workflow_run_id!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _html_url=(
            self.html_url
            if hasattr(self, "html_url")
            else None
        )
        _run_url=(
            self.run_url
            if hasattr(self, "run_url")
            else None
        )
        _workflow_run_id=(
            self.workflow_run_id
            if hasattr(self, "workflow_run_id")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"html_url={_html_url!s}, "
            f"run_url={_run_url!s}, "
            f"workflow_run_id={_workflow_run_id!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
