"""giteaapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class State6(object):
    """Implementation of the 'State6' enum.

    State indicates the current state of the notification subject
    open NotifySubjectStateOpen is an open subject
    closed NotifySubjectStateClosed is a closed subject
    merged NotifySubjectStateMerged is a merged pull request

    Attributes:
        OPEN: The enum member of type str.
        CLOSED: The enum member of type str.
        MERGED: The enum member of type str.

    """

    OPEN = "open"

    CLOSED = "closed"

    MERGED = "merged"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
