"""giteaapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from giteaapi.api_helper import APIHelper


class StopWatch(object):
    """Implementation of the 'StopWatch' model.

    StopWatch represent a running stopwatch

    Attributes:
        created (datetime): The model property of type datetime.
        duration (str): Duration is a human-readable duration string
        issue_index (int): IssueIndex is the index number of the associated issue
        issue_title (str): IssueTitle is the title of the associated issue
        repo_name (str): RepoName is the name of the repository
        repo_owner_name (str): RepoOwnerName is the name of the repository owner
        seconds (int): Seconds is the total elapsed time in seconds
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "created": "created",
        "duration": "duration",
        "issue_index": "issue_index",
        "issue_title": "issue_title",
        "repo_name": "repo_name",
        "repo_owner_name": "repo_owner_name",
        "seconds": "seconds",
    }

    _optionals = [
        "created",
        "duration",
        "issue_index",
        "issue_title",
        "repo_name",
        "repo_owner_name",
        "seconds",
    ]

    def __init__(
        self,
        created=APIHelper.SKIP,
        duration=APIHelper.SKIP,
        issue_index=APIHelper.SKIP,
        issue_title=APIHelper.SKIP,
        repo_name=APIHelper.SKIP,
        repo_owner_name=APIHelper.SKIP,
        seconds=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a StopWatch instance."""
        # Initialize members of the class
        if created is not APIHelper.SKIP:
            self.created =\
                 APIHelper.apply_datetime_converter(
                created, APIHelper.RFC3339DateTime)\
                 if created else None
        if duration is not APIHelper.SKIP:
            self.duration = duration
        if issue_index is not APIHelper.SKIP:
            self.issue_index = issue_index
        if issue_title is not APIHelper.SKIP:
            self.issue_title = issue_title
        if repo_name is not APIHelper.SKIP:
            self.repo_name = repo_name
        if repo_owner_name is not APIHelper.SKIP:
            self.repo_owner_name = repo_owner_name
        if seconds is not APIHelper.SKIP:
            self.seconds = seconds

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        created = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("created")).datetime\
            if dictionary.get("created") else APIHelper.SKIP
        duration =\
            dictionary.get("duration")\
            if dictionary.get("duration")\
                else APIHelper.SKIP
        issue_index =\
            dictionary.get("issue_index")\
            if dictionary.get("issue_index")\
                else APIHelper.SKIP
        issue_title =\
            dictionary.get("issue_title")\
            if dictionary.get("issue_title")\
                else APIHelper.SKIP
        repo_name =\
            dictionary.get("repo_name")\
            if dictionary.get("repo_name")\
                else APIHelper.SKIP
        repo_owner_name =\
            dictionary.get("repo_owner_name")\
            if dictionary.get("repo_owner_name")\
                else APIHelper.SKIP
        seconds =\
            dictionary.get("seconds")\
            if dictionary.get("seconds")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(created,
                   duration,
                   issue_index,
                   issue_title,
                   repo_name,
                   repo_owner_name,
                   seconds,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _created=(
            self.created
            if hasattr(self, "created")
            else None
        )
        _duration=(
            self.duration
            if hasattr(self, "duration")
            else None
        )
        _issue_index=(
            self.issue_index
            if hasattr(self, "issue_index")
            else None
        )
        _issue_title=(
            self.issue_title
            if hasattr(self, "issue_title")
            else None
        )
        _repo_name=(
            self.repo_name
            if hasattr(self, "repo_name")
            else None
        )
        _repo_owner_name=(
            self.repo_owner_name
            if hasattr(self, "repo_owner_name")
            else None
        )
        _seconds=(
            self.seconds
            if hasattr(self, "seconds")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"created={_created!r}, "
            f"duration={_duration!r}, "
            f"issue_index={_issue_index!r}, "
            f"issue_title={_issue_title!r}, "
            f"repo_name={_repo_name!r}, "
            f"repo_owner_name={_repo_owner_name!r}, "
            f"seconds={_seconds!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _created=(
            self.created
            if hasattr(self, "created")
            else None
        )
        _duration=(
            self.duration
            if hasattr(self, "duration")
            else None
        )
        _issue_index=(
            self.issue_index
            if hasattr(self, "issue_index")
            else None
        )
        _issue_title=(
            self.issue_title
            if hasattr(self, "issue_title")
            else None
        )
        _repo_name=(
            self.repo_name
            if hasattr(self, "repo_name")
            else None
        )
        _repo_owner_name=(
            self.repo_owner_name
            if hasattr(self, "repo_owner_name")
            else None
        )
        _seconds=(
            self.seconds
            if hasattr(self, "seconds")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"created={_created!s}, "
            f"duration={_duration!s}, "
            f"issue_index={_issue_index!s}, "
            f"issue_title={_issue_title!s}, "
            f"repo_name={_repo_name!s}, "
            f"repo_owner_name={_repo_owner_name!s}, "
            f"seconds={_seconds!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
