"""giteaapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from giteaapi.api_helper import APIHelper


class SubmitPullReviewOptions(object):
    """Implementation of the 'SubmitPullReviewOptions' model.

    SubmitPullReviewOptions are options to submit a pending pull request review

    Attributes:
        body (str): The model property of type str.
        event (Event): The model property of type Event.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "body": "body",
        "event": "event",
    }

    _optionals = [
        "body",
        "event",
    ]

    def __init__(
        self,
        body=APIHelper.SKIP,
        event=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a SubmitPullReviewOptions instance."""
        # Initialize members of the class
        if body is not APIHelper.SKIP:
            self.body = body
        if event is not APIHelper.SKIP:
            self.event = event

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        body =\
            dictionary.get("body")\
            if dictionary.get("body")\
                else APIHelper.SKIP
        event =\
            dictionary.get("event")\
            if dictionary.get("event")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(body,
                   event,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _body=(
            self.body
            if hasattr(self, "body")
            else None
        )
        _event=(
            self.event
            if hasattr(self, "event")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"body={_body!r}, "
            f"event={_event!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _body=(
            self.body
            if hasattr(self, "body")
            else None
        )
        _event=(
            self.event
            if hasattr(self, "event")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"body={_body!s}, "
            f"event={_event!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
