"""giteaapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from giteaapi.api_helper import APIHelper


class WatchInfo(object):
    """Implementation of the 'WatchInfo' model.

    WatchInfo represents an API watch status of one repository

    Attributes:
        created_at (datetime): The timestamp when the watch status was created
        ignored (bool): Whether notifications for the repository are ignored
        reason (Any): The reason for the current watch status
        repository_url (str): The URL of the repository being watched
        subscribed (bool): Whether the repository is being watched for notifications
        url (str): The URL for managing the watch status
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "created_at": "created_at",
        "ignored": "ignored",
        "reason": "reason",
        "repository_url": "repository_url",
        "subscribed": "subscribed",
        "url": "url",
    }

    _optionals = [
        "created_at",
        "ignored",
        "reason",
        "repository_url",
        "subscribed",
        "url",
    ]

    def __init__(
        self,
        created_at=APIHelper.SKIP,
        ignored=APIHelper.SKIP,
        reason=APIHelper.SKIP,
        repository_url=APIHelper.SKIP,
        subscribed=APIHelper.SKIP,
        url=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a WatchInfo instance."""
        # Initialize members of the class
        if created_at is not APIHelper.SKIP:
            self.created_at =\
                 APIHelper.apply_datetime_converter(
                created_at, APIHelper.RFC3339DateTime)\
                 if created_at else None
        if ignored is not APIHelper.SKIP:
            self.ignored = ignored
        if reason is not APIHelper.SKIP:
            self.reason = reason
        if repository_url is not APIHelper.SKIP:
            self.repository_url = repository_url
        if subscribed is not APIHelper.SKIP:
            self.subscribed = subscribed
        if url is not APIHelper.SKIP:
            self.url = url

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        created_at = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("created_at")).datetime\
            if dictionary.get("created_at") else APIHelper.SKIP
        ignored =\
            dictionary.get("ignored")\
            if "ignored" in dictionary.keys()\
                else APIHelper.SKIP
        reason =\
            dictionary.get("reason")\
            if dictionary.get("reason")\
                else APIHelper.SKIP
        repository_url =\
            dictionary.get("repository_url")\
            if dictionary.get("repository_url")\
                else APIHelper.SKIP
        subscribed =\
            dictionary.get("subscribed")\
            if "subscribed" in dictionary.keys()\
                else APIHelper.SKIP
        url =\
            dictionary.get("url")\
            if dictionary.get("url")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(created_at,
                   ignored,
                   reason,
                   repository_url,
                   subscribed,
                   url,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _created_at=(
            self.created_at
            if hasattr(self, "created_at")
            else None
        )
        _ignored=(
            self.ignored
            if hasattr(self, "ignored")
            else None
        )
        _reason=(
            self.reason
            if hasattr(self, "reason")
            else None
        )
        _repository_url=(
            self.repository_url
            if hasattr(self, "repository_url")
            else None
        )
        _subscribed=(
            self.subscribed
            if hasattr(self, "subscribed")
            else None
        )
        _url=(
            self.url
            if hasattr(self, "url")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"created_at={_created_at!r}, "
            f"ignored={_ignored!r}, "
            f"reason={_reason!r}, "
            f"repository_url={_repository_url!r}, "
            f"subscribed={_subscribed!r}, "
            f"url={_url!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _created_at=(
            self.created_at
            if hasattr(self, "created_at")
            else None
        )
        _ignored=(
            self.ignored
            if hasattr(self, "ignored")
            else None
        )
        _reason=(
            self.reason
            if hasattr(self, "reason")
            else None
        )
        _repository_url=(
            self.repository_url
            if hasattr(self, "repository_url")
            else None
        )
        _subscribed=(
            self.subscribed
            if hasattr(self, "subscribed")
            else None
        )
        _url=(
            self.url
            if hasattr(self, "url")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"created_at={_created_at!s}, "
            f"ignored={_ignored!s}, "
            f"reason={_reason!s}, "
            f"repository_url={_repository_url!s}, "
            f"subscribed={_subscribed!s}, "
            f"url={_url!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
