
"""
giteaapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import os

from apimatic_core.authentication.header_auth import HeaderAuth


class SudoHeader(HeaderAuth):
    """
    An authentication handler that applies `CustomHeaderAuthentication` to
    outgoing requests. It constructs the required credential values and integrates
    with the core authentication framework.
    """

    @property
    def error_message(self):
        """Return reason about the authentication failure."""
        return "SudoHeader: sudo is undefined."

    def __init__(self, auth_model):
        """
        Initialize the authentication handler with credential data.

        Args:
            auth_model: The credentials object used to generate the authorization
             header.

        """
        auth_params = {}
        if auth_model is not None \
                and auth_model.sudo is not None:
            auth_params["Sudo"] = auth_model.sudo
        super().__init__(auth_params=auth_params)


class SudoHeaderCredentials:
    """
    A model for authentication credentials. Provides simple validation,
    cloning support, and optional construction from environment variables.
    Suitable as a pattern for other auth models.
    """

    @property
    def sudo(self):
        """
        Sudo API request as the user provided as the key. Admin privileges are
        required.
        """
        return self._sudo

    def __init__(self, sudo):
        """
        Initialize the credentials.

        Args:
            sudo: The sudo property value to set.

        Raises:
            ValueError: If any required value is missing.

        """
        if sudo is None:
            raise ValueError("sudo cannot be None")
        self._sudo = sudo

    def clone_with(self, sudo=None):
        """
        Return a new instance with optional value overrides.

        Args:
            sudo: The sudo property value to set.

        """
        return SudoHeaderCredentials(sudo or self.sudo)

    @classmethod
    def from_environment(cls):
        """
        Create credentials from environment variables, if available.

        Returns:
            A credentials instance or ``None`` if values are missing.

        """
        sudo = os.getenv(
            "SUDO_HEADER_SUDO",
            None,
        )

        if (sudo is None):
            return None

        return cls(
            sudo=sudo,
        )
