
"""
giteaapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import os

from apimatic_core.authentication.query_auth import QueryAuth


class Token(QueryAuth):
    """
    An authentication handler that applies `CustomQueryAuthentication` to
    outgoing requests. It constructs the required credential values and integrates
    with the core authentication framework.
    """

    @property
    def error_message(self):
        """Return reason about the authentication failure."""
        return "Token: token is undefined."

    def __init__(self, auth_model):
        """
        Initialize the authentication handler with credential data.

        Args:
            auth_model: The credentials object used to generate the authorization
             header.

        """
        auth_params = {}
        if auth_model is not None \
                and auth_model.token is not None:
            auth_params["token"] = auth_model.token
        super().__init__(auth_params=auth_params)


class TokenCredentials:
    """
    A model for authentication credentials. Provides simple validation,
    cloning support, and optional construction from environment variables.
    Suitable as a pattern for other auth models.
    """

    @property
    def token(self):
        """
        This authentication option is deprecated for removal in Gitea 1.23. Please use
        AuthorizationHeaderToken instead.
        """
        return self._token

    def __init__(self, token):
        """
        Initialize the credentials.

        Args:
            token: The token property value to set.

        Raises:
            ValueError: If any required value is missing.

        """
        if token is None:
            raise ValueError("token cannot be None")
        self._token = token

    def clone_with(self, token=None):
        """
        Return a new instance with optional value overrides.

        Args:
            token: The token property value to set.

        """
        return TokenCredentials(token or self.token)

    @classmethod
    def from_environment(cls):
        """
        Create credentials from environment variables, if available.

        Returns:
            A credentials instance or ``None`` if values are missing.

        """
        token = os.getenv(
            "TOKEN_TOKEN",
            None,
        )

        if (token is None):
            return None

        return cls(
            token=token,
        )
