"""giteaapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: D410, E501, E101, D206
from apimatic_core.authentication.multiple.or_auth_group import (
    Or,
)
from apimatic_core.authentication.multiple.single_auth import (
    Single,
)
from apimatic_core.request_builder import RequestBuilder
from apimatic_core.response_handler import ResponseHandler
from apimatic_core.types.parameter import Parameter

from giteaapi.api_helper import APIHelper
from giteaapi.apis.base_api import BaseApi
from giteaapi.configuration import Server
from giteaapi.exceptions.api_exception import (
    ApiException,
)
from giteaapi.http.http_method_enum import HttpMethodEnum
from giteaapi.models.notification_count import (
    NotificationCount,
)
from giteaapi.models.notification_thread import (
    NotificationThread,
)


class NotificationApi(BaseApi):
    """A Controller to access Endpoints in the giteaapi API."""

    def __init__(self, config):
        """Initialize NotificationApi object."""
        super(NotificationApi, self).__init__(config)

    def notify_get_list(self,
                        all=None,
                        status_types=None,
                        subject_type=None,
                        since=None,
                        before=None,
                        page=None,
                        limit=None):
        """Perform a GET request to /notifications.

        List users's notification threads

        Args:
            all (bool, optional): If true, show notifications marked as read. Default
                value is false
            status_types (List[str], optional): Show notifications with the provided
                status types. Options are: unread, read and/or pinned. Defaults to
                unread & pinned.
            subject_type (List[SubjectType], optional): filter notifications by
                subject type
            since (datetime, optional): Only show notifications updated after the
                given time. This is a timestamp in RFC 3339 format
            before (datetime, optional): Only show notifications updated before the
                given time. This is a timestamp in RFC 3339 format
            page (int, optional): page number of results to return (1-based)
            limit (int, optional): page size of results

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. NotificationThreadList

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.SERVER1)
            .path("/notifications")
            .http_method(HttpMethodEnum.GET)
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/json"))
            .query_param(Parameter()
                .key("all")
                .value(all))
            .query_param(Parameter()
                .key("status-types")
                .value(status_types))
            .query_param(Parameter()
                .key("subject-type")
                .value(subject_type))
            .query_param(Parameter()
                .key("since")
                .value(APIHelper.when_defined(APIHelper.RFC3339DateTime,
                    since)))
            .query_param(Parameter()
                .key("before")
                .value(APIHelper.when_defined(APIHelper.RFC3339DateTime,
                    before)))
            .query_param(Parameter()
                .key("page")
                .value(page))
            .query_param(Parameter()
                .key("limit")
                .value(limit))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Or(Single("BasicAuth"), Single("Token"),
                Single("AccessToken"), Single("AuthorizationHeaderToken"),
                Single("SudoParam"), Single("SudoHeader"), Single("TOTPHeader"))),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(NotificationThread.from_dictionary)
            .is_api_response(True),
        ).execute()

    def notify_read_list(self,
                         last_read_at=None,
                         all=None,
                         status_types=None,
                         to_status=None):
        """Perform a PUT request to /notifications.

        Mark notification threads as read, pinned or unread

        Args:
            last_read_at (datetime, optional): Describes the last point that
                notifications were checked. Anything updated since this time will not
                be updated.
            all (str, optional): If true, mark all notifications on this repo.
                Default value is false
            status_types (List[str], optional): Mark notifications with the provided
                status types. Options are: unread, read and/or pinned. Defaults to
                unread.
            to_status (str, optional): Status to mark notifications as, Defaults to
                read.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. NotificationThreadList

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.SERVER1)
            .path("/notifications")
            .http_method(HttpMethodEnum.PUT)
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/json"))
            .query_param(Parameter()
                .key("last_read_at")
                .value(APIHelper.when_defined(APIHelper.RFC3339DateTime,
                    last_read_at)))
            .query_param(Parameter()
                .key("all")
                .value(all))
            .query_param(Parameter()
                .key("status-types")
                .value(status_types))
            .query_param(Parameter()
                .key("to-status")
                .value(to_status))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Or(Single("BasicAuth"), Single("Token"),
                Single("AccessToken"), Single("AuthorizationHeaderToken"),
                Single("SudoParam"), Single("SudoHeader"), Single("TOTPHeader"))),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(NotificationThread.from_dictionary)
            .is_api_response(True),
        ).execute()

    def notify_new_available(self):
        """Perform a GET request to /notifications/new.

        Check if unread notifications exist

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Number of unread
                notifications

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.SERVER1)
            .path("/notifications/new")
            .http_method(HttpMethodEnum.GET)
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Or(Single("BasicAuth"), Single("Token"),
                Single("AccessToken"), Single("AuthorizationHeaderToken"),
                Single("SudoParam"), Single("SudoHeader"), Single("TOTPHeader"))),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(NotificationCount.from_dictionary)
            .is_api_response(True),
        ).execute()

    def notify_get_thread(self,
                          id):
        """Perform a GET request to /notifications/threads/{id}.

        Get notification thread by ID

        Args:
            id (str): id of notification thread

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. NotificationThread

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.SERVER1)
            .path("/notifications/threads/{id}")
            .http_method(HttpMethodEnum.GET)
            .template_param(Parameter()
                .key("id")
                .value(id)
                .is_required(True)
                .should_encode(True))
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/json"))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Or(Single("BasicAuth"), Single("Token"),
                Single("AccessToken"), Single("AuthorizationHeaderToken"),
                Single("SudoParam"), Single("SudoHeader"), Single("TOTPHeader"))),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(NotificationThread.from_dictionary)
            .is_api_response(True)
            .local_error("403",
                "APIForbiddenError is a forbidden error response",
                ApiException)
            .local_error("404",
                "APINotFound is a not found empty response",
                ApiException),
        ).execute()

    def notify_read_thread(self,
                           id,
                           to_status="read"):
        """Perform a PATCH request to /notifications/threads/{id}.

        Mark notification thread as read by ID

        Args:
            id (str): id of notification thread
            to_status (str, optional): Status to mark notifications as

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. NotificationThread

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.SERVER1)
            .path("/notifications/threads/{id}")
            .http_method(HttpMethodEnum.PATCH)
            .template_param(Parameter()
                .key("id")
                .value(id)
                .is_required(True)
                .should_encode(True))
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/json"))
            .query_param(Parameter()
                .key("to-status")
                .value(to_status))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Or(Single("BasicAuth"), Single("Token"),
                Single("AccessToken"), Single("AuthorizationHeaderToken"),
                Single("SudoParam"), Single("SudoHeader"), Single("TOTPHeader"))),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(NotificationThread.from_dictionary)
            .is_api_response(True)
            .local_error("403",
                "APIForbiddenError is a forbidden error response",
                ApiException)
            .local_error("404",
                "APINotFound is a not found empty response",
                ApiException),
        ).execute()

    def notify_get_repo_list(self,
                             owner,
                             repo,
                             all=None,
                             status_types=None,
                             subject_type=None,
                             since=None,
                             before=None,
                             page=None,
                             limit=None):
        """Perform a GET request to /repos/{owner}/{repo}/notifications.

        List users's notification threads on a specific repo

        Args:
            owner (str): owner of the repo
            repo (str): name of the repo
            all (bool, optional): If true, show notifications marked as read. Default
                value is false
            status_types (List[str], optional): Show notifications with the provided
                status types. Options are: unread, read and/or pinned. Defaults to
                unread & pinned
            subject_type (List[SubjectType], optional): filter notifications by
                subject type
            since (datetime, optional): Only show notifications updated after the
                given time. This is a timestamp in RFC 3339 format
            before (datetime, optional): Only show notifications updated before the
                given time. This is a timestamp in RFC 3339 format
            page (int, optional): page number of results to return (1-based)
            limit (int, optional): page size of results

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. NotificationThreadList

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.SERVER1)
            .path("/repos/{owner}/{repo}/notifications")
            .http_method(HttpMethodEnum.GET)
            .template_param(Parameter()
                .key("owner")
                .value(owner)
                .is_required(True)
                .should_encode(True))
            .template_param(Parameter()
                .key("repo")
                .value(repo)
                .is_required(True)
                .should_encode(True))
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/json"))
            .query_param(Parameter()
                .key("all")
                .value(all))
            .query_param(Parameter()
                .key("status-types")
                .value(status_types))
            .query_param(Parameter()
                .key("subject-type")
                .value(subject_type))
            .query_param(Parameter()
                .key("since")
                .value(APIHelper.when_defined(APIHelper.RFC3339DateTime,
                    since)))
            .query_param(Parameter()
                .key("before")
                .value(APIHelper.when_defined(APIHelper.RFC3339DateTime,
                    before)))
            .query_param(Parameter()
                .key("page")
                .value(page))
            .query_param(Parameter()
                .key("limit")
                .value(limit))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Or(Single("BasicAuth"), Single("Token"),
                Single("AccessToken"), Single("AuthorizationHeaderToken"),
                Single("SudoParam"), Single("SudoHeader"), Single("TOTPHeader"))),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(NotificationThread.from_dictionary)
            .is_api_response(True),
        ).execute()

    def notify_read_repo_list(self,
                              owner,
                              repo,
                              all=None,
                              status_types=None,
                              to_status=None,
                              last_read_at=None):
        """Perform a PUT request to /repos/{owner}/{repo}/notifications.

        Mark notification threads as read, pinned or unread on a specific repo

        Args:
            owner (str): owner of the repo
            repo (str): name of the repo
            all (str, optional): If true, mark all notifications on this repo.
                Default value is false
            status_types (List[str], optional): Mark notifications with the provided
                status types. Options are: unread, read and/or pinned. Defaults to
                unread.
            to_status (str, optional): Status to mark notifications as. Defaults to
                read.
            last_read_at (datetime, optional): Describes the last point that
                notifications were checked. Anything updated since this time will not
                be updated.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. NotificationThreadList

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.SERVER1)
            .path("/repos/{owner}/{repo}/notifications")
            .http_method(HttpMethodEnum.PUT)
            .template_param(Parameter()
                .key("owner")
                .value(owner)
                .is_required(True)
                .should_encode(True))
            .template_param(Parameter()
                .key("repo")
                .value(repo)
                .is_required(True)
                .should_encode(True))
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/json"))
            .query_param(Parameter()
                .key("all")
                .value(all))
            .query_param(Parameter()
                .key("status-types")
                .value(status_types))
            .query_param(Parameter()
                .key("to-status")
                .value(to_status))
            .query_param(Parameter()
                .key("last_read_at")
                .value(APIHelper.when_defined(APIHelper.RFC3339DateTime,
                    last_read_at)))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Or(Single("BasicAuth"), Single("Token"),
                Single("AccessToken"), Single("AuthorizationHeaderToken"),
                Single("SudoParam"), Single("SudoHeader"), Single("TOTPHeader"))),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(NotificationThread.from_dictionary)
            .is_api_response(True),
        ).execute()
