"""gitea.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from gitea.api_helper import APIHelper


class Badge(object):
    """Implementation of the 'Badge' model.

    Badge represents a user badge

    Attributes:
        description (str): The model property of type str.
        id (int): The model property of type int.
        image_url (str): The model property of type str.
        slug (str): The model property of type str.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "description": "description",
        "id": "id",
        "image_url": "image_url",
        "slug": "slug",
    }

    _optionals = [
        "description",
        "id",
        "image_url",
        "slug",
    ]

    def __init__(
        self,
        description=APIHelper.SKIP,
        id=APIHelper.SKIP,
        image_url=APIHelper.SKIP,
        slug=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Badge instance."""
        # Initialize members of the class
        if description is not APIHelper.SKIP:
            self.description = description
        if id is not APIHelper.SKIP:
            self.id = id
        if image_url is not APIHelper.SKIP:
            self.image_url = image_url
        if slug is not APIHelper.SKIP:
            self.slug = slug

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        description =\
            dictionary.get("description")\
            if dictionary.get("description")\
                else APIHelper.SKIP
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else APIHelper.SKIP
        image_url =\
            dictionary.get("image_url")\
            if dictionary.get("image_url")\
                else APIHelper.SKIP
        slug =\
            dictionary.get("slug")\
            if dictionary.get("slug")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(description,
                   id,
                   image_url,
                   slug,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _image_url=(
            self.image_url
            if hasattr(self, "image_url")
            else None
        )
        _slug=(
            self.slug
            if hasattr(self, "slug")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"description={_description!r}, "
            f"id={_id!r}, "
            f"image_url={_image_url!r}, "
            f"slug={_slug!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _image_url=(
            self.image_url
            if hasattr(self, "image_url")
            else None
        )
        _slug=(
            self.slug
            if hasattr(self, "slug")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"description={_description!s}, "
            f"id={_id!s}, "
            f"image_url={_image_url!s}, "
            f"slug={_slug!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
