"""gitea.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from gitea.api_helper import APIHelper
from gitea.models.payload_commit import PayloadCommit


class Branch(object):
    """Implementation of the 'Branch' model.

    Branch represents a repository branch

    Attributes:
        commit (PayloadCommit): PayloadCommit represents a commit
        effective_branch_protection_name (str): EffectiveBranchProtectionName is the
            name of the effective branch protection rule
        enable_status_check (bool): EnableStatusCheck indicates if status checks are
            enabled
        name (str): Name is the branch name
        protected (bool): Protected indicates if the branch is protected
        required_approvals (int): RequiredApprovals is the number of required
            approvals for pull requests
        status_check_contexts (List[str]): StatusCheckContexts contains the list of
            required status check contexts
        user_can_merge (bool): UserCanMerge indicates if the current user can merge
            to this branch
        user_can_push (bool): UserCanPush indicates if the current user can push to
            this branch
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "commit": "commit",
        "effective_branch_protection_name": "effective_branch_protection_name",
        "enable_status_check": "enable_status_check",
        "name": "name",
        "protected": "protected",
        "required_approvals": "required_approvals",
        "status_check_contexts": "status_check_contexts",
        "user_can_merge": "user_can_merge",
        "user_can_push": "user_can_push",
    }

    _optionals = [
        "commit",
        "effective_branch_protection_name",
        "enable_status_check",
        "name",
        "protected",
        "required_approvals",
        "status_check_contexts",
        "user_can_merge",
        "user_can_push",
    ]

    def __init__(
        self,
        commit=APIHelper.SKIP,
        effective_branch_protection_name=APIHelper.SKIP,
        enable_status_check=APIHelper.SKIP,
        name=APIHelper.SKIP,
        protected=APIHelper.SKIP,
        required_approvals=APIHelper.SKIP,
        status_check_contexts=APIHelper.SKIP,
        user_can_merge=APIHelper.SKIP,
        user_can_push=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Branch instance."""
        # Initialize members of the class
        if commit is not APIHelper.SKIP:
            self.commit = commit
        if effective_branch_protection_name is not APIHelper.SKIP:
            self.effective_branch_protection_name = effective_branch_protection_name
        if enable_status_check is not APIHelper.SKIP:
            self.enable_status_check = enable_status_check
        if name is not APIHelper.SKIP:
            self.name = name
        if protected is not APIHelper.SKIP:
            self.protected = protected
        if required_approvals is not APIHelper.SKIP:
            self.required_approvals = required_approvals
        if status_check_contexts is not APIHelper.SKIP:
            self.status_check_contexts = status_check_contexts
        if user_can_merge is not APIHelper.SKIP:
            self.user_can_merge = user_can_merge
        if user_can_push is not APIHelper.SKIP:
            self.user_can_push = user_can_push

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        commit =\
            PayloadCommit.from_dictionary(
                dictionary.get("commit"))\
                if "commit" in dictionary.keys()\
                else APIHelper.SKIP
        effective_branch_protection_name =\
            dictionary.get("effective_branch_protection_name")\
            if dictionary.get("effective_branch_protection_name")\
                else APIHelper.SKIP
        enable_status_check =\
            dictionary.get("enable_status_check")\
            if "enable_status_check" in dictionary.keys()\
                else APIHelper.SKIP
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else APIHelper.SKIP
        protected =\
            dictionary.get("protected")\
            if "protected" in dictionary.keys()\
                else APIHelper.SKIP
        required_approvals =\
            dictionary.get("required_approvals")\
            if dictionary.get("required_approvals")\
                else APIHelper.SKIP
        status_check_contexts =\
            dictionary.get("status_check_contexts")\
            if dictionary.get("status_check_contexts")\
                else APIHelper.SKIP
        user_can_merge =\
            dictionary.get("user_can_merge")\
            if "user_can_merge" in dictionary.keys()\
                else APIHelper.SKIP
        user_can_push =\
            dictionary.get("user_can_push")\
            if "user_can_push" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(commit,
                   effective_branch_protection_name,
                   enable_status_check,
                   name,
                   protected,
                   required_approvals,
                   status_check_contexts,
                   user_can_merge,
                   user_can_push,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _commit=(
            self.commit
            if hasattr(self, "commit")
            else None
        )
        _effective_branch_protection_name=(
            self.effective_branch_protection_name
            if hasattr(self, "effective_branch_protection_name")
            else None
        )
        _enable_status_check=(
            self.enable_status_check
            if hasattr(self, "enable_status_check")
            else None
        )
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _protected=(
            self.protected
            if hasattr(self, "protected")
            else None
        )
        _required_approvals=(
            self.required_approvals
            if hasattr(self, "required_approvals")
            else None
        )
        _status_check_contexts=(
            self.status_check_contexts
            if hasattr(self, "status_check_contexts")
            else None
        )
        _user_can_merge=(
            self.user_can_merge
            if hasattr(self, "user_can_merge")
            else None
        )
        _user_can_push=(
            self.user_can_push
            if hasattr(self, "user_can_push")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"commit={_commit!r}, "
            f"effective_branch_protection_name={_effective_branch_protection_name!r}, "
            f"enable_status_check={_enable_status_check!r}, "
            f"name={_name!r}, "
            f"protected={_protected!r}, "
            f"required_approvals={_required_approvals!r}, "
            f"status_check_contexts={_status_check_contexts!r}, "
            f"user_can_merge={_user_can_merge!r}, "
            f"user_can_push={_user_can_push!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _commit=(
            self.commit
            if hasattr(self, "commit")
            else None
        )
        _effective_branch_protection_name=(
            self.effective_branch_protection_name
            if hasattr(self, "effective_branch_protection_name")
            else None
        )
        _enable_status_check=(
            self.enable_status_check
            if hasattr(self, "enable_status_check")
            else None
        )
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _protected=(
            self.protected
            if hasattr(self, "protected")
            else None
        )
        _required_approvals=(
            self.required_approvals
            if hasattr(self, "required_approvals")
            else None
        )
        _status_check_contexts=(
            self.status_check_contexts
            if hasattr(self, "status_check_contexts")
            else None
        )
        _user_can_merge=(
            self.user_can_merge
            if hasattr(self, "user_can_merge")
            else None
        )
        _user_can_push=(
            self.user_can_push
            if hasattr(self, "user_can_push")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"commit={_commit!s}, "
            f"effective_branch_protection_name={_effective_branch_protection_name!s}, "
            f"enable_status_check={_enable_status_check!s}, "
            f"name={_name!s}, "
            f"protected={_protected!s}, "
            f"required_approvals={_required_approvals!s}, "
            f"status_check_contexts={_status_check_contexts!s}, "
            f"user_can_merge={_user_can_merge!s}, "
            f"user_can_push={_user_can_push!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
