"""gitea.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from gitea.api_helper import APIHelper
from gitea.models.change_file_operation import (
    ChangeFileOperation,
)
from gitea.models.commit_date_options import (
    CommitDateOptions,
)
from gitea.models.identity import Identity


class ChangeFilesOptions(object):
    """Implementation of the 'ChangeFilesOptions' model.

    ChangeFilesOptions options for creating, updating or deleting multiple files
    Note: `author` and `committer` are optional (if only one is given, it will be
    used for the other, otherwise the authenticated user will be used)

    Attributes:
        author (Identity): Identity for a person's identity like an author or
            committer
        branch (str): branch (optional) is the base branch for the changes. If not
            supplied, the default branch is used
        committer (Identity): Identity for a person's identity like an author or
            committer
        dates (CommitDateOptions): CommitDateOptions store dates for GIT_AUTHOR_DATE
            and GIT_COMMITTER_DATE
        files (List[ChangeFileOperation]): list of file operations
        force_push (bool): force_push (optional) will do a force-push if the new
            branch already exists
        message (str): message (optional) is the commit message of the changes. If
            not supplied, a default message will be used
        new_branch (str): new_branch (optional) will make a new branch from base
            branch for the changes. If not supplied, the changes will be committed to
            the base branch
        signoff (bool): Add a Signed-off-by trailer by the committer at the end of
            the commit log message.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "files": "files",
        "author": "author",
        "branch": "branch",
        "committer": "committer",
        "dates": "dates",
        "force_push": "force_push",
        "message": "message",
        "new_branch": "new_branch",
        "signoff": "signoff",
    }

    _optionals = [
        "author",
        "branch",
        "committer",
        "dates",
        "force_push",
        "message",
        "new_branch",
        "signoff",
    ]

    def __init__(
        self,
        files=None,
        author=APIHelper.SKIP,
        branch=APIHelper.SKIP,
        committer=APIHelper.SKIP,
        dates=APIHelper.SKIP,
        force_push=APIHelper.SKIP,
        message=APIHelper.SKIP,
        new_branch=APIHelper.SKIP,
        signoff=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ChangeFilesOptions instance."""
        # Initialize members of the class
        if author is not APIHelper.SKIP:
            self.author = author
        if branch is not APIHelper.SKIP:
            self.branch = branch
        if committer is not APIHelper.SKIP:
            self.committer = committer
        if dates is not APIHelper.SKIP:
            self.dates = dates
        self.files = files
        if force_push is not APIHelper.SKIP:
            self.force_push = force_push
        if message is not APIHelper.SKIP:
            self.message = message
        if new_branch is not APIHelper.SKIP:
            self.new_branch = new_branch
        if signoff is not APIHelper.SKIP:
            self.signoff = signoff

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        files = None
        if dictionary.get("files") is not None:
            files = [
                ChangeFileOperation.from_dictionary(x)
                    for x in dictionary.get("files")
            ]
        author =\
            Identity.from_dictionary(
                dictionary.get("author"))\
                if "author" in dictionary.keys()\
                else APIHelper.SKIP
        branch =\
            dictionary.get("branch")\
            if dictionary.get("branch")\
                else APIHelper.SKIP
        committer =\
            Identity.from_dictionary(
                dictionary.get("committer"))\
                if "committer" in dictionary.keys()\
                else APIHelper.SKIP
        dates =\
            CommitDateOptions.from_dictionary(
                dictionary.get("dates"))\
                if "dates" in dictionary.keys()\
                else APIHelper.SKIP
        force_push =\
            dictionary.get("force_push")\
            if "force_push" in dictionary.keys()\
                else APIHelper.SKIP
        message =\
            dictionary.get("message")\
            if dictionary.get("message")\
                else APIHelper.SKIP
        new_branch =\
            dictionary.get("new_branch")\
            if dictionary.get("new_branch")\
                else APIHelper.SKIP
        signoff =\
            dictionary.get("signoff")\
            if "signoff" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(files,
                   author,
                   branch,
                   committer,
                   dates,
                   force_push,
                   message,
                   new_branch,
                   signoff,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _author=(
            self.author
            if hasattr(self, "author")
            else None
        )
        _branch=(
            self.branch
            if hasattr(self, "branch")
            else None
        )
        _committer=(
            self.committer
            if hasattr(self, "committer")
            else None
        )
        _dates=(
            self.dates
            if hasattr(self, "dates")
            else None
        )
        _files=self.files
        _force_push=(
            self.force_push
            if hasattr(self, "force_push")
            else None
        )
        _message=(
            self.message
            if hasattr(self, "message")
            else None
        )
        _new_branch=(
            self.new_branch
            if hasattr(self, "new_branch")
            else None
        )
        _signoff=(
            self.signoff
            if hasattr(self, "signoff")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"author={_author!r}, "
            f"branch={_branch!r}, "
            f"committer={_committer!r}, "
            f"dates={_dates!r}, "
            f"files={_files!r}, "
            f"force_push={_force_push!r}, "
            f"message={_message!r}, "
            f"new_branch={_new_branch!r}, "
            f"signoff={_signoff!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _author=(
            self.author
            if hasattr(self, "author")
            else None
        )
        _branch=(
            self.branch
            if hasattr(self, "branch")
            else None
        )
        _committer=(
            self.committer
            if hasattr(self, "committer")
            else None
        )
        _dates=(
            self.dates
            if hasattr(self, "dates")
            else None
        )
        _files=self.files
        _force_push=(
            self.force_push
            if hasattr(self, "force_push")
            else None
        )
        _message=(
            self.message
            if hasattr(self, "message")
            else None
        )
        _new_branch=(
            self.new_branch
            if hasattr(self, "new_branch")
            else None
        )
        _signoff=(
            self.signoff
            if hasattr(self, "signoff")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"author={_author!s}, "
            f"branch={_branch!s}, "
            f"committer={_committer!s}, "
            f"dates={_dates!s}, "
            f"files={_files!s}, "
            f"force_push={_force_push!s}, "
            f"message={_message!s}, "
            f"new_branch={_new_branch!s}, "
            f"signoff={_signoff!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
