"""gitea.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from gitea.api_helper import APIHelper


class CommitDateOptions(object):
    """Implementation of the 'CommitDateOptions' model.

    CommitDateOptions store dates for GIT_AUTHOR_DATE and GIT_COMMITTER_DATE

    Attributes:
        author (datetime): The model property of type datetime.
        committer (datetime): The model property of type datetime.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "author": "author",
        "committer": "committer",
    }

    _optionals = [
        "author",
        "committer",
    ]

    def __init__(
        self,
        author=APIHelper.SKIP,
        committer=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a CommitDateOptions instance."""
        # Initialize members of the class
        if author is not APIHelper.SKIP:
            self.author =\
                 APIHelper.apply_datetime_converter(
                author, APIHelper.RFC3339DateTime)\
                 if author else None
        if committer is not APIHelper.SKIP:
            self.committer =\
                 APIHelper.apply_datetime_converter(
                committer, APIHelper.RFC3339DateTime)\
                 if committer else None

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        author = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("author")).datetime\
            if dictionary.get("author") else APIHelper.SKIP
        committer = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("committer")).datetime\
            if dictionary.get("committer") else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(author,
                   committer,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _author=(
            self.author
            if hasattr(self, "author")
            else None
        )
        _committer=(
            self.committer
            if hasattr(self, "committer")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"author={_author!r}, "
            f"committer={_committer!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _author=(
            self.author
            if hasattr(self, "author")
            else None
        )
        _committer=(
            self.committer
            if hasattr(self, "committer")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"author={_author!s}, "
            f"committer={_committer!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
