"""gitea.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from gitea.api_helper import APIHelper


class CreatePullRequestOption(object):
    """Implementation of the 'CreatePullRequestOption' model.

    CreatePullRequestOption options when creating a pull request

    Attributes:
        allow_maintainer_edit (bool): Whether maintainers can edit the pull request
        assignee (str): The primary assignee username
        assignees (List[str]): The list of assignee usernames
        base (str): The base branch for the pull request
        body (str): The description body of the pull request
        due_date (datetime): The model property of type datetime.
        head (str): The head branch for the pull request, it could be a branch name
            on the base repository or a form like `<username>:<branch>` which refers
            to the user's fork repository's branch.
        labels (List[int]): The list of label IDs to assign to the pull request
        milestone (int): The milestone ID to assign to the pull request
        reviewers (List[str]): The list of reviewer usernames
        team_reviewers (List[str]): The list of team reviewer names
        title (str): The title of the pull request
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "allow_maintainer_edit": "allow_maintainer_edit",
        "assignee": "assignee",
        "assignees": "assignees",
        "base": "base",
        "body": "body",
        "due_date": "due_date",
        "head": "head",
        "labels": "labels",
        "milestone": "milestone",
        "reviewers": "reviewers",
        "team_reviewers": "team_reviewers",
        "title": "title",
    }

    _optionals = [
        "allow_maintainer_edit",
        "assignee",
        "assignees",
        "base",
        "body",
        "due_date",
        "head",
        "labels",
        "milestone",
        "reviewers",
        "team_reviewers",
        "title",
    ]

    def __init__(
        self,
        allow_maintainer_edit=APIHelper.SKIP,
        assignee=APIHelper.SKIP,
        assignees=APIHelper.SKIP,
        base=APIHelper.SKIP,
        body=APIHelper.SKIP,
        due_date=APIHelper.SKIP,
        head=APIHelper.SKIP,
        labels=APIHelper.SKIP,
        milestone=APIHelper.SKIP,
        reviewers=APIHelper.SKIP,
        team_reviewers=APIHelper.SKIP,
        title=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a CreatePullRequestOption instance."""
        # Initialize members of the class
        if allow_maintainer_edit is not APIHelper.SKIP:
            self.allow_maintainer_edit = allow_maintainer_edit
        if assignee is not APIHelper.SKIP:
            self.assignee = assignee
        if assignees is not APIHelper.SKIP:
            self.assignees = assignees
        if base is not APIHelper.SKIP:
            self.base = base
        if body is not APIHelper.SKIP:
            self.body = body
        if due_date is not APIHelper.SKIP:
            self.due_date =\
                 APIHelper.apply_datetime_converter(
                due_date, APIHelper.RFC3339DateTime)\
                 if due_date else None
        if head is not APIHelper.SKIP:
            self.head = head
        if labels is not APIHelper.SKIP:
            self.labels = labels
        if milestone is not APIHelper.SKIP:
            self.milestone = milestone
        if reviewers is not APIHelper.SKIP:
            self.reviewers = reviewers
        if team_reviewers is not APIHelper.SKIP:
            self.team_reviewers = team_reviewers
        if title is not APIHelper.SKIP:
            self.title = title

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        allow_maintainer_edit =\
            dictionary.get("allow_maintainer_edit")\
            if "allow_maintainer_edit" in dictionary.keys()\
                else APIHelper.SKIP
        assignee =\
            dictionary.get("assignee")\
            if dictionary.get("assignee")\
                else APIHelper.SKIP
        assignees =\
            dictionary.get("assignees")\
            if dictionary.get("assignees")\
                else APIHelper.SKIP
        base =\
            dictionary.get("base")\
            if dictionary.get("base")\
                else APIHelper.SKIP
        body =\
            dictionary.get("body")\
            if dictionary.get("body")\
                else APIHelper.SKIP
        due_date = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("due_date")).datetime\
            if dictionary.get("due_date") else APIHelper.SKIP
        head =\
            dictionary.get("head")\
            if dictionary.get("head")\
                else APIHelper.SKIP
        labels =\
            dictionary.get("labels")\
            if dictionary.get("labels")\
                else APIHelper.SKIP
        milestone =\
            dictionary.get("milestone")\
            if dictionary.get("milestone")\
                else APIHelper.SKIP
        reviewers =\
            dictionary.get("reviewers")\
            if dictionary.get("reviewers")\
                else APIHelper.SKIP
        team_reviewers =\
            dictionary.get("team_reviewers")\
            if dictionary.get("team_reviewers")\
                else APIHelper.SKIP
        title =\
            dictionary.get("title")\
            if dictionary.get("title")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(allow_maintainer_edit,
                   assignee,
                   assignees,
                   base,
                   body,
                   due_date,
                   head,
                   labels,
                   milestone,
                   reviewers,
                   team_reviewers,
                   title,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _allow_maintainer_edit=(
            self.allow_maintainer_edit
            if hasattr(self, "allow_maintainer_edit")
            else None
        )
        _assignee=(
            self.assignee
            if hasattr(self, "assignee")
            else None
        )
        _assignees=(
            self.assignees
            if hasattr(self, "assignees")
            else None
        )
        _base=(
            self.base
            if hasattr(self, "base")
            else None
        )
        _body=(
            self.body
            if hasattr(self, "body")
            else None
        )
        _due_date=(
            self.due_date
            if hasattr(self, "due_date")
            else None
        )
        _head=(
            self.head
            if hasattr(self, "head")
            else None
        )
        _labels=(
            self.labels
            if hasattr(self, "labels")
            else None
        )
        _milestone=(
            self.milestone
            if hasattr(self, "milestone")
            else None
        )
        _reviewers=(
            self.reviewers
            if hasattr(self, "reviewers")
            else None
        )
        _team_reviewers=(
            self.team_reviewers
            if hasattr(self, "team_reviewers")
            else None
        )
        _title=(
            self.title
            if hasattr(self, "title")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"allow_maintainer_edit={_allow_maintainer_edit!r}, "
            f"assignee={_assignee!r}, "
            f"assignees={_assignees!r}, "
            f"base={_base!r}, "
            f"body={_body!r}, "
            f"due_date={_due_date!r}, "
            f"head={_head!r}, "
            f"labels={_labels!r}, "
            f"milestone={_milestone!r}, "
            f"reviewers={_reviewers!r}, "
            f"team_reviewers={_team_reviewers!r}, "
            f"title={_title!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _allow_maintainer_edit=(
            self.allow_maintainer_edit
            if hasattr(self, "allow_maintainer_edit")
            else None
        )
        _assignee=(
            self.assignee
            if hasattr(self, "assignee")
            else None
        )
        _assignees=(
            self.assignees
            if hasattr(self, "assignees")
            else None
        )
        _base=(
            self.base
            if hasattr(self, "base")
            else None
        )
        _body=(
            self.body
            if hasattr(self, "body")
            else None
        )
        _due_date=(
            self.due_date
            if hasattr(self, "due_date")
            else None
        )
        _head=(
            self.head
            if hasattr(self, "head")
            else None
        )
        _labels=(
            self.labels
            if hasattr(self, "labels")
            else None
        )
        _milestone=(
            self.milestone
            if hasattr(self, "milestone")
            else None
        )
        _reviewers=(
            self.reviewers
            if hasattr(self, "reviewers")
            else None
        )
        _team_reviewers=(
            self.team_reviewers
            if hasattr(self, "team_reviewers")
            else None
        )
        _title=(
            self.title
            if hasattr(self, "title")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"allow_maintainer_edit={_allow_maintainer_edit!s}, "
            f"assignee={_assignee!s}, "
            f"assignees={_assignees!s}, "
            f"base={_base!s}, "
            f"body={_body!s}, "
            f"due_date={_due_date!s}, "
            f"head={_head!s}, "
            f"labels={_labels!s}, "
            f"milestone={_milestone!s}, "
            f"reviewers={_reviewers!s}, "
            f"team_reviewers={_team_reviewers!s}, "
            f"title={_title!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
