"""gitea.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from gitea.api_helper import APIHelper


class CreateMilestoneOption(object):
    """Implementation of the 'CreateMilestoneOption' model.

    CreateMilestoneOption options for creating a milestone

    Attributes:
        description (str): Description provides details about the milestone
        due_on (datetime): The model property of type datetime.
        state (State1): The model property of type State1.
        title (str): Title is the title of the new milestone
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "description": "description",
        "due_on": "due_on",
        "state": "state",
        "title": "title",
    }

    _optionals = [
        "description",
        "due_on",
        "state",
        "title",
    ]

    def __init__(
        self,
        description=APIHelper.SKIP,
        due_on=APIHelper.SKIP,
        state=APIHelper.SKIP,
        title=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a CreateMilestoneOption instance."""
        # Initialize members of the class
        if description is not APIHelper.SKIP:
            self.description = description
        if due_on is not APIHelper.SKIP:
            self.due_on =\
                 APIHelper.apply_datetime_converter(
                due_on, APIHelper.RFC3339DateTime)\
                 if due_on else None
        if state is not APIHelper.SKIP:
            self.state = state
        if title is not APIHelper.SKIP:
            self.title = title

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        description =\
            dictionary.get("description")\
            if dictionary.get("description")\
                else APIHelper.SKIP
        due_on = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("due_on")).datetime\
            if dictionary.get("due_on") else APIHelper.SKIP
        state =\
            dictionary.get("state")\
            if dictionary.get("state")\
                else APIHelper.SKIP
        title =\
            dictionary.get("title")\
            if dictionary.get("title")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(description,
                   due_on,
                   state,
                   title,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _due_on=(
            self.due_on
            if hasattr(self, "due_on")
            else None
        )
        _state=(
            self.state
            if hasattr(self, "state")
            else None
        )
        _title=(
            self.title
            if hasattr(self, "title")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"description={_description!r}, "
            f"due_on={_due_on!r}, "
            f"state={_state!r}, "
            f"title={_title!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _due_on=(
            self.due_on
            if hasattr(self, "due_on")
            else None
        )
        _state=(
            self.state
            if hasattr(self, "state")
            else None
        )
        _title=(
            self.title
            if hasattr(self, "title")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"description={_description!s}, "
            f"due_on={_due_on!s}, "
            f"state={_state!s}, "
            f"title={_title!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
