"""gitea.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from gitea.api_helper import APIHelper


class EditUserOption(object):
    """Implementation of the 'EditUserOption' model.

    EditUserOption edit user options

    Attributes:
        active (bool): Whether the user account is active
        admin (bool): Whether the user has administrator privileges
        allow_create_organization (bool): Whether the user can create organizations
        allow_git_hook (bool): Whether the user can use Git hooks
        allow_import_local (bool): Whether the user can import local repositories
        description (str): The user's personal description or bio
        email (str): The model property of type str.
        full_name (str): The full display name of the user
        location (str): The user's location or address
        login_name (str): identifier of the user, provided by the external
            authenticator (if configured)
        max_repo_creation (int): Maximum number of repositories the user can create
        must_change_password (bool): Whether the user must change password on next
            login
        password (str): The plain text password for the user
        prohibit_login (bool): Whether the user is prohibited from logging in
        restricted (bool): Whether the user has restricted access privileges
        source_id (int): The model property of type int.
        visibility (Visibility5): User visibility level: public, limited, or private
            public UserVisibilityPublic limited UserVisibilityLimited private
            UserVisibilityPrivate
        website (str): The user's personal website URL
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "login_name": "login_name",
        "source_id": "source_id",
        "active": "active",
        "admin": "admin",
        "allow_create_organization": "allow_create_organization",
        "allow_git_hook": "allow_git_hook",
        "allow_import_local": "allow_import_local",
        "description": "description",
        "email": "email",
        "full_name": "full_name",
        "location": "location",
        "max_repo_creation": "max_repo_creation",
        "must_change_password": "must_change_password",
        "password": "password",
        "prohibit_login": "prohibit_login",
        "restricted": "restricted",
        "visibility": "visibility",
        "website": "website",
    }

    _optionals = [
        "active",
        "admin",
        "allow_create_organization",
        "allow_git_hook",
        "allow_import_local",
        "description",
        "email",
        "full_name",
        "location",
        "max_repo_creation",
        "must_change_password",
        "password",
        "prohibit_login",
        "restricted",
        "visibility",
        "website",
    ]

    def __init__(
        self,
        login_name="empty",
        source_id=None,
        active=APIHelper.SKIP,
        admin=APIHelper.SKIP,
        allow_create_organization=APIHelper.SKIP,
        allow_git_hook=APIHelper.SKIP,
        allow_import_local=APIHelper.SKIP,
        description=APIHelper.SKIP,
        email=APIHelper.SKIP,
        full_name=APIHelper.SKIP,
        location=APIHelper.SKIP,
        max_repo_creation=APIHelper.SKIP,
        must_change_password=APIHelper.SKIP,
        password=APIHelper.SKIP,
        prohibit_login=APIHelper.SKIP,
        restricted=APIHelper.SKIP,
        visibility=APIHelper.SKIP,
        website=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a EditUserOption instance."""
        # Initialize members of the class
        if active is not APIHelper.SKIP:
            self.active = active
        if admin is not APIHelper.SKIP:
            self.admin = admin
        if allow_create_organization is not APIHelper.SKIP:
            self.allow_create_organization = allow_create_organization
        if allow_git_hook is not APIHelper.SKIP:
            self.allow_git_hook = allow_git_hook
        if allow_import_local is not APIHelper.SKIP:
            self.allow_import_local = allow_import_local
        if description is not APIHelper.SKIP:
            self.description = description
        if email is not APIHelper.SKIP:
            self.email = email
        if full_name is not APIHelper.SKIP:
            self.full_name = full_name
        if location is not APIHelper.SKIP:
            self.location = location
        self.login_name = login_name
        if max_repo_creation is not APIHelper.SKIP:
            self.max_repo_creation = max_repo_creation
        if must_change_password is not APIHelper.SKIP:
            self.must_change_password = must_change_password
        if password is not APIHelper.SKIP:
            self.password = password
        if prohibit_login is not APIHelper.SKIP:
            self.prohibit_login = prohibit_login
        if restricted is not APIHelper.SKIP:
            self.restricted = restricted
        self.source_id = source_id
        if visibility is not APIHelper.SKIP:
            self.visibility = visibility
        if website is not APIHelper.SKIP:
            self.website = website

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        login_name =\
            dictionary.get("login_name")\
            if dictionary.get("login_name")\
                else "empty"
        source_id =\
            dictionary.get("source_id")\
            if dictionary.get("source_id")\
                else None
        active =\
            dictionary.get("active")\
            if "active" in dictionary.keys()\
                else APIHelper.SKIP
        admin =\
            dictionary.get("admin")\
            if "admin" in dictionary.keys()\
                else APIHelper.SKIP
        allow_create_organization =\
            dictionary.get("allow_create_organization")\
            if "allow_create_organization" in dictionary.keys()\
                else APIHelper.SKIP
        allow_git_hook =\
            dictionary.get("allow_git_hook")\
            if "allow_git_hook" in dictionary.keys()\
                else APIHelper.SKIP
        allow_import_local =\
            dictionary.get("allow_import_local")\
            if "allow_import_local" in dictionary.keys()\
                else APIHelper.SKIP
        description =\
            dictionary.get("description")\
            if dictionary.get("description")\
                else APIHelper.SKIP
        email =\
            dictionary.get("email")\
            if dictionary.get("email")\
                else APIHelper.SKIP
        full_name =\
            dictionary.get("full_name")\
            if dictionary.get("full_name")\
                else APIHelper.SKIP
        location =\
            dictionary.get("location")\
            if dictionary.get("location")\
                else APIHelper.SKIP
        max_repo_creation =\
            dictionary.get("max_repo_creation")\
            if dictionary.get("max_repo_creation")\
                else APIHelper.SKIP
        must_change_password =\
            dictionary.get("must_change_password")\
            if "must_change_password" in dictionary.keys()\
                else APIHelper.SKIP
        password =\
            dictionary.get("password")\
            if dictionary.get("password")\
                else APIHelper.SKIP
        prohibit_login =\
            dictionary.get("prohibit_login")\
            if "prohibit_login" in dictionary.keys()\
                else APIHelper.SKIP
        restricted =\
            dictionary.get("restricted")\
            if "restricted" in dictionary.keys()\
                else APIHelper.SKIP
        visibility =\
            dictionary.get("visibility")\
            if dictionary.get("visibility")\
                else APIHelper.SKIP
        website =\
            dictionary.get("website")\
            if dictionary.get("website")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(login_name,
                   source_id,
                   active,
                   admin,
                   allow_create_organization,
                   allow_git_hook,
                   allow_import_local,
                   description,
                   email,
                   full_name,
                   location,
                   max_repo_creation,
                   must_change_password,
                   password,
                   prohibit_login,
                   restricted,
                   visibility,
                   website,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _active=(
            self.active
            if hasattr(self, "active")
            else None
        )
        _admin=(
            self.admin
            if hasattr(self, "admin")
            else None
        )
        _allow_create_organization=(
            self.allow_create_organization
            if hasattr(self, "allow_create_organization")
            else None
        )
        _allow_git_hook=(
            self.allow_git_hook
            if hasattr(self, "allow_git_hook")
            else None
        )
        _allow_import_local=(
            self.allow_import_local
            if hasattr(self, "allow_import_local")
            else None
        )
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _email=(
            self.email
            if hasattr(self, "email")
            else None
        )
        _full_name=(
            self.full_name
            if hasattr(self, "full_name")
            else None
        )
        _location=(
            self.location
            if hasattr(self, "location")
            else None
        )
        _login_name=self.login_name
        _max_repo_creation=(
            self.max_repo_creation
            if hasattr(self, "max_repo_creation")
            else None
        )
        _must_change_password=(
            self.must_change_password
            if hasattr(self, "must_change_password")
            else None
        )
        _password=(
            self.password
            if hasattr(self, "password")
            else None
        )
        _prohibit_login=(
            self.prohibit_login
            if hasattr(self, "prohibit_login")
            else None
        )
        _restricted=(
            self.restricted
            if hasattr(self, "restricted")
            else None
        )
        _source_id=self.source_id
        _visibility=(
            self.visibility
            if hasattr(self, "visibility")
            else None
        )
        _website=(
            self.website
            if hasattr(self, "website")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"active={_active!r}, "
            f"admin={_admin!r}, "
            f"allow_create_organization={_allow_create_organization!r}, "
            f"allow_git_hook={_allow_git_hook!r}, "
            f"allow_import_local={_allow_import_local!r}, "
            f"description={_description!r}, "
            f"email={_email!r}, "
            f"full_name={_full_name!r}, "
            f"location={_location!r}, "
            f"login_name={_login_name!r}, "
            f"max_repo_creation={_max_repo_creation!r}, "
            f"must_change_password={_must_change_password!r}, "
            f"password={_password!r}, "
            f"prohibit_login={_prohibit_login!r}, "
            f"restricted={_restricted!r}, "
            f"source_id={_source_id!r}, "
            f"visibility={_visibility!r}, "
            f"website={_website!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _active=(
            self.active
            if hasattr(self, "active")
            else None
        )
        _admin=(
            self.admin
            if hasattr(self, "admin")
            else None
        )
        _allow_create_organization=(
            self.allow_create_organization
            if hasattr(self, "allow_create_organization")
            else None
        )
        _allow_git_hook=(
            self.allow_git_hook
            if hasattr(self, "allow_git_hook")
            else None
        )
        _allow_import_local=(
            self.allow_import_local
            if hasattr(self, "allow_import_local")
            else None
        )
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _email=(
            self.email
            if hasattr(self, "email")
            else None
        )
        _full_name=(
            self.full_name
            if hasattr(self, "full_name")
            else None
        )
        _location=(
            self.location
            if hasattr(self, "location")
            else None
        )
        _login_name=self.login_name
        _max_repo_creation=(
            self.max_repo_creation
            if hasattr(self, "max_repo_creation")
            else None
        )
        _must_change_password=(
            self.must_change_password
            if hasattr(self, "must_change_password")
            else None
        )
        _password=(
            self.password
            if hasattr(self, "password")
            else None
        )
        _prohibit_login=(
            self.prohibit_login
            if hasattr(self, "prohibit_login")
            else None
        )
        _restricted=(
            self.restricted
            if hasattr(self, "restricted")
            else None
        )
        _source_id=self.source_id
        _visibility=(
            self.visibility
            if hasattr(self, "visibility")
            else None
        )
        _website=(
            self.website
            if hasattr(self, "website")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"active={_active!s}, "
            f"admin={_admin!s}, "
            f"allow_create_organization={_allow_create_organization!s}, "
            f"allow_git_hook={_allow_git_hook!s}, "
            f"allow_import_local={_allow_import_local!s}, "
            f"description={_description!s}, "
            f"email={_email!s}, "
            f"full_name={_full_name!s}, "
            f"location={_location!s}, "
            f"login_name={_login_name!s}, "
            f"max_repo_creation={_max_repo_creation!s}, "
            f"must_change_password={_must_change_password!s}, "
            f"password={_password!s}, "
            f"prohibit_login={_prohibit_login!s}, "
            f"restricted={_restricted!s}, "
            f"source_id={_source_id!s}, "
            f"visibility={_visibility!s}, "
            f"website={_website!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
