"""gitea.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from gitea.api_helper import APIHelper


class EditReleaseOption(object):
    """Implementation of the 'EditReleaseOption' model.

    EditReleaseOption options when editing a release

    Attributes:
        body (str): The new release notes or description
        draft (bool): Whether to change the draft status
        name (str): The new display title of the release
        prerelease (bool): Whether to change the prerelease status
        tag_name (str): The new name of the git tag
        target_commitish (str): The new target commitish for the release
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "body": "body",
        "draft": "draft",
        "name": "name",
        "prerelease": "prerelease",
        "tag_name": "tag_name",
        "target_commitish": "target_commitish",
    }

    _optionals = [
        "body",
        "draft",
        "name",
        "prerelease",
        "tag_name",
        "target_commitish",
    ]

    def __init__(
        self,
        body=APIHelper.SKIP,
        draft=APIHelper.SKIP,
        name=APIHelper.SKIP,
        prerelease=APIHelper.SKIP,
        tag_name=APIHelper.SKIP,
        target_commitish=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a EditReleaseOption instance."""
        # Initialize members of the class
        if body is not APIHelper.SKIP:
            self.body = body
        if draft is not APIHelper.SKIP:
            self.draft = draft
        if name is not APIHelper.SKIP:
            self.name = name
        if prerelease is not APIHelper.SKIP:
            self.prerelease = prerelease
        if tag_name is not APIHelper.SKIP:
            self.tag_name = tag_name
        if target_commitish is not APIHelper.SKIP:
            self.target_commitish = target_commitish

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        body =\
            dictionary.get("body")\
            if dictionary.get("body")\
                else APIHelper.SKIP
        draft =\
            dictionary.get("draft")\
            if "draft" in dictionary.keys()\
                else APIHelper.SKIP
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else APIHelper.SKIP
        prerelease =\
            dictionary.get("prerelease")\
            if "prerelease" in dictionary.keys()\
                else APIHelper.SKIP
        tag_name =\
            dictionary.get("tag_name")\
            if dictionary.get("tag_name")\
                else APIHelper.SKIP
        target_commitish =\
            dictionary.get("target_commitish")\
            if dictionary.get("target_commitish")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(body,
                   draft,
                   name,
                   prerelease,
                   tag_name,
                   target_commitish,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _body=(
            self.body
            if hasattr(self, "body")
            else None
        )
        _draft=(
            self.draft
            if hasattr(self, "draft")
            else None
        )
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _prerelease=(
            self.prerelease
            if hasattr(self, "prerelease")
            else None
        )
        _tag_name=(
            self.tag_name
            if hasattr(self, "tag_name")
            else None
        )
        _target_commitish=(
            self.target_commitish
            if hasattr(self, "target_commitish")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"body={_body!r}, "
            f"draft={_draft!r}, "
            f"name={_name!r}, "
            f"prerelease={_prerelease!r}, "
            f"tag_name={_tag_name!r}, "
            f"target_commitish={_target_commitish!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _body=(
            self.body
            if hasattr(self, "body")
            else None
        )
        _draft=(
            self.draft
            if hasattr(self, "draft")
            else None
        )
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _prerelease=(
            self.prerelease
            if hasattr(self, "prerelease")
            else None
        )
        _tag_name=(
            self.tag_name
            if hasattr(self, "tag_name")
            else None
        )
        _target_commitish=(
            self.target_commitish
            if hasattr(self, "target_commitish")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"body={_body!s}, "
            f"draft={_draft!s}, "
            f"name={_name!s}, "
            f"prerelease={_prerelease!s}, "
            f"tag_name={_tag_name!s}, "
            f"target_commitish={_target_commitish!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
