"""gitea.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from gitea.api_helper import APIHelper
from gitea.models.file_commit_response_contains_information_generated_from_a_git_commit_for_a_repo_s_file import (  # noqa: E501
    FileCommitResponseContainsInformationGeneratedFromAGitCommitForARepoSFile,
)
from gitea.models.payload_commit_verification import (
    PayloadCommitVerification,
)


class FileDeleteResponse(object):
    """Implementation of the 'FileDeleteResponse' model.

    FileDeleteResponse contains information about a repo's file that was deleted

    Attributes:
        commit
            (FileCommitResponseContainsInformationGeneratedFromAGitCommitForARepoSFile
            ): The model property of type
            FileCommitResponseContainsInformationGeneratedFromAGitCommitForARepoSFile.
        content (Any): Content is always null for delete operations
        verification (PayloadCommitVerification): PayloadCommitVerification
            represents the GPG verification of a commit
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "commit": "commit",
        "content": "content",
        "verification": "verification",
    }

    _optionals = [
        "commit",
        "content",
        "verification",
    ]

    def __init__(
        self,
        commit=APIHelper.SKIP,
        content=APIHelper.SKIP,
        verification=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a FileDeleteResponse instance."""
        # Initialize members of the class
        if commit is not APIHelper.SKIP:
            self.commit = commit
        if content is not APIHelper.SKIP:
            self.content = content
        if verification is not APIHelper.SKIP:
            self.verification = verification

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        commit =\
            FileCommitResponseContainsInformationGeneratedFromAGitCommitForARepoSFile.from_dictionary(
                dictionary.get("commit"))\
                if "commit" in dictionary.keys()\
                else APIHelper.SKIP
        content =\
            dictionary.get("content")\
            if dictionary.get("content")\
                else APIHelper.SKIP
        verification =\
            PayloadCommitVerification.from_dictionary(
                dictionary.get("verification"))\
                if "verification" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(commit,
                   content,
                   verification,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _commit=(
            self.commit
            if hasattr(self, "commit")
            else None
        )
        _content=(
            self.content
            if hasattr(self, "content")
            else None
        )
        _verification=(
            self.verification
            if hasattr(self, "verification")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"commit={_commit!r}, "
            f"content={_content!r}, "
            f"verification={_verification!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _commit=(
            self.commit
            if hasattr(self, "commit")
            else None
        )
        _content=(
            self.content
            if hasattr(self, "content")
            else None
        )
        _verification=(
            self.verification
            if hasattr(self, "verification")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"commit={_commit!s}, "
            f"content={_content!s}, "
            f"verification={_verification!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
