"""gitea.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from gitea.api_helper import APIHelper


class GitEntry(object):
    """Implementation of the 'GitEntry' model.

    GitEntry represents a git tree

    Attributes:
        mode (str): Mode is the file mode (permissions)
        path (str): Path is the file or directory path
        sha (str): SHA is the Git object SHA
        size (int): Size is the file size in bytes
        mtype (str): Type indicates if this is a file, directory, or symlink
        url (str): URL is the API URL for this tree entry
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "mode": "mode",
        "path": "path",
        "sha": "sha",
        "size": "size",
        "mtype": "type",
        "url": "url",
    }

    _optionals = [
        "mode",
        "path",
        "sha",
        "size",
        "mtype",
        "url",
    ]

    def __init__(
        self,
        mode=APIHelper.SKIP,
        path=APIHelper.SKIP,
        sha=APIHelper.SKIP,
        size=APIHelper.SKIP,
        mtype=APIHelper.SKIP,
        url=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a GitEntry instance."""
        # Initialize members of the class
        if mode is not APIHelper.SKIP:
            self.mode = mode
        if path is not APIHelper.SKIP:
            self.path = path
        if sha is not APIHelper.SKIP:
            self.sha = sha
        if size is not APIHelper.SKIP:
            self.size = size
        if mtype is not APIHelper.SKIP:
            self.mtype = mtype
        if url is not APIHelper.SKIP:
            self.url = url

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        mode =\
            dictionary.get("mode")\
            if dictionary.get("mode")\
                else APIHelper.SKIP
        path =\
            dictionary.get("path")\
            if dictionary.get("path")\
                else APIHelper.SKIP
        sha =\
            dictionary.get("sha")\
            if dictionary.get("sha")\
                else APIHelper.SKIP
        size =\
            dictionary.get("size")\
            if dictionary.get("size")\
                else APIHelper.SKIP
        mtype =\
            dictionary.get("type")\
            if dictionary.get("type")\
                else APIHelper.SKIP
        url =\
            dictionary.get("url")\
            if dictionary.get("url")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(mode,
                   path,
                   sha,
                   size,
                   mtype,
                   url,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _mode=(
            self.mode
            if hasattr(self, "mode")
            else None
        )
        _path=(
            self.path
            if hasattr(self, "path")
            else None
        )
        _sha=(
            self.sha
            if hasattr(self, "sha")
            else None
        )
        _size=(
            self.size
            if hasattr(self, "size")
            else None
        )
        _mtype=(
            self.mtype
            if hasattr(self, "mtype")
            else None
        )
        _url=(
            self.url
            if hasattr(self, "url")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"mode={_mode!r}, "
            f"path={_path!r}, "
            f"sha={_sha!r}, "
            f"size={_size!r}, "
            f"mtype={_mtype!r}, "
            f"url={_url!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _mode=(
            self.mode
            if hasattr(self, "mode")
            else None
        )
        _path=(
            self.path
            if hasattr(self, "path")
            else None
        )
        _sha=(
            self.sha
            if hasattr(self, "sha")
            else None
        )
        _size=(
            self.size
            if hasattr(self, "size")
            else None
        )
        _mtype=(
            self.mtype
            if hasattr(self, "mtype")
            else None
        )
        _url=(
            self.url
            if hasattr(self, "url")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"mode={_mode!s}, "
            f"path={_path!s}, "
            f"sha={_sha!s}, "
            f"size={_size!s}, "
            f"mtype={_mtype!s}, "
            f"url={_url!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
