"""gitea.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from gitea.api_helper import APIHelper


class MarkupOption(object):
    """Implementation of the 'MarkupOption' model.

    MarkupOption markup options

    Attributes:
        context (str): URL path for rendering issue, media and file links Expected
            format: /subpath/{user}/{repo}/src/{branch, commit,
            tag}/{identifier/path}/{file/dir}
        file_path (str): File path for detecting extension in file mode
        mode (str): Mode to render (markdown, comment, wiki, file)
        text (str): Text markup to render
        wiki (bool): Is it a wiki page? (use mode=wiki instead)  Deprecated: true
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "context": "Context",
        "file_path": "FilePath",
        "mode": "Mode",
        "text": "Text",
        "wiki": "Wiki",
    }

    _optionals = [
        "context",
        "file_path",
        "mode",
        "text",
        "wiki",
    ]

    def __init__(
        self,
        context=APIHelper.SKIP,
        file_path=APIHelper.SKIP,
        mode=APIHelper.SKIP,
        text=APIHelper.SKIP,
        wiki=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a MarkupOption instance."""
        # Initialize members of the class
        if context is not APIHelper.SKIP:
            self.context = context
        if file_path is not APIHelper.SKIP:
            self.file_path = file_path
        if mode is not APIHelper.SKIP:
            self.mode = mode
        if text is not APIHelper.SKIP:
            self.text = text
        if wiki is not APIHelper.SKIP:
            self.wiki = wiki

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        context =\
            dictionary.get("Context")\
            if dictionary.get("Context")\
                else APIHelper.SKIP
        file_path =\
            dictionary.get("FilePath")\
            if dictionary.get("FilePath")\
                else APIHelper.SKIP
        mode =\
            dictionary.get("Mode")\
            if dictionary.get("Mode")\
                else APIHelper.SKIP
        text =\
            dictionary.get("Text")\
            if dictionary.get("Text")\
                else APIHelper.SKIP
        wiki =\
            dictionary.get("Wiki")\
            if "Wiki" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(context,
                   file_path,
                   mode,
                   text,
                   wiki,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _context=(
            self.context
            if hasattr(self, "context")
            else None
        )
        _file_path=(
            self.file_path
            if hasattr(self, "file_path")
            else None
        )
        _mode=(
            self.mode
            if hasattr(self, "mode")
            else None
        )
        _text=(
            self.text
            if hasattr(self, "text")
            else None
        )
        _wiki=(
            self.wiki
            if hasattr(self, "wiki")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"context={_context!r}, "
            f"file_path={_file_path!r}, "
            f"mode={_mode!r}, "
            f"text={_text!r}, "
            f"wiki={_wiki!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _context=(
            self.context
            if hasattr(self, "context")
            else None
        )
        _file_path=(
            self.file_path
            if hasattr(self, "file_path")
            else None
        )
        _mode=(
            self.mode
            if hasattr(self, "mode")
            else None
        )
        _text=(
            self.text
            if hasattr(self, "text")
            else None
        )
        _wiki=(
            self.wiki
            if hasattr(self, "wiki")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"context={_context!s}, "
            f"file_path={_file_path!s}, "
            f"mode={_mode!s}, "
            f"text={_text!s}, "
            f"wiki={_wiki!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
