"""gitea.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from gitea.api_helper import APIHelper


class NodeInfoUsageUsers(object):
    """Implementation of the 'NodeInfoUsageUsers' model.

    NodeInfoUsageUsers contains statistics about the users of this server

    Attributes:
        active_halfyear (int): ActiveHalfyear is the amount of users that signed in
            at least once in the last 180 days
        active_month (int): ActiveMonth is the amount of users that signed in at
            least once in the last 30 days
        total (int): Total is the total amount of users on this server
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "active_halfyear": "activeHalfyear",
        "active_month": "activeMonth",
        "total": "total",
    }

    _optionals = [
        "active_halfyear",
        "active_month",
        "total",
    ]

    def __init__(
        self,
        active_halfyear=APIHelper.SKIP,
        active_month=APIHelper.SKIP,
        total=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a NodeInfoUsageUsers instance."""
        # Initialize members of the class
        if active_halfyear is not APIHelper.SKIP:
            self.active_halfyear = active_halfyear
        if active_month is not APIHelper.SKIP:
            self.active_month = active_month
        if total is not APIHelper.SKIP:
            self.total = total

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        active_halfyear =\
            dictionary.get("activeHalfyear")\
            if dictionary.get("activeHalfyear")\
                else APIHelper.SKIP
        active_month =\
            dictionary.get("activeMonth")\
            if dictionary.get("activeMonth")\
                else APIHelper.SKIP
        total =\
            dictionary.get("total")\
            if dictionary.get("total")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(active_halfyear,
                   active_month,
                   total,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _active_halfyear=(
            self.active_halfyear
            if hasattr(self, "active_halfyear")
            else None
        )
        _active_month=(
            self.active_month
            if hasattr(self, "active_month")
            else None
        )
        _total=(
            self.total
            if hasattr(self, "total")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"active_halfyear={_active_halfyear!r}, "
            f"active_month={_active_month!r}, "
            f"total={_total!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _active_halfyear=(
            self.active_halfyear
            if hasattr(self, "active_halfyear")
            else None
        )
        _active_month=(
            self.active_month
            if hasattr(self, "active_month")
            else None
        )
        _total=(
            self.total
            if hasattr(self, "total")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"active_halfyear={_active_halfyear!s}, "
            f"active_month={_active_month!s}, "
            f"total={_total!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
