"""gitea.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from gitea.api_helper import APIHelper


class NodeInfoSoftware(object):
    """Implementation of the 'NodeInfoSoftware' model.

    NodeInfoSoftware contains Metadata about server software in use

    Attributes:
        homepage (str): Homepage is the URL to the homepage of this server software
        name (str): Name is the canonical name of this server software
        repository (str): Repository is the URL to the source code repository
        version (str): Version is the version of this server software
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "homepage": "homepage",
        "name": "name",
        "repository": "repository",
        "version": "version",
    }

    _optionals = [
        "homepage",
        "name",
        "repository",
        "version",
    ]

    def __init__(
        self,
        homepage=APIHelper.SKIP,
        name=APIHelper.SKIP,
        repository=APIHelper.SKIP,
        version=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a NodeInfoSoftware instance."""
        # Initialize members of the class
        if homepage is not APIHelper.SKIP:
            self.homepage = homepage
        if name is not APIHelper.SKIP:
            self.name = name
        if repository is not APIHelper.SKIP:
            self.repository = repository
        if version is not APIHelper.SKIP:
            self.version = version

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        homepage =\
            dictionary.get("homepage")\
            if dictionary.get("homepage")\
                else APIHelper.SKIP
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else APIHelper.SKIP
        repository =\
            dictionary.get("repository")\
            if dictionary.get("repository")\
                else APIHelper.SKIP
        version =\
            dictionary.get("version")\
            if dictionary.get("version")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(homepage,
                   name,
                   repository,
                   version,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _homepage=(
            self.homepage
            if hasattr(self, "homepage")
            else None
        )
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _repository=(
            self.repository
            if hasattr(self, "repository")
            else None
        )
        _version=(
            self.version
            if hasattr(self, "version")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"homepage={_homepage!r}, "
            f"name={_name!r}, "
            f"repository={_repository!r}, "
            f"version={_version!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _homepage=(
            self.homepage
            if hasattr(self, "homepage")
            else None
        )
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _repository=(
            self.repository
            if hasattr(self, "repository")
            else None
        )
        _version=(
            self.version
            if hasattr(self, "version")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"homepage={_homepage!s}, "
            f"name={_name!s}, "
            f"repository={_repository!s}, "
            f"version={_version!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
