"""gitea.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from gitea.api_helper import APIHelper
from gitea.models.commit_contains_information_generated_from_a_git_commit import (
    CommitContainsInformationGeneratedFromAGitCommit,
)


class Note(object):
    """Implementation of the 'Note' model.

    Note contains information related to a git note

    Attributes:
        commit (CommitContainsInformationGeneratedFromAGitCommit): The model property
            of type CommitContainsInformationGeneratedFromAGitCommit.
        message (str): The content message of the git note
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "commit": "commit",
        "message": "message",
    }

    _optionals = [
        "commit",
        "message",
    ]

    def __init__(
        self,
        commit=APIHelper.SKIP,
        message=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Note instance."""
        # Initialize members of the class
        if commit is not APIHelper.SKIP:
            self.commit = commit
        if message is not APIHelper.SKIP:
            self.message = message

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        commit =\
            CommitContainsInformationGeneratedFromAGitCommit.from_dictionary(
                dictionary.get("commit"))\
                if "commit" in dictionary.keys()\
                else APIHelper.SKIP
        message =\
            dictionary.get("message")\
            if dictionary.get("message")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(commit,
                   message,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _commit=(
            self.commit
            if hasattr(self, "commit")
            else None
        )
        _message=(
            self.message
            if hasattr(self, "message")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"commit={_commit!r}, "
            f"message={_message!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _commit=(
            self.commit
            if hasattr(self, "commit")
            else None
        )
        _message=(
            self.message
            if hasattr(self, "message")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"commit={_commit!s}, "
            f"message={_message!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
