"""gitea.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from gitea.api_helper import APIHelper
from gitea.models.notification_subject import (
    NotificationSubject,
)
from gitea.models.repository import Repository


class NotificationThread(object):
    """Implementation of the 'NotificationThread' model.

    NotificationThread expose Notification on API

    Attributes:
        id (int): ID is the unique identifier for the notification thread
        pinned (bool): Pinned indicates if the notification is pinned
        repository (Repository): Repository represents a repository
        subject (NotificationSubject): NotificationSubject contains the notification
            subject (Issue/Pull/Commit)
        unread (bool): Unread indicates if the notification has been read
        updated_at (datetime): UpdatedAt is the time when the notification was last
            updated
        url (str): URL is the API URL for this notification thread
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": "id",
        "pinned": "pinned",
        "repository": "repository",
        "subject": "subject",
        "unread": "unread",
        "updated_at": "updated_at",
        "url": "url",
    }

    _optionals = [
        "id",
        "pinned",
        "repository",
        "subject",
        "unread",
        "updated_at",
        "url",
    ]

    def __init__(
        self,
        id=APIHelper.SKIP,
        pinned=APIHelper.SKIP,
        repository=APIHelper.SKIP,
        subject=APIHelper.SKIP,
        unread=APIHelper.SKIP,
        updated_at=APIHelper.SKIP,
        url=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a NotificationThread instance."""
        # Initialize members of the class
        if id is not APIHelper.SKIP:
            self.id = id
        if pinned is not APIHelper.SKIP:
            self.pinned = pinned
        if repository is not APIHelper.SKIP:
            self.repository = repository
        if subject is not APIHelper.SKIP:
            self.subject = subject
        if unread is not APIHelper.SKIP:
            self.unread = unread
        if updated_at is not APIHelper.SKIP:
            self.updated_at =\
                 APIHelper.apply_datetime_converter(
                updated_at, APIHelper.RFC3339DateTime)\
                 if updated_at else None
        if url is not APIHelper.SKIP:
            self.url = url

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else APIHelper.SKIP
        pinned =\
            dictionary.get("pinned")\
            if "pinned" in dictionary.keys()\
                else APIHelper.SKIP
        repository =\
            Repository.from_dictionary(
                dictionary.get("repository"))\
                if "repository" in dictionary.keys()\
                else APIHelper.SKIP
        subject =\
            NotificationSubject.from_dictionary(
                dictionary.get("subject"))\
                if "subject" in dictionary.keys()\
                else APIHelper.SKIP
        unread =\
            dictionary.get("unread")\
            if "unread" in dictionary.keys()\
                else APIHelper.SKIP
        updated_at = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("updated_at")).datetime\
            if dictionary.get("updated_at") else APIHelper.SKIP
        url =\
            dictionary.get("url")\
            if dictionary.get("url")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(id,
                   pinned,
                   repository,
                   subject,
                   unread,
                   updated_at,
                   url,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _pinned=(
            self.pinned
            if hasattr(self, "pinned")
            else None
        )
        _repository=(
            self.repository
            if hasattr(self, "repository")
            else None
        )
        _subject=(
            self.subject
            if hasattr(self, "subject")
            else None
        )
        _unread=(
            self.unread
            if hasattr(self, "unread")
            else None
        )
        _updated_at=(
            self.updated_at
            if hasattr(self, "updated_at")
            else None
        )
        _url=(
            self.url
            if hasattr(self, "url")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"id={_id!r}, "
            f"pinned={_pinned!r}, "
            f"repository={_repository!r}, "
            f"subject={_subject!r}, "
            f"unread={_unread!r}, "
            f"updated_at={_updated_at!r}, "
            f"url={_url!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _pinned=(
            self.pinned
            if hasattr(self, "pinned")
            else None
        )
        _repository=(
            self.repository
            if hasattr(self, "repository")
            else None
        )
        _subject=(
            self.subject
            if hasattr(self, "subject")
            else None
        )
        _unread=(
            self.unread
            if hasattr(self, "unread")
            else None
        )
        _updated_at=(
            self.updated_at
            if hasattr(self, "updated_at")
            else None
        )
        _url=(
            self.url
            if hasattr(self, "url")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"id={_id!s}, "
            f"pinned={_pinned!s}, "
            f"repository={_repository!s}, "
            f"subject={_subject!s}, "
            f"unread={_unread!s}, "
            f"updated_at={_updated_at!s}, "
            f"url={_url!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
