"""gitea.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class Permission1(object):
    """Implementation of the 'Permission1' enum.

    Attributes:
        NONE: The enum member of type str.
        READ: The enum member of type str.
        WRITE: The enum member of type str.
        ADMIN: The enum member of type str.
        OWNER: The enum member of type str.

    """

    NONE = "none"

    READ = "read"

    WRITE = "write"

    ADMIN = "admin"

    OWNER = "owner"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
