"""gitea.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from gitea.api_helper import APIHelper


class Project(object):
    """Implementation of the 'Project' model.

    Project represents a project

    Attributes:
        closed_at (datetime): The model property of type datetime.
        created_at (datetime): The model property of type datetime.
        creator_id (int): CreatorID is the user who created the project
        description (str): Description provides details about the project
        id (int): ID is the unique identifier for the project
        is_closed (bool): IsClosed indicates if the project is closed
        owner_id (int): OwnerID is the owner of the project (for org-level projects)
        repo_id (int): RepoID is the repository this project belongs to (for
            repo-level projects)
        title (str): Title is the title of the project
        updated_at (datetime): The model property of type datetime.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "closed_at": "closed_at",
        "created_at": "created_at",
        "creator_id": "creator_id",
        "description": "description",
        "id": "id",
        "is_closed": "is_closed",
        "owner_id": "owner_id",
        "repo_id": "repo_id",
        "title": "title",
        "updated_at": "updated_at",
    }

    _optionals = [
        "closed_at",
        "created_at",
        "creator_id",
        "description",
        "id",
        "is_closed",
        "owner_id",
        "repo_id",
        "title",
        "updated_at",
    ]

    def __init__(
        self,
        closed_at=APIHelper.SKIP,
        created_at=APIHelper.SKIP,
        creator_id=APIHelper.SKIP,
        description=APIHelper.SKIP,
        id=APIHelper.SKIP,
        is_closed=APIHelper.SKIP,
        owner_id=APIHelper.SKIP,
        repo_id=APIHelper.SKIP,
        title=APIHelper.SKIP,
        updated_at=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Project instance."""
        # Initialize members of the class
        if closed_at is not APIHelper.SKIP:
            self.closed_at =\
                 APIHelper.apply_datetime_converter(
                closed_at, APIHelper.RFC3339DateTime)\
                 if closed_at else None
        if created_at is not APIHelper.SKIP:
            self.created_at =\
                 APIHelper.apply_datetime_converter(
                created_at, APIHelper.RFC3339DateTime)\
                 if created_at else None
        if creator_id is not APIHelper.SKIP:
            self.creator_id = creator_id
        if description is not APIHelper.SKIP:
            self.description = description
        if id is not APIHelper.SKIP:
            self.id = id
        if is_closed is not APIHelper.SKIP:
            self.is_closed = is_closed
        if owner_id is not APIHelper.SKIP:
            self.owner_id = owner_id
        if repo_id is not APIHelper.SKIP:
            self.repo_id = repo_id
        if title is not APIHelper.SKIP:
            self.title = title
        if updated_at is not APIHelper.SKIP:
            self.updated_at =\
                 APIHelper.apply_datetime_converter(
                updated_at, APIHelper.RFC3339DateTime)\
                 if updated_at else None

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        closed_at = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("closed_at")).datetime\
            if dictionary.get("closed_at") else APIHelper.SKIP
        created_at = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("created_at")).datetime\
            if dictionary.get("created_at") else APIHelper.SKIP
        creator_id =\
            dictionary.get("creator_id")\
            if dictionary.get("creator_id")\
                else APIHelper.SKIP
        description =\
            dictionary.get("description")\
            if dictionary.get("description")\
                else APIHelper.SKIP
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else APIHelper.SKIP
        is_closed =\
            dictionary.get("is_closed")\
            if "is_closed" in dictionary.keys()\
                else APIHelper.SKIP
        owner_id =\
            dictionary.get("owner_id")\
            if dictionary.get("owner_id")\
                else APIHelper.SKIP
        repo_id =\
            dictionary.get("repo_id")\
            if dictionary.get("repo_id")\
                else APIHelper.SKIP
        title =\
            dictionary.get("title")\
            if dictionary.get("title")\
                else APIHelper.SKIP
        updated_at = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("updated_at")).datetime\
            if dictionary.get("updated_at") else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(closed_at,
                   created_at,
                   creator_id,
                   description,
                   id,
                   is_closed,
                   owner_id,
                   repo_id,
                   title,
                   updated_at,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _closed_at=(
            self.closed_at
            if hasattr(self, "closed_at")
            else None
        )
        _created_at=(
            self.created_at
            if hasattr(self, "created_at")
            else None
        )
        _creator_id=(
            self.creator_id
            if hasattr(self, "creator_id")
            else None
        )
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _is_closed=(
            self.is_closed
            if hasattr(self, "is_closed")
            else None
        )
        _owner_id=(
            self.owner_id
            if hasattr(self, "owner_id")
            else None
        )
        _repo_id=(
            self.repo_id
            if hasattr(self, "repo_id")
            else None
        )
        _title=(
            self.title
            if hasattr(self, "title")
            else None
        )
        _updated_at=(
            self.updated_at
            if hasattr(self, "updated_at")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"closed_at={_closed_at!r}, "
            f"created_at={_created_at!r}, "
            f"creator_id={_creator_id!r}, "
            f"description={_description!r}, "
            f"id={_id!r}, "
            f"is_closed={_is_closed!r}, "
            f"owner_id={_owner_id!r}, "
            f"repo_id={_repo_id!r}, "
            f"title={_title!r}, "
            f"updated_at={_updated_at!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _closed_at=(
            self.closed_at
            if hasattr(self, "closed_at")
            else None
        )
        _created_at=(
            self.created_at
            if hasattr(self, "created_at")
            else None
        )
        _creator_id=(
            self.creator_id
            if hasattr(self, "creator_id")
            else None
        )
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _is_closed=(
            self.is_closed
            if hasattr(self, "is_closed")
            else None
        )
        _owner_id=(
            self.owner_id
            if hasattr(self, "owner_id")
            else None
        )
        _repo_id=(
            self.repo_id
            if hasattr(self, "repo_id")
            else None
        )
        _title=(
            self.title
            if hasattr(self, "title")
            else None
        )
        _updated_at=(
            self.updated_at
            if hasattr(self, "updated_at")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"closed_at={_closed_at!s}, "
            f"created_at={_created_at!s}, "
            f"creator_id={_creator_id!s}, "
            f"description={_description!s}, "
            f"id={_id!s}, "
            f"is_closed={_is_closed!s}, "
            f"owner_id={_owner_id!s}, "
            f"repo_id={_repo_id!s}, "
            f"title={_title!s}, "
            f"updated_at={_updated_at!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
