"""gitea.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from gitea.api_helper import APIHelper
from gitea.models.label import Label
from gitea.models.milestone import Milestone
from gitea.models.pr_branch_info import PrBranchInfo
from gitea.models.team import Team
from gitea.models.user import User


class PullRequest(object):
    """Implementation of the 'PullRequest' model.

    PullRequest represents a pull request

    Attributes:
        additions (int): The number of lines added in the pull request
        allow_maintainer_edit (bool): Whether maintainers can edit the pull request
        assignee (User): User represents a user
        assignees (List[User]): The list of users assigned to the pull request
        base (PrBranchInfo): PRBranchInfo information about a branch
        body (str): The description body of the pull request
        changed_files (int): The number of files changed in the pull request
        closed_at (datetime): The model property of type datetime.
        comments (int): The number of comments on the pull request
        content_version (int): The version of the pull request content for optimistic
            locking
        created_at (datetime): The model property of type datetime.
        deletions (int): The number of lines deleted in the pull request
        diff_url (str): The URL to download the diff patch
        draft (bool): Whether the pull request is a draft
        due_date (datetime): The model property of type datetime.
        head (PrBranchInfo): PRBranchInfo information about a branch
        html_url (str): The HTML URL to view the pull request
        id (int): The unique identifier of the pull request
        is_locked (bool): Whether the pull request conversation is locked
        labels (List[Label]): The labels attached to the pull request
        merge_base (str): The merge base commit SHA
        merge_commit_sha (str): The SHA of the merge commit
        mergeable (bool): Whether the pull request can be merged
        merged (bool): Whether the pull request has been merged
        merged_at (datetime): The model property of type datetime.
        merged_by (User): User represents a user
        milestone (Milestone): Milestone milestone is a collection of issues on one
            repository
        number (int): The pull request number
        patch_url (str): The URL to download the patch file
        pin_order (int): The pin order for the pull request
        requested_reviewers (List[User]): The users requested to review the pull
            request
        requested_reviewers_teams (List[Team]): The teams requested to review the
            pull request
        review_comments (int): number of review comments made on the diff of a PR
            review (not including comments on commits or issues in a PR)
        state (State7): The current state of the pull request open StateOpen pr is
            opened closed StateClosed pr is closed
        title (str): The title of the pull request
        updated_at (datetime): The model property of type datetime.
        url (str): The API URL of the pull request
        user (User): User represents a user
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "additions": "additions",
        "allow_maintainer_edit": "allow_maintainer_edit",
        "assignee": "assignee",
        "assignees": "assignees",
        "base": "base",
        "body": "body",
        "changed_files": "changed_files",
        "closed_at": "closed_at",
        "comments": "comments",
        "content_version": "content_version",
        "created_at": "created_at",
        "deletions": "deletions",
        "diff_url": "diff_url",
        "draft": "draft",
        "due_date": "due_date",
        "head": "head",
        "html_url": "html_url",
        "id": "id",
        "is_locked": "is_locked",
        "labels": "labels",
        "merge_base": "merge_base",
        "merge_commit_sha": "merge_commit_sha",
        "mergeable": "mergeable",
        "merged": "merged",
        "merged_at": "merged_at",
        "merged_by": "merged_by",
        "milestone": "milestone",
        "number": "number",
        "patch_url": "patch_url",
        "pin_order": "pin_order",
        "requested_reviewers": "requested_reviewers",
        "requested_reviewers_teams": "requested_reviewers_teams",
        "review_comments": "review_comments",
        "state": "state",
        "title": "title",
        "updated_at": "updated_at",
        "url": "url",
        "user": "user",
    }

    _optionals = [
        "additions",
        "allow_maintainer_edit",
        "assignee",
        "assignees",
        "base",
        "body",
        "changed_files",
        "closed_at",
        "comments",
        "content_version",
        "created_at",
        "deletions",
        "diff_url",
        "draft",
        "due_date",
        "head",
        "html_url",
        "id",
        "is_locked",
        "labels",
        "merge_base",
        "merge_commit_sha",
        "mergeable",
        "merged",
        "merged_at",
        "merged_by",
        "milestone",
        "number",
        "patch_url",
        "pin_order",
        "requested_reviewers",
        "requested_reviewers_teams",
        "review_comments",
        "state",
        "title",
        "updated_at",
        "url",
        "user",
    ]

    def __init__(
        self,
        additions=APIHelper.SKIP,
        allow_maintainer_edit=APIHelper.SKIP,
        assignee=APIHelper.SKIP,
        assignees=APIHelper.SKIP,
        base=APIHelper.SKIP,
        body=APIHelper.SKIP,
        changed_files=APIHelper.SKIP,
        closed_at=APIHelper.SKIP,
        comments=APIHelper.SKIP,
        content_version=APIHelper.SKIP,
        created_at=APIHelper.SKIP,
        deletions=APIHelper.SKIP,
        diff_url=APIHelper.SKIP,
        draft=APIHelper.SKIP,
        due_date=APIHelper.SKIP,
        head=APIHelper.SKIP,
        html_url=APIHelper.SKIP,
        id=APIHelper.SKIP,
        is_locked=APIHelper.SKIP,
        labels=APIHelper.SKIP,
        merge_base=APIHelper.SKIP,
        merge_commit_sha=APIHelper.SKIP,
        mergeable=APIHelper.SKIP,
        merged=APIHelper.SKIP,
        merged_at=APIHelper.SKIP,
        merged_by=APIHelper.SKIP,
        milestone=APIHelper.SKIP,
        number=APIHelper.SKIP,
        patch_url=APIHelper.SKIP,
        pin_order=APIHelper.SKIP,
        requested_reviewers=APIHelper.SKIP,
        requested_reviewers_teams=APIHelper.SKIP,
        review_comments=APIHelper.SKIP,
        state=APIHelper.SKIP,
        title=APIHelper.SKIP,
        updated_at=APIHelper.SKIP,
        url=APIHelper.SKIP,
        user=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a PullRequest instance."""
        # Initialize members of the class
        if additions is not APIHelper.SKIP:
            self.additions = additions
        if allow_maintainer_edit is not APIHelper.SKIP:
            self.allow_maintainer_edit = allow_maintainer_edit
        if assignee is not APIHelper.SKIP:
            self.assignee = assignee
        if assignees is not APIHelper.SKIP:
            self.assignees = assignees
        if base is not APIHelper.SKIP:
            self.base = base
        if body is not APIHelper.SKIP:
            self.body = body
        if changed_files is not APIHelper.SKIP:
            self.changed_files = changed_files
        if closed_at is not APIHelper.SKIP:
            self.closed_at =\
                 APIHelper.apply_datetime_converter(
                closed_at, APIHelper.RFC3339DateTime)\
                 if closed_at else None
        if comments is not APIHelper.SKIP:
            self.comments = comments
        if content_version is not APIHelper.SKIP:
            self.content_version = content_version
        if created_at is not APIHelper.SKIP:
            self.created_at =\
                 APIHelper.apply_datetime_converter(
                created_at, APIHelper.RFC3339DateTime)\
                 if created_at else None
        if deletions is not APIHelper.SKIP:
            self.deletions = deletions
        if diff_url is not APIHelper.SKIP:
            self.diff_url = diff_url
        if draft is not APIHelper.SKIP:
            self.draft = draft
        if due_date is not APIHelper.SKIP:
            self.due_date =\
                 APIHelper.apply_datetime_converter(
                due_date, APIHelper.RFC3339DateTime)\
                 if due_date else None
        if head is not APIHelper.SKIP:
            self.head = head
        if html_url is not APIHelper.SKIP:
            self.html_url = html_url
        if id is not APIHelper.SKIP:
            self.id = id
        if is_locked is not APIHelper.SKIP:
            self.is_locked = is_locked
        if labels is not APIHelper.SKIP:
            self.labels = labels
        if merge_base is not APIHelper.SKIP:
            self.merge_base = merge_base
        if merge_commit_sha is not APIHelper.SKIP:
            self.merge_commit_sha = merge_commit_sha
        if mergeable is not APIHelper.SKIP:
            self.mergeable = mergeable
        if merged is not APIHelper.SKIP:
            self.merged = merged
        if merged_at is not APIHelper.SKIP:
            self.merged_at =\
                 APIHelper.apply_datetime_converter(
                merged_at, APIHelper.RFC3339DateTime)\
                 if merged_at else None
        if merged_by is not APIHelper.SKIP:
            self.merged_by = merged_by
        if milestone is not APIHelper.SKIP:
            self.milestone = milestone
        if number is not APIHelper.SKIP:
            self.number = number
        if patch_url is not APIHelper.SKIP:
            self.patch_url = patch_url
        if pin_order is not APIHelper.SKIP:
            self.pin_order = pin_order
        if requested_reviewers is not APIHelper.SKIP:
            self.requested_reviewers = requested_reviewers
        if requested_reviewers_teams is not APIHelper.SKIP:
            self.requested_reviewers_teams = requested_reviewers_teams
        if review_comments is not APIHelper.SKIP:
            self.review_comments = review_comments
        if state is not APIHelper.SKIP:
            self.state = state
        if title is not APIHelper.SKIP:
            self.title = title
        if updated_at is not APIHelper.SKIP:
            self.updated_at =\
                 APIHelper.apply_datetime_converter(
                updated_at, APIHelper.RFC3339DateTime)\
                 if updated_at else None
        if url is not APIHelper.SKIP:
            self.url = url
        if user is not APIHelper.SKIP:
            self.user = user

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        additions =\
            dictionary.get("additions")\
            if dictionary.get("additions")\
                else APIHelper.SKIP
        allow_maintainer_edit =\
            dictionary.get("allow_maintainer_edit")\
            if "allow_maintainer_edit" in dictionary.keys()\
                else APIHelper.SKIP
        assignee =\
            User.from_dictionary(
                dictionary.get("assignee"))\
                if "assignee" in dictionary.keys()\
                else APIHelper.SKIP
        assignees = None
        if dictionary.get("assignees") is not None:
            assignees = [
                User.from_dictionary(x)
                    for x in dictionary.get("assignees")
            ]
        else:
            assignees = APIHelper.SKIP
        base =\
            PrBranchInfo.from_dictionary(
                dictionary.get("base"))\
                if "base" in dictionary.keys()\
                else APIHelper.SKIP
        body =\
            dictionary.get("body")\
            if dictionary.get("body")\
                else APIHelper.SKIP
        changed_files =\
            dictionary.get("changed_files")\
            if dictionary.get("changed_files")\
                else APIHelper.SKIP
        closed_at = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("closed_at")).datetime\
            if dictionary.get("closed_at") else APIHelper.SKIP
        comments =\
            dictionary.get("comments")\
            if dictionary.get("comments")\
                else APIHelper.SKIP
        content_version =\
            dictionary.get("content_version")\
            if dictionary.get("content_version")\
                else APIHelper.SKIP
        created_at = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("created_at")).datetime\
            if dictionary.get("created_at") else APIHelper.SKIP
        deletions =\
            dictionary.get("deletions")\
            if dictionary.get("deletions")\
                else APIHelper.SKIP
        diff_url =\
            dictionary.get("diff_url")\
            if dictionary.get("diff_url")\
                else APIHelper.SKIP
        draft =\
            dictionary.get("draft")\
            if "draft" in dictionary.keys()\
                else APIHelper.SKIP
        due_date = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("due_date")).datetime\
            if dictionary.get("due_date") else APIHelper.SKIP
        head =\
            PrBranchInfo.from_dictionary(
                dictionary.get("head"))\
                if "head" in dictionary.keys()\
                else APIHelper.SKIP
        html_url =\
            dictionary.get("html_url")\
            if dictionary.get("html_url")\
                else APIHelper.SKIP
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else APIHelper.SKIP
        is_locked =\
            dictionary.get("is_locked")\
            if "is_locked" in dictionary.keys()\
                else APIHelper.SKIP
        labels = None
        if dictionary.get("labels") is not None:
            labels = [
                Label.from_dictionary(x)
                    for x in dictionary.get("labels")
            ]
        else:
            labels = APIHelper.SKIP
        merge_base =\
            dictionary.get("merge_base")\
            if dictionary.get("merge_base")\
                else APIHelper.SKIP
        merge_commit_sha =\
            dictionary.get("merge_commit_sha")\
            if dictionary.get("merge_commit_sha")\
                else APIHelper.SKIP
        mergeable =\
            dictionary.get("mergeable")\
            if "mergeable" in dictionary.keys()\
                else APIHelper.SKIP
        merged =\
            dictionary.get("merged")\
            if "merged" in dictionary.keys()\
                else APIHelper.SKIP
        merged_at = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("merged_at")).datetime\
            if dictionary.get("merged_at") else APIHelper.SKIP
        merged_by =\
            User.from_dictionary(
                dictionary.get("merged_by"))\
                if "merged_by" in dictionary.keys()\
                else APIHelper.SKIP
        milestone =\
            Milestone.from_dictionary(
                dictionary.get("milestone"))\
                if "milestone" in dictionary.keys()\
                else APIHelper.SKIP
        number =\
            dictionary.get("number")\
            if dictionary.get("number")\
                else APIHelper.SKIP
        patch_url =\
            dictionary.get("patch_url")\
            if dictionary.get("patch_url")\
                else APIHelper.SKIP
        pin_order =\
            dictionary.get("pin_order")\
            if dictionary.get("pin_order")\
                else APIHelper.SKIP
        requested_reviewers = None
        if dictionary.get("requested_reviewers") is not None:
            requested_reviewers = [
                User.from_dictionary(x)
                    for x in dictionary.get("requested_reviewers")
            ]
        else:
            requested_reviewers = APIHelper.SKIP
        requested_reviewers_teams = None
        if dictionary.get("requested_reviewers_teams") is not None:
            requested_reviewers_teams = [
                Team.from_dictionary(x)
                    for x in dictionary.get("requested_reviewers_teams")
            ]
        else:
            requested_reviewers_teams = APIHelper.SKIP
        review_comments =\
            dictionary.get("review_comments")\
            if dictionary.get("review_comments")\
                else APIHelper.SKIP
        state =\
            dictionary.get("state")\
            if dictionary.get("state")\
                else APIHelper.SKIP
        title =\
            dictionary.get("title")\
            if dictionary.get("title")\
                else APIHelper.SKIP
        updated_at = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("updated_at")).datetime\
            if dictionary.get("updated_at") else APIHelper.SKIP
        url =\
            dictionary.get("url")\
            if dictionary.get("url")\
                else APIHelper.SKIP
        user =\
            User.from_dictionary(
                dictionary.get("user"))\
                if "user" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(additions,
                   allow_maintainer_edit,
                   assignee,
                   assignees,
                   base,
                   body,
                   changed_files,
                   closed_at,
                   comments,
                   content_version,
                   created_at,
                   deletions,
                   diff_url,
                   draft,
                   due_date,
                   head,
                   html_url,
                   id,
                   is_locked,
                   labels,
                   merge_base,
                   merge_commit_sha,
                   mergeable,
                   merged,
                   merged_at,
                   merged_by,
                   milestone,
                   number,
                   patch_url,
                   pin_order,
                   requested_reviewers,
                   requested_reviewers_teams,
                   review_comments,
                   state,
                   title,
                   updated_at,
                   url,
                   user,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _additions=(
            self.additions
            if hasattr(self, "additions")
            else None
        )
        _allow_maintainer_edit=(
            self.allow_maintainer_edit
            if hasattr(self, "allow_maintainer_edit")
            else None
        )
        _assignee=(
            self.assignee
            if hasattr(self, "assignee")
            else None
        )
        _assignees=(
            self.assignees
            if hasattr(self, "assignees")
            else None
        )
        _base=(
            self.base
            if hasattr(self, "base")
            else None
        )
        _body=(
            self.body
            if hasattr(self, "body")
            else None
        )
        _changed_files=(
            self.changed_files
            if hasattr(self, "changed_files")
            else None
        )
        _closed_at=(
            self.closed_at
            if hasattr(self, "closed_at")
            else None
        )
        _comments=(
            self.comments
            if hasattr(self, "comments")
            else None
        )
        _content_version=(
            self.content_version
            if hasattr(self, "content_version")
            else None
        )
        _created_at=(
            self.created_at
            if hasattr(self, "created_at")
            else None
        )
        _deletions=(
            self.deletions
            if hasattr(self, "deletions")
            else None
        )
        _diff_url=(
            self.diff_url
            if hasattr(self, "diff_url")
            else None
        )
        _draft=(
            self.draft
            if hasattr(self, "draft")
            else None
        )
        _due_date=(
            self.due_date
            if hasattr(self, "due_date")
            else None
        )
        _head=(
            self.head
            if hasattr(self, "head")
            else None
        )
        _html_url=(
            self.html_url
            if hasattr(self, "html_url")
            else None
        )
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _is_locked=(
            self.is_locked
            if hasattr(self, "is_locked")
            else None
        )
        _labels=(
            self.labels
            if hasattr(self, "labels")
            else None
        )
        _merge_base=(
            self.merge_base
            if hasattr(self, "merge_base")
            else None
        )
        _merge_commit_sha=(
            self.merge_commit_sha
            if hasattr(self, "merge_commit_sha")
            else None
        )
        _mergeable=(
            self.mergeable
            if hasattr(self, "mergeable")
            else None
        )
        _merged=(
            self.merged
            if hasattr(self, "merged")
            else None
        )
        _merged_at=(
            self.merged_at
            if hasattr(self, "merged_at")
            else None
        )
        _merged_by=(
            self.merged_by
            if hasattr(self, "merged_by")
            else None
        )
        _milestone=(
            self.milestone
            if hasattr(self, "milestone")
            else None
        )
        _number=(
            self.number
            if hasattr(self, "number")
            else None
        )
        _patch_url=(
            self.patch_url
            if hasattr(self, "patch_url")
            else None
        )
        _pin_order=(
            self.pin_order
            if hasattr(self, "pin_order")
            else None
        )
        _requested_reviewers=(
            self.requested_reviewers
            if hasattr(self, "requested_reviewers")
            else None
        )
        _requested_reviewers_teams=(
            self.requested_reviewers_teams
            if hasattr(self, "requested_reviewers_teams")
            else None
        )
        _review_comments=(
            self.review_comments
            if hasattr(self, "review_comments")
            else None
        )
        _state=(
            self.state
            if hasattr(self, "state")
            else None
        )
        _title=(
            self.title
            if hasattr(self, "title")
            else None
        )
        _updated_at=(
            self.updated_at
            if hasattr(self, "updated_at")
            else None
        )
        _url=(
            self.url
            if hasattr(self, "url")
            else None
        )
        _user=(
            self.user
            if hasattr(self, "user")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"additions={_additions!r}, "
            f"allow_maintainer_edit={_allow_maintainer_edit!r}, "
            f"assignee={_assignee!r}, "
            f"assignees={_assignees!r}, "
            f"base={_base!r}, "
            f"body={_body!r}, "
            f"changed_files={_changed_files!r}, "
            f"closed_at={_closed_at!r}, "
            f"comments={_comments!r}, "
            f"content_version={_content_version!r}, "
            f"created_at={_created_at!r}, "
            f"deletions={_deletions!r}, "
            f"diff_url={_diff_url!r}, "
            f"draft={_draft!r}, "
            f"due_date={_due_date!r}, "
            f"head={_head!r}, "
            f"html_url={_html_url!r}, "
            f"id={_id!r}, "
            f"is_locked={_is_locked!r}, "
            f"labels={_labels!r}, "
            f"merge_base={_merge_base!r}, "
            f"merge_commit_sha={_merge_commit_sha!r}, "
            f"mergeable={_mergeable!r}, "
            f"merged={_merged!r}, "
            f"merged_at={_merged_at!r}, "
            f"merged_by={_merged_by!r}, "
            f"milestone={_milestone!r}, "
            f"number={_number!r}, "
            f"patch_url={_patch_url!r}, "
            f"pin_order={_pin_order!r}, "
            f"requested_reviewers={_requested_reviewers!r}, "
            f"requested_reviewers_teams={_requested_reviewers_teams!r}, "
            f"review_comments={_review_comments!r}, "
            f"state={_state!r}, "
            f"title={_title!r}, "
            f"updated_at={_updated_at!r}, "
            f"url={_url!r}, "
            f"user={_user!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _additions=(
            self.additions
            if hasattr(self, "additions")
            else None
        )
        _allow_maintainer_edit=(
            self.allow_maintainer_edit
            if hasattr(self, "allow_maintainer_edit")
            else None
        )
        _assignee=(
            self.assignee
            if hasattr(self, "assignee")
            else None
        )
        _assignees=(
            self.assignees
            if hasattr(self, "assignees")
            else None
        )
        _base=(
            self.base
            if hasattr(self, "base")
            else None
        )
        _body=(
            self.body
            if hasattr(self, "body")
            else None
        )
        _changed_files=(
            self.changed_files
            if hasattr(self, "changed_files")
            else None
        )
        _closed_at=(
            self.closed_at
            if hasattr(self, "closed_at")
            else None
        )
        _comments=(
            self.comments
            if hasattr(self, "comments")
            else None
        )
        _content_version=(
            self.content_version
            if hasattr(self, "content_version")
            else None
        )
        _created_at=(
            self.created_at
            if hasattr(self, "created_at")
            else None
        )
        _deletions=(
            self.deletions
            if hasattr(self, "deletions")
            else None
        )
        _diff_url=(
            self.diff_url
            if hasattr(self, "diff_url")
            else None
        )
        _draft=(
            self.draft
            if hasattr(self, "draft")
            else None
        )
        _due_date=(
            self.due_date
            if hasattr(self, "due_date")
            else None
        )
        _head=(
            self.head
            if hasattr(self, "head")
            else None
        )
        _html_url=(
            self.html_url
            if hasattr(self, "html_url")
            else None
        )
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _is_locked=(
            self.is_locked
            if hasattr(self, "is_locked")
            else None
        )
        _labels=(
            self.labels
            if hasattr(self, "labels")
            else None
        )
        _merge_base=(
            self.merge_base
            if hasattr(self, "merge_base")
            else None
        )
        _merge_commit_sha=(
            self.merge_commit_sha
            if hasattr(self, "merge_commit_sha")
            else None
        )
        _mergeable=(
            self.mergeable
            if hasattr(self, "mergeable")
            else None
        )
        _merged=(
            self.merged
            if hasattr(self, "merged")
            else None
        )
        _merged_at=(
            self.merged_at
            if hasattr(self, "merged_at")
            else None
        )
        _merged_by=(
            self.merged_by
            if hasattr(self, "merged_by")
            else None
        )
        _milestone=(
            self.milestone
            if hasattr(self, "milestone")
            else None
        )
        _number=(
            self.number
            if hasattr(self, "number")
            else None
        )
        _patch_url=(
            self.patch_url
            if hasattr(self, "patch_url")
            else None
        )
        _pin_order=(
            self.pin_order
            if hasattr(self, "pin_order")
            else None
        )
        _requested_reviewers=(
            self.requested_reviewers
            if hasattr(self, "requested_reviewers")
            else None
        )
        _requested_reviewers_teams=(
            self.requested_reviewers_teams
            if hasattr(self, "requested_reviewers_teams")
            else None
        )
        _review_comments=(
            self.review_comments
            if hasattr(self, "review_comments")
            else None
        )
        _state=(
            self.state
            if hasattr(self, "state")
            else None
        )
        _title=(
            self.title
            if hasattr(self, "title")
            else None
        )
        _updated_at=(
            self.updated_at
            if hasattr(self, "updated_at")
            else None
        )
        _url=(
            self.url
            if hasattr(self, "url")
            else None
        )
        _user=(
            self.user
            if hasattr(self, "user")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"additions={_additions!s}, "
            f"allow_maintainer_edit={_allow_maintainer_edit!s}, "
            f"assignee={_assignee!s}, "
            f"assignees={_assignees!s}, "
            f"base={_base!s}, "
            f"body={_body!s}, "
            f"changed_files={_changed_files!s}, "
            f"closed_at={_closed_at!s}, "
            f"comments={_comments!s}, "
            f"content_version={_content_version!s}, "
            f"created_at={_created_at!s}, "
            f"deletions={_deletions!s}, "
            f"diff_url={_diff_url!s}, "
            f"draft={_draft!s}, "
            f"due_date={_due_date!s}, "
            f"head={_head!s}, "
            f"html_url={_html_url!s}, "
            f"id={_id!s}, "
            f"is_locked={_is_locked!s}, "
            f"labels={_labels!s}, "
            f"merge_base={_merge_base!s}, "
            f"merge_commit_sha={_merge_commit_sha!s}, "
            f"mergeable={_mergeable!s}, "
            f"merged={_merged!s}, "
            f"merged_at={_merged_at!s}, "
            f"merged_by={_merged_by!s}, "
            f"milestone={_milestone!s}, "
            f"number={_number!s}, "
            f"patch_url={_patch_url!s}, "
            f"pin_order={_pin_order!s}, "
            f"requested_reviewers={_requested_reviewers!s}, "
            f"requested_reviewers_teams={_requested_reviewers_teams!s}, "
            f"review_comments={_review_comments!s}, "
            f"state={_state!s}, "
            f"title={_title!s}, "
            f"updated_at={_updated_at!s}, "
            f"url={_url!s}, "
            f"user={_user!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
