"""gitea.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from gitea.api_helper import APIHelper
from gitea.models.pull_request_minimal_head_repo_is_a_minimal_description_of_the_repository_on_one_side_of_a_pull_request import (  # noqa: E501
    PullRequestMinimalHeadRepoIsAMinimalDescriptionOfTheRepositoryOnOneSideOfAPullRequest,
)


class PullRequestMinimalHeadIsAMinimalDescriptionOfOneSideOfAPullRequest(object):
    """Implementation of the
    'PullRequestMinimalHead is a minimal description of one side of a pull request.' model.

    Attributes:
        ref (str): The model property of type str.
        repo (PullRequestMinimalHeadRepoIsAMinimalDescriptionOfTheRepositoryOnOneSideO
            fAPullRequest): The model property of type
            PullRequestMinimalHeadRepoIsAMinimalDescriptionOfTheRepositoryOnOneSideOfA
            PullRequest.
        sha (str): The model property of type str.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "ref": "ref",
        "repo": "repo",
        "sha": "sha",
    }

    _optionals = [
        "ref",
        "repo",
        "sha",
    ]

    def __init__(
        self,
        ref=APIHelper.SKIP,
        repo=APIHelper.SKIP,
        sha=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a
        PullRequestMinimalHeadIsAMinimalDescriptionOfOneSideOfAPullRequest instance.
        """
        # Initialize members of the class
        if ref is not APIHelper.SKIP:
            self.ref = ref
        if repo is not APIHelper.SKIP:
            self.repo = repo
        if sha is not APIHelper.SKIP:
            self.sha = sha

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        ref =\
            dictionary.get("ref")\
            if dictionary.get("ref")\
                else APIHelper.SKIP
        repo =\
            PullRequestMinimalHeadRepoIsAMinimalDescriptionOfTheRepositoryOnOneSideOfAPullRequest.from_dictionary(
                dictionary.get("repo"))\
                if "repo" in dictionary.keys()\
                else APIHelper.SKIP
        sha =\
            dictionary.get("sha")\
            if dictionary.get("sha")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(ref,
                   repo,
                   sha,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _ref=(
            self.ref
            if hasattr(self, "ref")
            else None
        )
        _repo=(
            self.repo
            if hasattr(self, "repo")
            else None
        )
        _sha=(
            self.sha
            if hasattr(self, "sha")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"ref={_ref!r}, "
            f"repo={_repo!r}, "
            f"sha={_sha!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _ref=(
            self.ref
            if hasattr(self, "ref")
            else None
        )
        _repo=(
            self.repo
            if hasattr(self, "repo")
            else None
        )
        _sha=(
            self.sha
            if hasattr(self, "sha")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"ref={_ref!s}, "
            f"repo={_repo!s}, "
            f"sha={_sha!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
