"""gitea.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class Service(object):
    """Implementation of the 'Service' enum.

    Attributes:
        GIT: The enum member of type str.
        GITHUB: The enum member of type str.
        GITEA: The enum member of type str.
        GITLAB: The enum member of type str.
        GOGS: The enum member of type str.
        ONEDEV: The enum member of type str.
        GITBUCKET: The enum member of type str.
        CODEBASE: The enum member of type str.
        CODECOMMIT: The enum member of type str.

    """

    GIT = "git"

    GITHUB = "github"

    GITEA = "gitea"

    GITLAB = "gitlab"

    GOGS = "gogs"

    ONEDEV = "onedev"

    GITBUCKET = "gitbucket"

    CODEBASE = "codebase"

    CODECOMMIT = "codecommit"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
