"""gitea.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from gitea.api_helper import APIHelper
from gitea.models.organization import Organization


class Team(object):
    """Implementation of the 'Team' model.

    Team represents a team in an organization

    Attributes:
        can_create_org_repo (bool): Whether the team can create repositories in the
            organization
        description (str): The description of the team
        id (int): The unique identifier of the team
        includes_all_repositories (bool): Whether the team has access to all
            repositories in the organization
        name (str): The name of the team
        organization (Organization): Organization represents an organization
        permission (Permission1): The model property of type Permission1.
        units (List[str]): The model property of type List[str].
        units_map (Dict[str, str]): The model property of type Dict[str, str].
        visibility (Visibility2): Team visibility within the organization. "private"
            teams are only listable by members and org owners; "limited" teams are
            listable by any organization member; "public" teams are listable by any
            signed-in user. public TeamVisibilityPublic limited TeamVisibilityLimited
            private TeamVisibilityPrivate
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "can_create_org_repo": "can_create_org_repo",
        "description": "description",
        "id": "id",
        "includes_all_repositories": "includes_all_repositories",
        "name": "name",
        "organization": "organization",
        "permission": "permission",
        "units": "units",
        "units_map": "units_map",
        "visibility": "visibility",
    }

    _optionals = [
        "can_create_org_repo",
        "description",
        "id",
        "includes_all_repositories",
        "name",
        "organization",
        "permission",
        "units",
        "units_map",
        "visibility",
    ]

    def __init__(
        self,
        can_create_org_repo=APIHelper.SKIP,
        description=APIHelper.SKIP,
        id=APIHelper.SKIP,
        includes_all_repositories=APIHelper.SKIP,
        name=APIHelper.SKIP,
        organization=APIHelper.SKIP,
        permission=APIHelper.SKIP,
        units=APIHelper.SKIP,
        units_map=APIHelper.SKIP,
        visibility=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Team instance."""
        # Initialize members of the class
        if can_create_org_repo is not APIHelper.SKIP:
            self.can_create_org_repo = can_create_org_repo
        if description is not APIHelper.SKIP:
            self.description = description
        if id is not APIHelper.SKIP:
            self.id = id
        if includes_all_repositories is not APIHelper.SKIP:
            self.includes_all_repositories = includes_all_repositories
        if name is not APIHelper.SKIP:
            self.name = name
        if organization is not APIHelper.SKIP:
            self.organization = organization
        if permission is not APIHelper.SKIP:
            self.permission = permission
        if units is not APIHelper.SKIP:
            self.units = units
        if units_map is not APIHelper.SKIP:
            self.units_map = units_map
        if visibility is not APIHelper.SKIP:
            self.visibility = visibility

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        can_create_org_repo =\
            dictionary.get("can_create_org_repo")\
            if "can_create_org_repo" in dictionary.keys()\
                else APIHelper.SKIP
        description =\
            dictionary.get("description")\
            if dictionary.get("description")\
                else APIHelper.SKIP
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else APIHelper.SKIP
        includes_all_repositories =\
            dictionary.get("includes_all_repositories")\
            if "includes_all_repositories" in dictionary.keys()\
                else APIHelper.SKIP
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else APIHelper.SKIP
        organization =\
            Organization.from_dictionary(
                dictionary.get("organization"))\
                if "organization" in dictionary.keys()\
                else APIHelper.SKIP
        permission =\
            dictionary.get("permission")\
            if dictionary.get("permission")\
                else APIHelper.SKIP
        units =\
            dictionary.get("units")\
            if dictionary.get("units")\
                else APIHelper.SKIP
        units_map =\
            dictionary.get("units_map")\
            if dictionary.get("units_map")\
                else APIHelper.SKIP
        visibility =\
            dictionary.get("visibility")\
            if dictionary.get("visibility")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(can_create_org_repo,
                   description,
                   id,
                   includes_all_repositories,
                   name,
                   organization,
                   permission,
                   units,
                   units_map,
                   visibility,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _can_create_org_repo=(
            self.can_create_org_repo
            if hasattr(self, "can_create_org_repo")
            else None
        )
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _includes_all_repositories=(
            self.includes_all_repositories
            if hasattr(self, "includes_all_repositories")
            else None
        )
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _organization=(
            self.organization
            if hasattr(self, "organization")
            else None
        )
        _permission=(
            self.permission
            if hasattr(self, "permission")
            else None
        )
        _units=(
            self.units
            if hasattr(self, "units")
            else None
        )
        _units_map=(
            self.units_map
            if hasattr(self, "units_map")
            else None
        )
        _visibility=(
            self.visibility
            if hasattr(self, "visibility")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"can_create_org_repo={_can_create_org_repo!r}, "
            f"description={_description!r}, "
            f"id={_id!r}, "
            f"includes_all_repositories={_includes_all_repositories!r}, "
            f"name={_name!r}, "
            f"organization={_organization!r}, "
            f"permission={_permission!r}, "
            f"units={_units!r}, "
            f"units_map={_units_map!r}, "
            f"visibility={_visibility!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _can_create_org_repo=(
            self.can_create_org_repo
            if hasattr(self, "can_create_org_repo")
            else None
        )
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _includes_all_repositories=(
            self.includes_all_repositories
            if hasattr(self, "includes_all_repositories")
            else None
        )
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _organization=(
            self.organization
            if hasattr(self, "organization")
            else None
        )
        _permission=(
            self.permission
            if hasattr(self, "permission")
            else None
        )
        _units=(
            self.units
            if hasattr(self, "units")
            else None
        )
        _units_map=(
            self.units_map
            if hasattr(self, "units_map")
            else None
        )
        _visibility=(
            self.visibility
            if hasattr(self, "visibility")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"can_create_org_repo={_can_create_org_repo!s}, "
            f"description={_description!s}, "
            f"id={_id!s}, "
            f"includes_all_repositories={_includes_all_repositories!s}, "
            f"name={_name!s}, "
            f"organization={_organization!s}, "
            f"permission={_permission!s}, "
            f"units={_units!s}, "
            f"units_map={_units_map!s}, "
            f"visibility={_visibility!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
