"""gitea.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from gitea.api_helper import APIHelper
from gitea.models.comment import Comment
from gitea.models.issue import Issue
from gitea.models.label import Label
from gitea.models.milestone import Milestone
from gitea.models.team import Team
from gitea.models.tracked_time import TrackedTime
from gitea.models.user import User


class TimelineComment(object):
    """Implementation of the 'TimelineComment' model.

    TimelineComment represents a timeline comment (comment of any type) on a commit
    or issue

    Attributes:
        assignee (User): User represents a user
        assignee_team (Team): Team represents a team in an organization
        body (str): Body contains the timeline event content
        created_at (datetime): The model property of type datetime.
        dependent_issue (Issue): Issue represents an issue in a repository
        html_url (str): HTMLURL is the web URL for viewing the comment
        id (int): ID is the unique identifier for the timeline comment
        issue_url (str): IssueURL is the API URL for the issue
        label (Label): Label a label to an issue or a pr
        milestone (Milestone): Milestone milestone is a collection of issues on one
            repository
        new_ref (str): The model property of type str.
        new_title (str): The model property of type str.
        old_milestone (Milestone): Milestone milestone is a collection of issues on
            one repository
        old_project_id (int): The model property of type int.
        old_ref (str): The model property of type str.
        old_title (str): The model property of type str.
        project_id (int): The model property of type int.
        pull_request_url (str): PRURL is the API URL for the pull request (if
            applicable)
        ref_action (str): The model property of type str.
        ref_comment (Comment): Comment represents a comment on a commit or issue
        ref_commit_sha (str): commit SHA where issue/PR was referenced
        ref_issue (Issue): Issue represents an issue in a repository
        removed_assignee (bool): whether the assignees were removed or added
        resolve_doer (User): User represents a user
        review_id (int): The model property of type int.
        tracked_time (TrackedTime): TrackedTime worked time for an issue / pr
        mtype (str): Type indicates the type of timeline event
        updated_at (datetime): The model property of type datetime.
        user (User): User represents a user
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "assignee": "assignee",
        "assignee_team": "assignee_team",
        "body": "body",
        "created_at": "created_at",
        "dependent_issue": "dependent_issue",
        "html_url": "html_url",
        "id": "id",
        "issue_url": "issue_url",
        "label": "label",
        "milestone": "milestone",
        "new_ref": "new_ref",
        "new_title": "new_title",
        "old_milestone": "old_milestone",
        "old_project_id": "old_project_id",
        "old_ref": "old_ref",
        "old_title": "old_title",
        "project_id": "project_id",
        "pull_request_url": "pull_request_url",
        "ref_action": "ref_action",
        "ref_comment": "ref_comment",
        "ref_commit_sha": "ref_commit_sha",
        "ref_issue": "ref_issue",
        "removed_assignee": "removed_assignee",
        "resolve_doer": "resolve_doer",
        "review_id": "review_id",
        "tracked_time": "tracked_time",
        "mtype": "type",
        "updated_at": "updated_at",
        "user": "user",
    }

    _optionals = [
        "assignee",
        "assignee_team",
        "body",
        "created_at",
        "dependent_issue",
        "html_url",
        "id",
        "issue_url",
        "label",
        "milestone",
        "new_ref",
        "new_title",
        "old_milestone",
        "old_project_id",
        "old_ref",
        "old_title",
        "project_id",
        "pull_request_url",
        "ref_action",
        "ref_comment",
        "ref_commit_sha",
        "ref_issue",
        "removed_assignee",
        "resolve_doer",
        "review_id",
        "tracked_time",
        "mtype",
        "updated_at",
        "user",
    ]

    def __init__(
        self,
        assignee=APIHelper.SKIP,
        assignee_team=APIHelper.SKIP,
        body=APIHelper.SKIP,
        created_at=APIHelper.SKIP,
        dependent_issue=APIHelper.SKIP,
        html_url=APIHelper.SKIP,
        id=APIHelper.SKIP,
        issue_url=APIHelper.SKIP,
        label=APIHelper.SKIP,
        milestone=APIHelper.SKIP,
        new_ref=APIHelper.SKIP,
        new_title=APIHelper.SKIP,
        old_milestone=APIHelper.SKIP,
        old_project_id=APIHelper.SKIP,
        old_ref=APIHelper.SKIP,
        old_title=APIHelper.SKIP,
        project_id=APIHelper.SKIP,
        pull_request_url=APIHelper.SKIP,
        ref_action=APIHelper.SKIP,
        ref_comment=APIHelper.SKIP,
        ref_commit_sha=APIHelper.SKIP,
        ref_issue=APIHelper.SKIP,
        removed_assignee=APIHelper.SKIP,
        resolve_doer=APIHelper.SKIP,
        review_id=APIHelper.SKIP,
        tracked_time=APIHelper.SKIP,
        mtype=APIHelper.SKIP,
        updated_at=APIHelper.SKIP,
        user=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a TimelineComment instance."""
        # Initialize members of the class
        if assignee is not APIHelper.SKIP:
            self.assignee = assignee
        if assignee_team is not APIHelper.SKIP:
            self.assignee_team = assignee_team
        if body is not APIHelper.SKIP:
            self.body = body
        if created_at is not APIHelper.SKIP:
            self.created_at =\
                 APIHelper.apply_datetime_converter(
                created_at, APIHelper.RFC3339DateTime)\
                 if created_at else None
        if dependent_issue is not APIHelper.SKIP:
            self.dependent_issue = dependent_issue
        if html_url is not APIHelper.SKIP:
            self.html_url = html_url
        if id is not APIHelper.SKIP:
            self.id = id
        if issue_url is not APIHelper.SKIP:
            self.issue_url = issue_url
        if label is not APIHelper.SKIP:
            self.label = label
        if milestone is not APIHelper.SKIP:
            self.milestone = milestone
        if new_ref is not APIHelper.SKIP:
            self.new_ref = new_ref
        if new_title is not APIHelper.SKIP:
            self.new_title = new_title
        if old_milestone is not APIHelper.SKIP:
            self.old_milestone = old_milestone
        if old_project_id is not APIHelper.SKIP:
            self.old_project_id = old_project_id
        if old_ref is not APIHelper.SKIP:
            self.old_ref = old_ref
        if old_title is not APIHelper.SKIP:
            self.old_title = old_title
        if project_id is not APIHelper.SKIP:
            self.project_id = project_id
        if pull_request_url is not APIHelper.SKIP:
            self.pull_request_url = pull_request_url
        if ref_action is not APIHelper.SKIP:
            self.ref_action = ref_action
        if ref_comment is not APIHelper.SKIP:
            self.ref_comment = ref_comment
        if ref_commit_sha is not APIHelper.SKIP:
            self.ref_commit_sha = ref_commit_sha
        if ref_issue is not APIHelper.SKIP:
            self.ref_issue = ref_issue
        if removed_assignee is not APIHelper.SKIP:
            self.removed_assignee = removed_assignee
        if resolve_doer is not APIHelper.SKIP:
            self.resolve_doer = resolve_doer
        if review_id is not APIHelper.SKIP:
            self.review_id = review_id
        if tracked_time is not APIHelper.SKIP:
            self.tracked_time = tracked_time
        if mtype is not APIHelper.SKIP:
            self.mtype = mtype
        if updated_at is not APIHelper.SKIP:
            self.updated_at =\
                 APIHelper.apply_datetime_converter(
                updated_at, APIHelper.RFC3339DateTime)\
                 if updated_at else None
        if user is not APIHelper.SKIP:
            self.user = user

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        assignee =\
            User.from_dictionary(
                dictionary.get("assignee"))\
                if "assignee" in dictionary.keys()\
                else APIHelper.SKIP
        assignee_team =\
            Team.from_dictionary(
                dictionary.get("assignee_team"))\
                if "assignee_team" in dictionary.keys()\
                else APIHelper.SKIP
        body =\
            dictionary.get("body")\
            if dictionary.get("body")\
                else APIHelper.SKIP
        created_at = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("created_at")).datetime\
            if dictionary.get("created_at") else APIHelper.SKIP
        dependent_issue =\
            Issue.from_dictionary(
                dictionary.get("dependent_issue"))\
                if "dependent_issue" in dictionary.keys()\
                else APIHelper.SKIP
        html_url =\
            dictionary.get("html_url")\
            if dictionary.get("html_url")\
                else APIHelper.SKIP
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else APIHelper.SKIP
        issue_url =\
            dictionary.get("issue_url")\
            if dictionary.get("issue_url")\
                else APIHelper.SKIP
        label =\
            Label.from_dictionary(
                dictionary.get("label"))\
                if "label" in dictionary.keys()\
                else APIHelper.SKIP
        milestone =\
            Milestone.from_dictionary(
                dictionary.get("milestone"))\
                if "milestone" in dictionary.keys()\
                else APIHelper.SKIP
        new_ref =\
            dictionary.get("new_ref")\
            if dictionary.get("new_ref")\
                else APIHelper.SKIP
        new_title =\
            dictionary.get("new_title")\
            if dictionary.get("new_title")\
                else APIHelper.SKIP
        old_milestone =\
            Milestone.from_dictionary(
                dictionary.get("old_milestone"))\
                if "old_milestone" in dictionary.keys()\
                else APIHelper.SKIP
        old_project_id =\
            dictionary.get("old_project_id")\
            if dictionary.get("old_project_id")\
                else APIHelper.SKIP
        old_ref =\
            dictionary.get("old_ref")\
            if dictionary.get("old_ref")\
                else APIHelper.SKIP
        old_title =\
            dictionary.get("old_title")\
            if dictionary.get("old_title")\
                else APIHelper.SKIP
        project_id =\
            dictionary.get("project_id")\
            if dictionary.get("project_id")\
                else APIHelper.SKIP
        pull_request_url =\
            dictionary.get("pull_request_url")\
            if dictionary.get("pull_request_url")\
                else APIHelper.SKIP
        ref_action =\
            dictionary.get("ref_action")\
            if dictionary.get("ref_action")\
                else APIHelper.SKIP
        ref_comment =\
            Comment.from_dictionary(
                dictionary.get("ref_comment"))\
                if "ref_comment" in dictionary.keys()\
                else APIHelper.SKIP
        ref_commit_sha =\
            dictionary.get("ref_commit_sha")\
            if dictionary.get("ref_commit_sha")\
                else APIHelper.SKIP
        ref_issue =\
            Issue.from_dictionary(
                dictionary.get("ref_issue"))\
                if "ref_issue" in dictionary.keys()\
                else APIHelper.SKIP
        removed_assignee =\
            dictionary.get("removed_assignee")\
            if "removed_assignee" in dictionary.keys()\
                else APIHelper.SKIP
        resolve_doer =\
            User.from_dictionary(
                dictionary.get("resolve_doer"))\
                if "resolve_doer" in dictionary.keys()\
                else APIHelper.SKIP
        review_id =\
            dictionary.get("review_id")\
            if dictionary.get("review_id")\
                else APIHelper.SKIP
        tracked_time =\
            TrackedTime.from_dictionary(
                dictionary.get("tracked_time"))\
                if "tracked_time" in dictionary.keys()\
                else APIHelper.SKIP
        mtype =\
            dictionary.get("type")\
            if dictionary.get("type")\
                else APIHelper.SKIP
        updated_at = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("updated_at")).datetime\
            if dictionary.get("updated_at") else APIHelper.SKIP
        user =\
            User.from_dictionary(
                dictionary.get("user"))\
                if "user" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(assignee,
                   assignee_team,
                   body,
                   created_at,
                   dependent_issue,
                   html_url,
                   id,
                   issue_url,
                   label,
                   milestone,
                   new_ref,
                   new_title,
                   old_milestone,
                   old_project_id,
                   old_ref,
                   old_title,
                   project_id,
                   pull_request_url,
                   ref_action,
                   ref_comment,
                   ref_commit_sha,
                   ref_issue,
                   removed_assignee,
                   resolve_doer,
                   review_id,
                   tracked_time,
                   mtype,
                   updated_at,
                   user,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _assignee=(
            self.assignee
            if hasattr(self, "assignee")
            else None
        )
        _assignee_team=(
            self.assignee_team
            if hasattr(self, "assignee_team")
            else None
        )
        _body=(
            self.body
            if hasattr(self, "body")
            else None
        )
        _created_at=(
            self.created_at
            if hasattr(self, "created_at")
            else None
        )
        _dependent_issue=(
            self.dependent_issue
            if hasattr(self, "dependent_issue")
            else None
        )
        _html_url=(
            self.html_url
            if hasattr(self, "html_url")
            else None
        )
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _issue_url=(
            self.issue_url
            if hasattr(self, "issue_url")
            else None
        )
        _label=(
            self.label
            if hasattr(self, "label")
            else None
        )
        _milestone=(
            self.milestone
            if hasattr(self, "milestone")
            else None
        )
        _new_ref=(
            self.new_ref
            if hasattr(self, "new_ref")
            else None
        )
        _new_title=(
            self.new_title
            if hasattr(self, "new_title")
            else None
        )
        _old_milestone=(
            self.old_milestone
            if hasattr(self, "old_milestone")
            else None
        )
        _old_project_id=(
            self.old_project_id
            if hasattr(self, "old_project_id")
            else None
        )
        _old_ref=(
            self.old_ref
            if hasattr(self, "old_ref")
            else None
        )
        _old_title=(
            self.old_title
            if hasattr(self, "old_title")
            else None
        )
        _project_id=(
            self.project_id
            if hasattr(self, "project_id")
            else None
        )
        _pull_request_url=(
            self.pull_request_url
            if hasattr(self, "pull_request_url")
            else None
        )
        _ref_action=(
            self.ref_action
            if hasattr(self, "ref_action")
            else None
        )
        _ref_comment=(
            self.ref_comment
            if hasattr(self, "ref_comment")
            else None
        )
        _ref_commit_sha=(
            self.ref_commit_sha
            if hasattr(self, "ref_commit_sha")
            else None
        )
        _ref_issue=(
            self.ref_issue
            if hasattr(self, "ref_issue")
            else None
        )
        _removed_assignee=(
            self.removed_assignee
            if hasattr(self, "removed_assignee")
            else None
        )
        _resolve_doer=(
            self.resolve_doer
            if hasattr(self, "resolve_doer")
            else None
        )
        _review_id=(
            self.review_id
            if hasattr(self, "review_id")
            else None
        )
        _tracked_time=(
            self.tracked_time
            if hasattr(self, "tracked_time")
            else None
        )
        _mtype=(
            self.mtype
            if hasattr(self, "mtype")
            else None
        )
        _updated_at=(
            self.updated_at
            if hasattr(self, "updated_at")
            else None
        )
        _user=(
            self.user
            if hasattr(self, "user")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"assignee={_assignee!r}, "
            f"assignee_team={_assignee_team!r}, "
            f"body={_body!r}, "
            f"created_at={_created_at!r}, "
            f"dependent_issue={_dependent_issue!r}, "
            f"html_url={_html_url!r}, "
            f"id={_id!r}, "
            f"issue_url={_issue_url!r}, "
            f"label={_label!r}, "
            f"milestone={_milestone!r}, "
            f"new_ref={_new_ref!r}, "
            f"new_title={_new_title!r}, "
            f"old_milestone={_old_milestone!r}, "
            f"old_project_id={_old_project_id!r}, "
            f"old_ref={_old_ref!r}, "
            f"old_title={_old_title!r}, "
            f"project_id={_project_id!r}, "
            f"pull_request_url={_pull_request_url!r}, "
            f"ref_action={_ref_action!r}, "
            f"ref_comment={_ref_comment!r}, "
            f"ref_commit_sha={_ref_commit_sha!r}, "
            f"ref_issue={_ref_issue!r}, "
            f"removed_assignee={_removed_assignee!r}, "
            f"resolve_doer={_resolve_doer!r}, "
            f"review_id={_review_id!r}, "
            f"tracked_time={_tracked_time!r}, "
            f"mtype={_mtype!r}, "
            f"updated_at={_updated_at!r}, "
            f"user={_user!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _assignee=(
            self.assignee
            if hasattr(self, "assignee")
            else None
        )
        _assignee_team=(
            self.assignee_team
            if hasattr(self, "assignee_team")
            else None
        )
        _body=(
            self.body
            if hasattr(self, "body")
            else None
        )
        _created_at=(
            self.created_at
            if hasattr(self, "created_at")
            else None
        )
        _dependent_issue=(
            self.dependent_issue
            if hasattr(self, "dependent_issue")
            else None
        )
        _html_url=(
            self.html_url
            if hasattr(self, "html_url")
            else None
        )
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _issue_url=(
            self.issue_url
            if hasattr(self, "issue_url")
            else None
        )
        _label=(
            self.label
            if hasattr(self, "label")
            else None
        )
        _milestone=(
            self.milestone
            if hasattr(self, "milestone")
            else None
        )
        _new_ref=(
            self.new_ref
            if hasattr(self, "new_ref")
            else None
        )
        _new_title=(
            self.new_title
            if hasattr(self, "new_title")
            else None
        )
        _old_milestone=(
            self.old_milestone
            if hasattr(self, "old_milestone")
            else None
        )
        _old_project_id=(
            self.old_project_id
            if hasattr(self, "old_project_id")
            else None
        )
        _old_ref=(
            self.old_ref
            if hasattr(self, "old_ref")
            else None
        )
        _old_title=(
            self.old_title
            if hasattr(self, "old_title")
            else None
        )
        _project_id=(
            self.project_id
            if hasattr(self, "project_id")
            else None
        )
        _pull_request_url=(
            self.pull_request_url
            if hasattr(self, "pull_request_url")
            else None
        )
        _ref_action=(
            self.ref_action
            if hasattr(self, "ref_action")
            else None
        )
        _ref_comment=(
            self.ref_comment
            if hasattr(self, "ref_comment")
            else None
        )
        _ref_commit_sha=(
            self.ref_commit_sha
            if hasattr(self, "ref_commit_sha")
            else None
        )
        _ref_issue=(
            self.ref_issue
            if hasattr(self, "ref_issue")
            else None
        )
        _removed_assignee=(
            self.removed_assignee
            if hasattr(self, "removed_assignee")
            else None
        )
        _resolve_doer=(
            self.resolve_doer
            if hasattr(self, "resolve_doer")
            else None
        )
        _review_id=(
            self.review_id
            if hasattr(self, "review_id")
            else None
        )
        _tracked_time=(
            self.tracked_time
            if hasattr(self, "tracked_time")
            else None
        )
        _mtype=(
            self.mtype
            if hasattr(self, "mtype")
            else None
        )
        _updated_at=(
            self.updated_at
            if hasattr(self, "updated_at")
            else None
        )
        _user=(
            self.user
            if hasattr(self, "user")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"assignee={_assignee!s}, "
            f"assignee_team={_assignee_team!s}, "
            f"body={_body!s}, "
            f"created_at={_created_at!s}, "
            f"dependent_issue={_dependent_issue!s}, "
            f"html_url={_html_url!s}, "
            f"id={_id!s}, "
            f"issue_url={_issue_url!s}, "
            f"label={_label!s}, "
            f"milestone={_milestone!s}, "
            f"new_ref={_new_ref!s}, "
            f"new_title={_new_title!s}, "
            f"old_milestone={_old_milestone!s}, "
            f"old_project_id={_old_project_id!s}, "
            f"old_ref={_old_ref!s}, "
            f"old_title={_old_title!s}, "
            f"project_id={_project_id!s}, "
            f"pull_request_url={_pull_request_url!s}, "
            f"ref_action={_ref_action!s}, "
            f"ref_comment={_ref_comment!s}, "
            f"ref_commit_sha={_ref_commit_sha!s}, "
            f"ref_issue={_ref_issue!s}, "
            f"removed_assignee={_removed_assignee!s}, "
            f"resolve_doer={_resolve_doer!s}, "
            f"review_id={_review_id!s}, "
            f"tracked_time={_tracked_time!s}, "
            f"mtype={_mtype!s}, "
            f"updated_at={_updated_at!s}, "
            f"user={_user!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
