"""gitea.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from gitea.api_helper import APIHelper


class TransferRepoOption(object):
    """Implementation of the 'TransferRepoOption' model.

    TransferRepoOption options when transfer a repository's ownership

    Attributes:
        new_owner (str): The model property of type str.
        team_ids (List[int]): ID of the team or teams to add to the repository. Teams
            can only be added to organization-owned repositories.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "new_owner": "new_owner",
        "team_ids": "team_ids",
    }

    _optionals = [
        "team_ids",
    ]

    def __init__(
        self,
        new_owner=None,
        team_ids=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a TransferRepoOption instance."""
        # Initialize members of the class
        self.new_owner = new_owner
        if team_ids is not APIHelper.SKIP:
            self.team_ids = team_ids

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        new_owner =\
            dictionary.get("new_owner")\
            if dictionary.get("new_owner")\
                else None
        team_ids =\
            dictionary.get("team_ids")\
            if dictionary.get("team_ids")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(new_owner,
                   team_ids,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _new_owner=self.new_owner
        _team_ids=(
            self.team_ids
            if hasattr(self, "team_ids")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"new_owner={_new_owner!r}, "
            f"team_ids={_team_ids!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _new_owner=self.new_owner
        _team_ids=(
            self.team_ids
            if hasattr(self, "team_ids")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"new_owner={_new_owner!s}, "
            f"team_ids={_team_ids!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
