"""gitea.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class Type4(object):
    """Implementation of the 'type4' enum.

    Attributes:
        ALPINE: The enum member of type str.
        CARGO: The enum member of type str.
        CHEF: The enum member of type str.
        COMPOSER: The enum member of type str.
        CONAN: The enum member of type str.
        CONDA: The enum member of type str.
        CONTAINER: The enum member of type str.
        CRAN: The enum member of type str.
        DEBIAN: The enum member of type str.
        GENERIC: The enum member of type str.
        GO: The enum member of type str.
        HELM: The enum member of type str.
        MAVEN: The enum member of type str.
        NPM: The enum member of type str.
        NUGET: The enum member of type str.
        PUB: The enum member of type str.
        PYPI: The enum member of type str.
        RPM: The enum member of type str.
        RUBYGEMS: The enum member of type str.
        SWIFT: The enum member of type str.
        TERRAFORM: The enum member of type str.
        VAGRANT: The enum member of type str.

    """

    ALPINE = "alpine"

    CARGO = "cargo"

    CHEF = "chef"

    COMPOSER = "composer"

    CONAN = "conan"

    CONDA = "conda"

    CONTAINER = "container"

    CRAN = "cran"

    DEBIAN = "debian"

    GENERIC = "generic"

    GO = "go"

    HELM = "helm"

    MAVEN = "maven"

    NPM = "npm"

    NUGET = "nuget"

    PUB = "pub"

    PYPI = "pypi"

    RPM = "rpm"

    RUBYGEMS = "rubygems"

    SWIFT = "swift"

    TERRAFORM = "terraform"

    VAGRANT = "vagrant"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
