"""gitea.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class Visibility2(object):
    """Implementation of the 'Visibility2' enum.

    Team visibility within the organization. "private" teams are only
    listable by members and org owners; "limited" teams are listable by
    any organization member; "public" teams are listable by any signed-in
    user.
    public TeamVisibilityPublic
    limited TeamVisibilityLimited
    private TeamVisibilityPrivate

    Attributes:
        PUBLIC: The enum member of type str.
        LIMITED: The enum member of type str.
        PRIVATE: The enum member of type str.

    """

    PUBLIC = "public"

    LIMITED = "limited"

    PRIVATE = "private"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
